### ISSUE TITLE
How to handle source jar?

### ISSUE THREAD

**Issue by daschl** [johnrengelman/shadow#112]
Hi @johnrengelman 

We're successfully shadowing our deps (https://github.com/couchbase/couchbase-jvm-core/blob/master/build.gradle) but one thing that does not work is also creating a correct sources jar!

I'm sure this works, can you provide a simple example? That would be amazing, thanks!

**Comment by robisrob** [comment]
Is this a feature that is planned in the near future?

**Comment by juddgaddie** [comment]
@schulzp I have found an issue with ArtifactResolutionQuery API in that it does not resolve dependencies for project deps in multi project build. I have created an issue on [Gradle Discuss 19890](https://discuss.gradle.org/t/how-to-create-an-uber-source-jar-of-dependencies-in-multi-project-build/19890)

**Comment by johnrengelman** [comment]
Duplicate of https://github.com/johnrengelman/shadow/issues/41
