### ISSUE TITLE
Resource files in dependencies are not relocated

### ISSUE THREAD

**Issue by johnrengelman** [johnrengelman/shadow#114]
Same as https://github.com/johnrengelman/shadow/issues/93 but for resource files in dependencies.

**Comment by sbuettner** [comment]
Could need this to since relocating httpclient doesnt move all the property files it comes with.

**Comment by johnrengelman** [comment]
Fixed and released. Sorry this took so long.

**Comment by pron** [comment]
Yay! Thanks!

**Comment by pron** [comment]
Works great. Thanks again.

**Comment by sbuettner** [comment]
Works great. Thank you. :metal:
