### ISSUE TITLE
Can't include a directory outside the dist directory into the application distribution

### ISSUE THREAD

**Issue by mcarlin** [johnrengelman/shadow#118]
Hey @johnrengelman 

I've been trying to include a directory outside the dist directory in to the application distribution. When doing this with the installApp task the directory is properly brought into the install build directory but when using the installShadowApp it isn't copied into the installShadow build directory. I've used the following code to include the directory

```groovy
applicationDistribution.from('config') {
    into "config"
}
```

Is there something I'm missing?

**Comment by johnrengelman** [comment]
The `installShadow` is controlled by a separate `applicationDistribution`. Try setting this:
```
shadow.applicationDistribution.from('config') {
  into "config"
}
```

**Comment by mcarlin** [comment]
* What went wrong:
A problem occurred evaluating project ':Controller'.
> Could not find property 'ApplicationDistribution' on com.github.jengelman.gradle.plugins.shadow.ShadowExtension_Decorated@4db0747b.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.864 secs
Could not find property 'ApplicationDistribution' on com.github.jengelman.gradle.plugins.shadow.ShadowExtension_Decorated@4db0747b.

Looks like I don't have access to the shadow's applicationDistribution from the scope of my build.gradle

**Comment by mcarlin** [comment]
Works great!! Thanks
