### ISSUE TITLE
Remove the "knows" task

### ISSUE THREAD

**Issue by Skamandros** [johnrengelman/shadow#122]
The task named "knows" doesn't serve any purpose. For projects with many Gradle tasks this means that there is a task which consumes space in the task list (e.g. in an IDE), but doesn't provide any useful functionality. Moreover, it could confuse developers which are not familiar with the build setup and the origin of this task.

**Comment by Skamandros** [comment]
Could you elaborate on the close please? :)

**Comment by danhyun** [comment]
This is a fun easter egg task that pays homage to the old radio serial "The Shadow"
https://www.youtube.com/watch?v=uMlRpN8ANrU

**Comment by johnrengelman** [comment]
The addition of the `knows` task causes no problems for a user IMO. If they run it, they get a fun little output.
There are many tasks that are inherently created by Gradle, that users would never or very sparingly use (including myself), so IMO that argument is moot. 
Thanks for your concern though. This is how open source is supposed to work. We won't always agree, but don't hesitate to bring up concerns.

Oh and @danhyun, I prefer the 1994 film staring Alec Baldwin - http://en.wikipedia.org/wiki/The_Shadow_(1994_film)

**Comment by Skamandros** [comment]
Thanks for your response. Though we disagree on that part, I certainly appreciate your work. :)

**Comment by pledbrook** [comment]
@Skamandros has a valid point. May I suggest that all sides can be made relatively happy by having a convention property that disables the easter egg, for example:

    shadow {
        iknow = true
    }

After all, most easter eggs aren't so visible in normal operation. For what it's worth, I like it :smile: But I can see a small value in being able to disable it.

**Comment by jostwald** [comment]
It serves a purpose: Joy.

Pure geeky joy.  I was so happy to find this Easter egg

Agreed that an easy way to suppress it makes sense, though.

**Comment by Goooler** [comment]
This has been resolved by #1236.
