### ISSUE TITLE
Relocation does not seem to work if the exclude element get a package prefix instead of the full classname

### ISSUE THREAD

**Issue by rdsr** [johnrengelman/shadow#124]
This is for version 1.2.0

**Comment by shevek** [comment]
Exclusion by package prefix not working for me either. :-( 1.2.1

**Comment by shevek** [comment]
See #117 ?

**Comment by rdsr** [comment]
Thanks Shevek . It works, the correct syntax being 
exclude 'org/apache/hadoop/hive/ql/io/**'
