### ISSUE TITLE
Property applicationDistribution not recognized

### ISSUE THREAD

**Issue by u6f6o** [johnrengelman/shadow#133]
My project has a folder called dist that contains some stuff I'd like to include in the shadow jar. The application plugin has a property called "applicationDistribution" to address this topic. In my build.gradle I added the following line: 

```groovy
applicationDistribution.from(distDir){
    include "*.jpg"
}
```

While this is working for the application plugin, the shadow plugin seems to ignore this property.

**Comment by johnrengelman** [comment]
Shadow keeps it's own `copySpec` so that it doesn't collide with the normal `applicationDistribution`. Configure it like this:

```
shadow.applicationDistribution.from(distDir) {
  include "*.jpg"
}
```

**Comment by u6f6o** [comment]
Oh I see, ty. It works.
