### ISSUE TITLE
How can I prevent that a zip resource file is extracted.

### ISSUE THREAD

**Issue by lwolter** [johnrengelman/shadow#136]
In my resource directory, a zip file help.zip is included. This file should be taken over unchanged. How can I prevent that the file is extracted?

**Comment by johnrengelman** [comment]
Don't have support this at the moment. I could see that argument that Zip files shouldn't be exploded because I have never encountered the case where I was importing classes using a `zip` and not a `jar`.

**Comment by johnrengelman** [comment]
Zip files will not be unpacked in v2.0.0 of shadow.
