### ISSUE TITLE
How can I exclude a resource in a subproject?

### ISSUE THREAD

**Issue by GoGoris** [johnrengelman/shadow#137]
I have a project with the modules API and view, because I have one really large resource, I want to make a task to build a jar with this resource and one without this resource. I have the following configuration, but the problem is that I don't know how to tell the view-module to compile the API by using the shadowJarWithoutX task instead of the default task.
Any help would be greatly appreciated.

In view:

```
dependencies {
    compile project(':API')
    ...
}

task shadowJarWithoutX(type: ShadowJar) {
    configurations = [project.configurations.runtime]
    mergeServiceFiles()
    archiveName = 'no_x.jar'
    exclude("API/src/main/resources/x")
}
```

**Comment by johnrengelman** [comment]
Just like normal project dependencies, project resources are combined together, so you should do this:
`exclude("x")` 
since the project resources are located at the root of the jar.

**Comment by johnrengelman** [comment]
It's the same as if you wanted to exclude that file from your `jar` task.
