### ISSUE TITLE
Multiple shadowJar tasks

### ISSUE THREAD

**Issue by sergiofagostinho** [johnrengelman/shadow#138]
Hi,

I would like to have to multiple shadowJar tasks in my build.gradle. Namely, I would like to have different JAR names for each task. Here is what I've done:
```groovy
shadowJar {
    mergeServiceFiles()
}

task shadowJar2(type: com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    mergeServiceFiles()
    archiveName = 'foo.jar'
}
```

The thing is, when I run the "shadowJar2" task, the "foo.jar" it produces includes only the manifest, no code. What's the correct way to do this?

P.S.: another person has posted a similar question on [StackOverflow](http://stackoverflow.com/questions/25309250/execute-gradle-shadowjar-task-twice-in-same-build-file).

**Comment by johnrengelman** [comment]
There is a bunch of convention based configuration that happens to the built in `shadowJar` task. When you create your own task of that type that convention is not applied to the task, so you'll have to manually configure it. You can see what is happening here: https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy#L38-L63

**Comment by sergiofagostinho** [comment]
Thanks for the prompt reply.

Humm... this seems a little too complex for what I need.

I've used the following workaround:
```groovy
shadowJar {
    mergeServiceFiles()
    archiveName = System.properties.getProperty('archiveName')
}
```

It's not so elegant as it makes me add a `-ParchiveName=foo.jar` parameter, but it does the job.

**Comment by johnrengelman** [comment]
You only need a couple pieces:

```
task shadowJarFoo(type: ShadowJar) {
  archiveName = 'foo.jar'
  from sourceSets.main.output //tells the task to include the project code
  configurations = [ configurations.runtime ] //tells the task to shadow in the jars files in the 'runtime' scope
```

that would get you the majority of the solution. This is the same configuration that you would have to perform if you were adding a custom `jar` or `zip` task to your project.

**Comment by pavolloffay** [comment]
I get `com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar_Decorated cannot be cast to java.lang.Class` when I define `shadowJarFoo` from the comment above.

**Comment by daviddking** [comment]
If you want to create multiple executable shadow JARs with the same class files but different main class entries in the manifest, you can do this:

```
shadowJar {
  mergeServiceFiles()
}

task shadowJar2(type: Jar, dependsOn: shadowJar) {
  archiveName = 'foo2.jar'
  manifest {
      attributes('Main-Class': 'org.foo.Foo2')
  }
  from zipTree(shadowJar.archivePath)
}

task shadowJar3(type: Jar, dependsOn: shadowJar) {
  archiveName = 'foo3.jar'
  manifest {
      attributes('Main-Class': 'org.foo.Foo3')
  }
  from zipTree(shadowJar.archivePath)
}
```

**Comment by princefisher** [comment]
> I get `com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar_Decorated cannot be cast to java.lang.Class` when I define `shadowJarFoo` from the comment above.

I had this issue as well and there are two options to fix this:
1. Specify the full path:
```
task shadowJarFoo(type: com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    // ...
}
```

2. Import the class before specifying the task:
```
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
task shadowJarBar(type: ShadowJar) {
    // ...
}
```

**Comment by ph4r05** [comment]
In my case I had to add configuration `runtimeClasspath`

```gradle
task shadowJarReloc(type: com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    group 'shadow'    
    from(project.convention.getPlugin(JavaPluginConvention).sourceSets.main.output)
    configurations = [ project.configurations.runtimeClasspath ]
    exclude('META-INF/INDEX.LIST', 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA')
}
```

**Comment by keilhofer** [comment]
Thank you for your solution. As convention is now deprecated one can use 
`from(project.extensions.findByType(JavaPluginExtension.class).sourceSets.main.output)`
instead of 
`from(project.convention.getPlugin(JavaPluginConvention).sourceSets.main.output)`

**Comment by alexanderankin** [comment]
> There is a bunch of convention based configuration that happens to the built in `shadowJar` task. When you create your own task of that type that convention is not applied to the task, so you'll have to manually configure it. You can see what is happening here: https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy#L38-L63

that link was this as of march 14 when the quoted comment was posted: https://github.com/johnrengelman/shadow/blob/b886a34f34f520f05c783e12c11c4fb9fb2804e3/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy#L38-L64
