### ISSUE TITLE
Provided configuration

### ISSUE THREAD

**Issue by rpmoore** [johnrengelman/shadow#140]
I have a provided configuration and I'm trying to figure out how I would go about adding it to shadowjar.  The docs says that it uses the runtime for most of the configuration lookup stuff, but I need to support an offline build where I provide all the libraries.  Is there a way to do this with the current version?

**Comment by johnrengelman** [comment]
```
shadowJar {
  configurations = [ project.configurations.runtime, project.configurations.provided ]
}
```

**Comment by rpmoore** [comment]
Thanks!

Was this in the documentation and I just missed it?

**Comment by johnrengelman** [comment]
It's not in the docs. The docs aren't very good. I need to write better ones. Just difficult finding the time.

**Comment by rpmoore** [comment]
Thanks for this. I'll give it a shot.
