### ISSUE TITLE
Unable to create android AAR

### ISSUE THREAD

**Issue by virl** [johnrengelman/shadow#144]
How to create Android AAR file for my library?

**Comment by johnrengelman** [comment]
No idea. I don't do Android development. Probably a good question for their forums.

**Comment by virl** [comment]
But but but its THE most useful application for that plugin!

**Comment by johnrengelman** [comment]
I don't doubt it. But again, I don't do Android development. I don't know what the format for an AAR library is. I'm sure someone in the Android community would have better insight.
If there is some special support that is needed to build AARs beyond the normal items you can configured with the JAR api, then I'm happy to review and integrate a pull request. 

But I'm not inclined to go research Android development and figure it out for you.

**Comment by virl** [comment]
AAR is just a zip over jar where jar is in file classes.jar

Okay, thanks anyway. Android is pain but throught suffering we can reach the truth.

**Comment by danhyun** [comment]
:bell:

**Comment by kyleboon** [comment]
maybe @pieces029 wants to do this

**Comment by johnrengelman** [comment]
From the description above it seems this would be beyond the concern of Shadow. shadow is not meant to be an all encompassing packaging tool. 

I believe the output above could be accomplished be using an additional Zip task that uses the shadow output as one of the inputs. But this should be the concern of either the android plugin and a new android-aar plugin.
