### ISSUE TITLE
Using shadow in Android app to merge Groovy extension module descriptors

### ISSUE THREAD

**Issue by mariogarcia** [johnrengelman/shadow#149]
Hi:

First of all, great plugin :+1: 

I would like to merge some Groovy extension module files in an Android app. Checking the docs I've seen you can merge Groovy extension files with shadow, which is just what I wanted. The problem is that the Android plugin doesn't allow to use neither 'java' nor 'groovy' plugins, exactly the ones required by shadow.

Can I use a specific task directly instead of using the shadow plugin DSL ? 

Thanks
Mario

**Comment by aruis** [comment]
This plugin https://github.com/groovy/groovy-android-gradle-plugin maybe help you,try it.

**Comment by mariogarcia** [comment]
@aruis thanks, but the Android/Groovy plugins doesn't merge extension module descriptors, and Android complains about having more than one file with the same name in the same path when packaging the app.

Android has the "packagingOptions" and even in the latest beta version, there is a "merge" option. The problem is that it doesn't understand how to merge that type of files and eventually breaks them.

Anyway, I've implemented my own solution at https://github.com/kaleidos/emerger . I guess it would make sense to include that into the Groovy/Android plugin eventually.
