### ISSUE TITLE
The installShadowApp task does not copy files from src/main/dist

### ISSUE THREAD

**Issue by dskiles** [johnrengelman/shadow#150]
The installShadowApp task does not copy files from src/main/dist like the installApp and installDist tasks do.

Would it be possible to add this functionality?  In the meantime, is there a workaround?

**Comment by dskiles** [comment]
Current workaround:

//Override the distribution of the installShadowApp to include static files at runtime.
installShadowApp {
	distributions {
		contents {
			from 'src/main/dist'
		}
	}
}

**Comment by johnrengelman** [comment]
So I'm looking at this, and I believe you have the path wrong.
According to the Gradle docs (https://docs.gradle.org/current/userguide/application_plugin.html), only `src/dist` is copied into the output. Not `src/main/dist`.
