### ISSUE TITLE
Zip and tar files created in addition to shadow jar file

### ISSUE THREAD

**Issue by jeffbeard** [johnrengelman/shadow#153]
The combo of the application and shadow plugins apparently triggers the creation of both a zip and tar file. These unnecessary files are also uploaded to our Maven repository which means that we're creating a lot of unused data.

I can't figure out if there's configuration to disable the creation of the zip and tar files but it would be nice if there was.

**Comment by johnrengelman** [comment]
what is the task you are running from the Gradle command line?

**Comment by kurtseebauer** [comment]
it's the application-plugin that adds the zip and tar distribution targets when you run the task bootRepackage.

**Comment by jeffbeard** [comment]
@kurtseebauer 's answer is probably more technically accurate. We wire the 'shadowJar' task into the 'jar' task then we just run './gradlew build'

**Comment by johnrengelman** [comment]
Closing as this isn't an issue with Shadow

**Comment by patrickherrera** [comment]
For anyone else coming across this, you can try something like this to disable these tasks:
`tasks.whenTaskAdded { task ->
    if (Arrays.asList("shadowDistZip", "shadowDistTar", "distZip", "distTar").contains(task.name)) {
        task.enabled = false
    }
}`

Not ideal, but it works so far.

**Comment by elmagnoon** [comment]
Even though the issue is closed, the previous solutions didn't work for me. Currently using Gradle 8.0.1. The below worked.

```
tasks.distZip.setEnabled(false)
tasks.distTar.setEnabled(false)
tasks.shadowDistZip.setEnabled(false)
tasks.shadowDistTar.setEnabled(false)
```
