### ISSUE TITLE
startShadowScripts creates wrong path to jar-file

### ISSUE THREAD

**Issue by sputnik27** [johnrengelman/shadow#155]
Hello,

I use the shadow plugin in conjunction with the application plugin as described in the README. The beginning of my build.gradle is

```
plugins {
    id 'com.github.johnrengelman.shadow' version '1.2.2'
}

apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'application'
apply plugin: 'com.github.johnrengelman.shadow'
```

When I run `./gradlew clean startShadowScripts` and try to start the generated shell script, the following happens (my project's name really is 'shell')

```
$ ./build/scriptsShadow/shell                 
Error: Unable to access jarfile /home/USER/code/shell/build/lib/shell-1.1-SNAPSHOT-all.jar

```
The problem is that the jar is in a folder called `build/libs` (notice the 's'). Manually changing the path in the shell script fixes the problem. I don't know if this is a bug in shadow, but the current situation is not satisfying.

I use gradle 2.5, but also tried 2.4 and 2.2 with the same error.

Can someone verify this? Is it a bug in shadow, or in application?

**Comment by johnrengelman** [comment]
Actually, that's not how you are supposed to use the startScripts.

The start scripts are generated and intended to be bundled into an application distribution. The `build/scriptsShadow` directory is merely a staging direction for the file generation before it's bundled into a TAR or ZIP.

You should be running `gradle distShadowTar` or `gradle distShadowZip` to generate the distribution and then extracting that to your install directory.

You can read the Gradle manual regarding the behavior and uses of the Application plugin for more information - https://docs.gradle.org/current/userguide/application_plugin.html
