### ISSUE TITLE
mergeServiceFiles does not create new line

### ISSUE THREAD

**Issue by matteshe** [johnrengelman/shadow#156]
i use

```
shadowJar {
  mergeServiceFiles()
}
```

on of my jar file contains a service provider with NO new line at the end. Your function doesn't check if the merge is based on a new line. So as result i get LAST line of merge file A and FIRST line of merge file B at the same line.

**Comment by johnrengelman** [comment]
There is a test for this case that is checking this particular scenario: https://github.com/johnrengelman/shadow/blob/master/src/test/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformerSpec.groovy#L51

**Comment by johnrengelman** [comment]
Do you have a reproducible test case?
