### ISSUE TITLE
gradle build failing due to - org/objectweb/asm/Type

### ISSUE THREAD

**Issue by megha-sharma** [johnrengelman/shadow#157]
While trying to build a package it is giving exception:

:debian:shadowJar FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':debian:shadowJar'.
  > org/objectweb/asm/Type

**Comment by johnrengelman** [comment]
@meghaFlipkart can you provide the full stack trace by passing the `-s` switch to the Gradle command. Also which version of Shadow are you using and which version of Java?
