### ISSUE TITLE
Simplify shell script templates

### ISSUE THREAD

**Issue by mcandre** [johnrengelman/shadow#158]
The sh, bat scripts that the shadow plugin generates don't appear to work out of the box. Calling them results in errors about missing classes. As a result, I handwrite my sh and bat scripts:

https://github.com/mcandre/mcandre/tree/master/java/hello/bin

Instead of using complicated shell variable configuration, they just assume they're placed in a directory structure as cousins to the shadow jar. It works great for development, and OS packages can employ the same directory structure on installation, placing links from /usr/bin/<thing> to .../bin<thing> in Unix, or adding ...\bin to PATH in Windows.

What do you think about using these as templates for simpler, more reliable shadow-generated shell scripts?

**Comment by johnrengelman** [comment]
These templates are the same templates that are used by the Gradle core `application` plugin. If there is a specific issue with them, I'd like to know that and fix them while staying as close to the upstream templates as possible.
