### ISSUE TITLE
Is there a way to specify the output location?

### ISSUE THREAD

**Issue by millimeep** [johnrengelman/shadow#161]
Hi,

We recently updated from v0.8 to v1.2.2 and notice that the jar now appears in `build/libs` instead of `build/distributions`

Is there a way to specify the output directory in our build.gradle as some of our downstream jobs rely on the location?

Thanks

Iain

**Comment by millimeep** [comment]
Aha, we've found the answer, it would be handy to add this to the docs?
```groovy
shadowJar {
    transform(ServiceFileTransformer)
    baseName 'name'
    destinationDir = file('build/distributions')
}
```

**Comment by johnrengelman** [comment]
`ShadowJar` extends from `Jar` so you can reference teh Gradle docs for `Jar` for these configuration items.

**Comment by millimeep** [comment]
Yes, I'm still quite new to Gradle, so still learning lots!

Thanks!
