### ISSUE TITLE
Publish configuration docs on Gradle Plugins page

### ISSUE THREAD

**Issue by mcandre** [johnrengelman/shadow#162]
Please publish the configuration doc on Gradle Plugins, to make it easier for newbies to know how to configure the shadow plugin.

**Comment by johnrengelman** [comment]
AFAICT this isn't possibly at the moment (https://plugins.gradle.org/docs/publish-plugin#full-example)

**Comment by johnrengelman** [comment]
User Guide now available - http://imperceptiblethoughts.com/shadow/
