### ISSUE TITLE
How to configure shadow JAR name?

### ISSUE THREAD

**Issue by mcandre** [johnrengelman/shadow#164]
What's an example snippet that I can insert into my `build.gradle` in order to choose a custom name for the shadow JAR produced by this plugin?

**Comment by mcandre** [comment]
Ah, it's similar to how one would configure a regular jar task's name, but we need to customize the shadowJar task specifically, like so:

```
shadowJar.archiveName = 'bobby.jar'
```

**Comment by NabilCC** [comment]
For anyone viewing this issue in 2020 and using a newer version of Gradle, see: (https://imperceptiblethoughts.com/shadow/configuration/#configuring-output-name)
