### ISSUE TITLE
Is it possible to ship an 'application.properties' file located in the 'bin' directory?

### ISSUE THREAD

**Issue by christian-raedel** [johnrengelman/shadow#172]
Hi,

I wonder if it's possible to include custom files from the project sources/resources which should be copied to the _bin_ directory, next to the executable. This way I could ship a configuration file template to be edited by the app user and located in the current working directory of the app.

Regards,
Christian

**Comment by johnrengelman** [comment]
Not a shadow specific issue. You should be able to configure this with the distribution tasks.
