### ISSUE TITLE
Seamlessly replacing the default project jar?

### ISSUE THREAD

**Issue by levsa** [johnrengelman/shadow#174]
Is there a simple way to replace the default jar created by the java plugin? The maven shade plugin seems to rename the default artifact to "original-..." and replaces it with the new jar, which then becomes to default artifact from the project, so that other projects, publishing etc uses it automatically. With the current solution, one has to insert the shadowJar task in the default build task graph and also make sure that the artifact becomes the default.

**Comment by johnrengelman** [comment]
I personally don't recommend doing that. It breaks Gradle's ability to properly track the task UP-TO-DATE state (i.e. if you run `gradle jar` you'd get one output file and if you ran `gradle shadowJar` you'd get another).
Instead you should configure the downstream consumers to use the output of the `shadowJar` task.

That being said, you could configure the necessary attributes on the `shadowJar` task to simply write to the same output as the `jar` task.

**Comment by levsa** [comment]
I agree, closing this issue.
