### ISSUE TITLE
Is it possible to create two shadow jars in one project?

### ISSUE THREAD

**Issue by PeterMitrano** [johnrengelman/shadow#178]
I'm building two jars for two different platforms. I need the contents to vary slightly, but I'm not sure how to do that.

I tried putting two shadowJar tasks with different `baseName` but it didn't work. Is this possible? I might be trying to do the wrong thing with plugin...

**Comment by johnrengelman** [comment]
This plugin follows Gradle best practices wherein, it creates the `shadowJar` task and configures it based on conventions and the presence of other plugins in your project (i.e. the Java plugin).
You can create standalone `ShadowJar` tasks, but you'll need to fully configure them yourself (just like you would if you were adding a standalone `Jar` task).

The configuration that is applied to the standard task is here: https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy#L38-L63

So when adding a standalone `ShadowJar` task, you would need to add these same configurations to your build file.
