### ISSUE TITLE
Does not append file to jar.

### ISSUE THREAD

**Issue by chiken88** [johnrengelman/shadow#180]
```
shadowJar {
	append('NOTICE_TEST')
	manifest {
		attributes 'Main-Class': 'com.test.Main'
	}
}
```

After executing "shadowJar" file 'NOTICE_TEST' is not exists in jar file.

My project structure:
project/
    - src/
    - build.gradle
    - NOTICE_TEST

**Comment by johnrengelman** [comment]
The `append(String)` method is not for adding files to the Jar itself, it's an instruction that tells Shadow that during the merge process that the contents of any entries in the source JAR files with the provided name should be merged together into a single file in the output JAR.

What you are trying to do is add an additional file to sources for the underlying `CopySpec`. This would from the `from` commands - https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar:from(java.lang.Object[])
