### ISSUE TITLE
Possible to use shadowJar with com.android.library modules?

### ISSUE THREAD

**Issue by isuPatches** [johnrengelman/shadow#183]
I'm trying to use shadow jar with a library I created that has a sub-module and a few gradle based compile dependencies...I can see more shadowTasks if I switch to apply plugin: 'java' but I seem to not have them if I use 'com.android.application' or 'com.android.library'.  Is this supported? 

```
Shadow tasks
------------
knows - Do you know who knows?
```

Any help would be fantastic

**Comment by johnrengelman** [comment]
The plugin is convention based and only creates tasks when int he presence of the `java` plugin. 
If you aren't using the `java` plugin, then you'll need to configure your own `ShadowJar` task with the appropriate settings.

**Comment by ptyagi911** [comment]
@isuPatches Were you able to figure out how to achieve it ? Any example would be greatly appreciated !

**Comment by Tomislav-Tomsic** [comment]
Same problem brought me here, since I am writing this in 2018, and there are no examples, I have to conclude that shadow plugin can not solve that. Now, I have to hope that fat jar plugin, though not in maintenance anymore, can help one build a "fat jar" out of android app. 

If someone has an actual example (please, no childish it's in manual/documentation and so on, if there is a clear example of use anywhere in it, I wouldn't write this here), I, and many others I presume, would greatly appreciate it.

Thanks for your time

**Comment by isuPatches** [comment]
I did not spend the time to write my own custom ShadowJar task just for library modules.  I am sorry that I do not have an example to provide with everyone...it was not worth the effort (at least for me) if the library did not support it.  I ended up going another direction.

**Comment by mfuerstenau** [comment]
Late to the party. But here is my solution:
```groovy
buildscript {
   repositories {
      google ()
      jcenter ()
   }
   dependencies {
      classpath 'com.android.tools.build:gradle:3.2.1'
      classpath 'com.github.jengelman.gradle.plugins:shadow:4.0.2'
   }
}

// ...

apply plugin: "com.android.library"
apply plugin: 'com.github.johnrengelman.shadow' // because java plugin is missing there is no task defined

// ...

configurations {
   internalize // just define a separate configuration
}

/* a task to create the relocated libs, must be defined before used below in dependencies */
task internalizeJar (type: com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
   classifier = 'intern' // this is not needed but prevents conflicts with other artifacts you may want to create
   def pkg = 'com.squareup.tape2' // lib to relocate
   def shadowPrefix = 'our.package.name'
   relocate pkg, [shadowPrefix, pkg].join ('.') // we want to relocate the above package
   configurations = [project.configurations.internalize] // our configuration from above
}

dependencies {
   internalize 'com.squareup.tape2:tape:2.0.0-beta1' // this lib is a dependency of our separate configuration
   implementation tasks.internalizeJar.outputs.files // our real project uses the relocated jar as dependency
}
```

If you enable _ProGuard_, the dependency is merged into `classes.jar` for _release-.aar_. Don't worry about duplicate _injar_ entries in _Proguard_ output:
```
ProGuard, version 6.0.3
Reading input...
Reading program jar [SOMEPATH-SOMENAME-intern.jar] (filtered)
Reading program jar [SOMEPATH-SOMENAME-intern.jar] (filtered)
...
```
for some versions of _Android Gradle Plugin _ the _.jar_ is added twice to the _injars_. _Proguard_ will filter these.

Other soltution I came up with is a separate module with _Shadow_ and then using the output as dependency, but I like this better.

**Comment by nitheeshks91** [comment]
> @ptyagi911:
> 
> > @isuPatches Were you able to figure out how to achieve it ? Any example would be greatly appreciated !
> 
> Late to the party. But here is my solution (working with jar dependecies only, not aar):
> 
> ```groovy
> buildscript {
>    repositories {
>       google ()
>       jcenter ()
>    }
>    dependencies {
>       classpath 'com.android.tools.build:gradle:3.2.1'
>       classpath 'com.github.jengelman.gradle.plugins:shadow:4.0.2'
>    }
> }
> 
> // ...
> 
> apply plugin: "com.android.library"
> apply plugin: 'com.github.johnrengelman.shadow' // because java plugin is missing there is no task defined
> 
> // ...
> 
> configurations {
>    internalize // just define a separate configuration
> }
> 
> /* a task to create the relocated libs, must be defined before used below in dependencies */
> task internalizeJar (type: com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
>    classifier = 'intern' // this is not needed but prevents conflicts with other artifacts you may want to create
>    def pkg = 'com.squareup.tape2' // lib to relocate
>    def shadowPrefix = 'our.package.name'
>    relocate pkg, [shadowPrefix, pkg].join ('.') // we want to relocate the above package
>    configurations = [project.configurations.internalize] // our configuration from above
> }
> 
> dependencies {
>    internalize 'com.squareup.tape2:tape:2.0.0-beta1' // this lib is a dependency of our separate configuration
>    implementation tasks.internalizeJar.outputs.files // our real project uses the relocated jar as dependency
> }
> ```
> 
> If you enable _ProGuard_, the dependency is merged into `classes.jar` for _release-.aar_. Don't worry about duplicate _injar_ entries in _Proguard_ output:
> 
> ```
> ProGuard, version 6.0.3
> Reading input...
> Reading program jar [SOMEPATH-SOMENAME-intern.jar] (filtered)
> Reading program jar [SOMEPATH-SOMENAME-intern.jar] (filtered)
> ...
> ```
> for some versions of _Android Gradle Plugin _ the _.jar_ is added twice to the _injars_. _Proguard_ will filter these.
> 
> Other soltution I came up with is a separate module with _Shadow_ and then using the output as dependency, but I like this better.

Could not get unknown property 'runtime' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer

**Comment by roffel** [comment]
> > @ptyagi911:
> > > @isuPatches Were you able to figure out how to achieve it ? Any example would be greatly appreciated !
> > 
> > 
> > Late to the party. But here is my solution (working with jar dependecies only, not aar):
> > ```groovy
> > buildscript {
> >    repositories {
> >       google ()
> >       jcenter ()
> >    }
> >    dependencies {
> >       classpath 'com.android.tools.build:gradle:3.2.1'
> >       classpath 'com.github.jengelman.gradle.plugins:shadow:4.0.2'
> >    }
> > }
> > 
> > // ...
> > 
> > apply plugin: "com.android.library"
> > apply plugin: 'com.github.johnrengelman.shadow' // because java plugin is missing there is no task defined
> > 
> > // ...
> > 
> > configurations {
> >    internalize // just define a separate configuration
> > }
> > 
> > /* a task to create the relocated libs, must be defined before used below in dependencies */
> > task internalizeJar (type: com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
> >    classifier = 'intern' // this is not needed but prevents conflicts with other artifacts you may want to create
> >    def pkg = 'com.squareup.tape2' // lib to relocate
> >    def shadowPrefix = 'our.package.name'
> >    relocate pkg, [shadowPrefix, pkg].join ('.') // we want to relocate the above package
> >    configurations = [project.configurations.internalize] // our configuration from above
> > }
> > 
> > dependencies {
> >    internalize 'com.squareup.tape2:tape:2.0.0-beta1' // this lib is a dependency of our separate configuration
> >    implementation tasks.internalizeJar.outputs.files // our real project uses the relocated jar as dependency
> > }
> > ```
> > 
> > 
> > If you enable _ProGuard_, the dependency is merged into `classes.jar` for _release-.aar_. Don't worry about duplicate _injar_ entries in _Proguard_ output:
> > ```
> > ProGuard, version 6.0.3
> > Reading input...
> > Reading program jar [SOMEPATH-SOMENAME-intern.jar] (filtered)
> > Reading program jar [SOMEPATH-SOMENAME-intern.jar] (filtered)
> > ...
> > ```
> > 
> > 
> > for some versions of _Android Gradle Plugin _ the _.jar_ is added twice to the _injars_. _Proguard_ will filter these.
> > Other soltution I came up with is a separate module with _Shadow_ and then using the output as dependency, but I like this better.
> 
> Could not get unknown property 'runtime' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer

Did you manage to solve this issue?

**Comment by darylsze** [comment]
may i know how to install this plugin cuz i always receive this error `Connection refused (Connection refused)`

**Comment by darylsze** [comment]
> > > @ptyagi911:
> > > > @isuPatches Were you able to figure out how to achieve it ? Any example would be greatly appreciated !
> > > 
> > > 
> > > Late to the party. But here is my solution (working with jar dependecies only, not aar):
> > > ```groovy
> > > buildscript {
> > >    repositories {
> > >       google ()
> > >       jcenter ()
> > >    }
> > >    dependencies {
> > >       classpath 'com.android.tools.build:gradle:3.2.1'
> > >       classpath 'com.github.jengelman.gradle.plugins:shadow:4.0.2'
> > >    }
> > > }
> > > 
> > > // ...
> > > 
> > > apply plugin: "com.android.library"
> > > apply plugin: 'com.github.johnrengelman.shadow' // because java plugin is missing there is no task defined
> > > 
> > > // ...
> > > 
> > > configurations {
> > >    internalize // just define a separate configuration
> > > }
> > > 
> > > /* a task to create the relocated libs, must be defined before used below in dependencies */
> > > task internalizeJar (type: com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
> > >    classifier = 'intern' // this is not needed but prevents conflicts with other artifacts you may want to create
> > >    def pkg = 'com.squareup.tape2' // lib to relocate
> > >    def shadowPrefix = 'our.package.name'
> > >    relocate pkg, [shadowPrefix, pkg].join ('.') // we want to relocate the above package
> > >    configurations = [project.configurations.internalize] // our configuration from above
> > > }
> > > 
> > > dependencies {
> > >    internalize 'com.squareup.tape2:tape:2.0.0-beta1' // this lib is a dependency of our separate configuration
> > >    implementation tasks.internalizeJar.outputs.files // our real project uses the relocated jar as dependency
> > > }
> > > ```
> > > 
> > > 
> > > If you enable _ProGuard_, the dependency is merged into `classes.jar` for _release-.aar_. Don't worry about duplicate _injar_ entries in _Proguard_ output:
> > > ```
> > > ProGuard, version 6.0.3
> > > Reading input...
> > > Reading program jar [SOMEPATH-SOMENAME-intern.jar] (filtered)
> > > Reading program jar [SOMEPATH-SOMENAME-intern.jar] (filtered)
> > > ...
> > > ```
> > > 
> > > 
> > > for some versions of _Android Gradle Plugin _ the _.jar_ is added twice to the _injars_. _Proguard_ will filter these.
> > > Other soltution I came up with is a separate module with _Shadow_ and then using the output as dependency, but I like this better.
> > 
> > 
> > Could not get unknown property 'runtime' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer
> 
> Did you manage to solve this issue?

upgrade to         classpath 'com.github.jengelman.gradle.plugins:shadow:5.1.0'
solve it.

**Comment by darylsze** [comment]
> > @ptyagi911:
> > > @isuPatches Were you able to figure out how to achieve it ? Any example would be greatly appreciated !
> > 
> > 
> > Late to the party. But here is my solution (working with jar dependecies only, not aar):
> > ```groovy
> > buildscript {
> >    repositories {
> >       google ()
> >       jcenter ()
> >    }
> >    dependencies {
> >       classpath 'com.android.tools.build:gradle:3.2.1'
> >       classpath 'com.github.jengelman.gradle.plugins:shadow:4.0.2'
> >    }
> > }
> > 
> > // ...
> > 
> > apply plugin: "com.android.library"
> > apply plugin: 'com.github.johnrengelman.shadow' // because java plugin is missing there is no task defined
> > 
> > // ...
> > 
> > configurations {
> >    internalize // just define a separate configuration
> > }
> > 
> > /* a task to create the relocated libs, must be defined before used below in dependencies */
> > task internalizeJar (type: com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
> >    classifier = 'intern' // this is not needed but prevents conflicts with other artifacts you may want to create
> >    def pkg = 'com.squareup.tape2' // lib to relocate
> >    def shadowPrefix = 'our.package.name'
> >    relocate pkg, [shadowPrefix, pkg].join ('.') // we want to relocate the above package
> >    configurations = [project.configurations.internalize] // our configuration from above
> > }
> > 
> > dependencies {
> >    internalize 'com.squareup.tape2:tape:2.0.0-beta1' // this lib is a dependency of our separate configuration
> >    implementation tasks.internalizeJar.outputs.files // our real project uses the relocated jar as dependency
> > }
> > ```
> > 
> > 
> > If you enable _ProGuard_, the dependency is merged into `classes.jar` for _release-.aar_. Don't worry about duplicate _injar_ entries in _Proguard_ output:
> > ```
> > ProGuard, version 6.0.3
> > Reading input...
> > Reading program jar [SOMEPATH-SOMENAME-intern.jar] (filtered)
> > Reading program jar [SOMEPATH-SOMENAME-intern.jar] (filtered)
> > ...
> > ```
> > 
> > 
> > for some versions of _Android Gradle Plugin _ the _.jar_ is added twice to the _injars_. _Proguard_ will filter these.
> > Other soltution I came up with is a separate module with _Shadow_ and then using the output as dependency, but I like this better.
> 
> Could not get unknown property 'runtime' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer

upgrade to classpath 'com.github.jengelman.gradle.plugins:shadow:5.1.0'
solve it.

**Comment by realchandan** [comment]
I am being bombarded with Duplicate class errors, my library depends on other dependencies. and pretty much all of them are found as duplicates! are there any updates since it's now version 7.0.0 regarding android?

**Comment by xiaochao00** [comment]
> ```groovy
> com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
> ```

hi leader, how to solve error "Could not find method internalize() "?

**Comment by miguel-level** [comment]
When I tried it it wasn't rewriting the android library's source files with the new package name.

**Comment by devinmorgan** [comment]
> Same problem brought me here, since I am writing this in 2018, and there are no examples, I have to conclude that shadow plugin can not solve that. Now, I have to hope that fat jar plugin, though not in maintenance anymore, can help one build a "fat jar" out of android app.
> 
> If someone has an actual example (please, no childish it's in manual/documentation and so on, if there is a clear example of use anywhere in it, I wouldn't write this here), I, and many others I presume, would greatly appreciate it.
> 
> Thanks for your time

Hey all! Here is the link to [a Github repo](https://github.com/devinmorgan/shadow-plugin-for-aar) with a working example of a custom Gradle Plugin that I made that uses the Shadow Plugin to relocate AAR (android libraries) to an arbitrary namespace. When I have more time, I will:
- [] add a readme
- [] make the grade plugin able to support more than just a single AAR
- [] figure out a way to not have to hard-code the peer dependencies (ideally these are passed to `implementation` under the hood)

Hope this helps the next person coming through!

**Comment by devinmorgan** [comment]
@kostadin-damyanov-prime - roger that! I'll have time to add documentation this evening and will report back. Glad that it may end up being helpful to someone other than me!!

**Comment by devinmorgan** [comment]
Hey there @kostadin-damyanov-prime! Thanks for your patience. I had the time to revise [the Gradle plugin repo](https://github.com/devinmorgan/shadow-plugin-for-aar) from earlier. Notable updates include:
- [x] I added a short but (hopefully) sweet `README.md` to explain what it is and how to use it
- [x] The plugin now supports multiple AAR artifacts for relocation by creating a new Gradle configuration
- [x] You no longer need to hard-code transitive dependencies of the AAR artifacts you're looking to do namespace relocation on

Regarding your note:
> Edit: can it be used to move obfuscated (a.a, a.b, a.c ...) classes from the root of the package to a dedicated namespace?
This is needed when we do not have control over the way the AAR file is produced - coming from a third party.
If we set the targetPackageName parameter to an empty string will it do it?

Can you elaborate and/or let me know if the `README.md` plus other updates I added speak to this point here? I want to make sure I understand exactly what your concern is so I can speak intelligently about it

**Comment by devinmorgan** [comment]
@Tomislav-Tomsic forgot to mention you in my last response. love to know if the repo I linked is a useful legitimate example from your point of view. Any feedback is much appreciated!
