### ISSUE TITLE
Incompatibility with Gradle 2.11

### ISSUE THREAD

**Issue by danielfernandez** [johnrengelman/shadow#185]
The current constructor of `DefaultInheritManifest` looks like:

```java
DefaultInheritManifest(FileResolver fileResolver) {
    this.internalManifest = new DefaultManifest(fileResolver)
    this.fileResolver = fileResolver
}
```

But apparently in Gradle 2.11 the `DefaultManifest(FileResolver)` constructor has disappeared, having been replaced by a `DefaultManifest(PathToFileResolver)`.

See https://github.com/gradle/gradle/blob/69cabb777bcd69627a36eedf5ae7cfb68b19cc26/subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/internal/DefaultManifest.java#L44-L47

This provokes the ShadowJar plugin to throw a `NoSuchMethodError` when being executed using version 2.11 of Gradle :(

**Comment by danhyun** [comment]
This is fixed in 1.2.3 #177
