### ISSUE TITLE
Strings containing same package name as relocate are also relocated

### ISSUE THREAD

**Issue by rpmoore** [johnrengelman/shadow#190]
I'm building a shadow jar with the slf4j-api jar included in it.  When slf4j-api starts up it looks for the class `org/slf4j/impl/StaticLoggerBinder.class`  However, after the jar is built, the string has been re-written to my relocated path, so for instance `fatjar/org/slf4j/impl/StaticLoggerBinder.class`.  This is not what I was expecting.  It actually breaks slf4j-api so that none of the bindings for it will work since `org/slf4j/impl/StaticLoggerBinder.class` is defined in the slf4j bindings, and not actually in the api jar.

Is there a way to disable this?  Or if not disable, can a feature be added to disable re-writing of strings inside of the jars.

**Comment by johnrengelman** [comment]
The string is used to locate a class in the classloader, so why not also relocate the bindings?
I'm failing to see why you would relocate the api packages but not the binding classes themselves.

But to answer your specific question, no, there is no find tuning for this. You either relocate a class and references to it or not.

**Comment by rpmoore** [comment]
The issue is that the library I'm producing is for use by other users who may use their own bindings.

**Comment by johnrengelman** [comment]
then why relocate the `slf4j-api` dependency? If they can pick their own binding, then you'd have conflicts anyway (i.e. when I include the binding library, it will be loaded by both your relocated api and any non0-relocated api libs that the user has pulled in).

**Comment by rpmoore** [comment]
Hmmm.  I see what you mean.  I'll look into trying to solve this a different way.  Most likely I'll have to introduce my own logging abstraction.  I think this pointed me in the write direction.  Thanks!
