### ISSUE TITLE
Use resulted jar as project result

### ISSUE THREAD

**Issue by paulvi** [johnrengelman/shadow#194]
This question may be because of my not perfect understanding how gradle works.
I have multi-module project #193, and one of the modules, say `:base.base`, uses this shadow plugin.

Can I make gradle and be sure about this when use later 

```gradle
dependencies {
	compile project(':base.base')
	//no lib
}
```

that the next project will get results as resulted shadow jar?

**Comment by johnrengelman** [comment]
See section 24.7 (https://docs.gradle.org/current/userguide/multi_project_builds.html)

**Comment by paulvi** [comment]
Great, so I have to try new configuration as in

# 24.7. Project lib dependencies

Example 24.24. Project lib dependencies

```gradle
subprojects {
    apply plugin: 'java'
    group = 'org.gradle.sample'
    version = '1.0'
}

project(':api') {
    configurations {
        spi
    }
    dependencies {
        compile project(':shared')
    }
    task spiJar(type: Jar) {
        baseName = 'api-spi'
        dependsOn classes
        from sourceSets.main.output
        include('org/gradle/sample/api/**')
    }
    artifacts {
        spi spiJar
    }
}

project(':services:personService') {
    dependencies {
        compile project(':shared')
        compile project(path: ':api', configuration: 'spi')
        testCompile "junit:junit:4.12", project(':api')
    }
}
```

**Comment by johnrengelman** [comment]
User Guide now available - http://imperceptiblethoughts.com/shadow/
