### ISSUE TITLE
Zip resources are exploded into output Jar

### ISSUE THREAD

**Issue by RishikeshDarandale** [johnrengelman/shadow#196]
If src.main.resources.mydir folder has sample.zip, then shadowJar skips these file while creating the FatJar.

**Comment by johnrengelman** [comment]
Correct. This would be the expected behavior. Shadow is only for merging applications dependencies. a Jar file in `src/main/resources` is not an application dependency...it would be treated the same as a Javascript or CSS file.

If you want a local dependency, then you should be adding the jar as a File Dependency per https://docs.gradle.org/current/userguide/dependency_management.html#sub:file_dependencies

**Comment by RishikeshDarandale** [comment]
Zip file added in resources is not dependency, its resource file which gets used in the application.

I do not have any local dependencies.

**Comment by RishikeshDarandale** [comment]
Jar task does not skip these and includes on the jar file.

**Comment by johnrengelman** [comment]
Sorry, I originally misread your question.
So you are saying that a Jar file in `src/main/resources` is not included in the shadow jar as a single file, correct?

Is the getting exploded into its contents?

**Comment by RishikeshDarandale** [comment]
Not really. I have a resource file in format of zip, take an example of postal code. This file present under ```src/main/resources/postalCodes/US.zip```; if you execute the jar task, then this resource file gets included in final jar file.

The same doesn't happen with shadowJar. Please refer [shadow-example](https://github.com/RishikeshDarandale/gradle-examples/tree/master/shadow-example) for further details.
```
gradle clean build run
```
Here is the details:
```
rdarand$ jar -tvf ./shadow-example/build/libs/shadow-example.jar 
     0 Wed Mar 23 14:05:46 IST 2016 META-INF/
    25 Wed Mar 23 14:05:46 IST 2016 META-INF/MANIFEST.MF
     0 Wed Mar 23 14:05:46 IST 2016 sample/
   536 Wed Mar 23 14:05:46 IST 2016 sample/Sample.class
     0 Wed Mar 23 14:05:46 IST 2016 io/
     0 Wed Mar 23 14:05:46 IST 2016 io/rishikeshdarandale/
     0 Wed Mar 23 14:05:46 IST 2016 io/rishikeshdarandale/gradle/
  1944 Wed Mar 23 14:05:46 IST 2016 io/rishikeshdarandale/gradle/Example.class
     0 Wed Mar 23 14:05:46 IST 2016 postalCodes/
650958 Wed Mar 23 14:05:46 IST 2016 postalCodes/US.zip

rdarand$ jar -tvf ./shadow-example/build/libs/shadow-example-all.jar
     0 Wed Mar 23 14:05:50 IST 2016 META-INF/
    75 Wed Mar 23 14:05:52 IST 2016 META-INF/MANIFEST.MF
     0 Wed Mar 23 14:05:46 IST 2016 sample/
   536 Wed Mar 23 14:05:46 IST 2016 sample/Sample.class
     0 Wed Mar 23 14:05:46 IST 2016 io/
     0 Wed Mar 23 14:05:46 IST 2016 io/rishikeshdarandale/
     0 Wed Mar 23 14:05:46 IST 2016 io/rishikeshdarandale/gradle/
  1944 Wed Mar 23 14:05:46 IST 2016 io/rishikeshdarandale/gradle/Example.class
     0 Wed Mar 23 14:05:46 IST 2016 postalCodes/
  2372 Wed Mar 23 14:05:52 IST 2016 readme.txt
2779415 Wed Mar 23 14:05:52 IST 2016 US.txt
     0 Wed Mar 23 14:05:52 IST 2016 META-INF/maven/
     0 Wed Mar 23 14:05:52 IST 2016 META-INF/maven/com.google.guava/
     0 Wed Mar 23 14:05:52 IST 2016 META-INF/maven/com.google.guava/guava/
   129 Wed Mar 23 14:05:52 IST 2016 META-INF/maven/com.google.guava/guava/pom.properties
  6792 Wed Mar 23 14:05:52 IST 2016 META-INF/maven/com.google.guava/guava/pom.xml
...
```

**Comment by johnrengelman** [comment]
Yeah, it's treating. The JAR as a dependency and exploding its contents. Your shadow jar has a US.txt file in the root of the jar. That's the contents from the US.zip file.

**Comment by RishikeshDarandale** [comment]
Okay. what would be the workaround?

**Comment by johnrengelman** [comment]
The only workaround at the moment would be to include the zip file contents in your project instead of the zip file and referencing them that way.

**Comment by RishikeshDarandale** [comment]
For workaround, just change the extension from .zip to .zipx and it works!

**Comment by Lanchon** [comment]
hi,

FYI, for the longest time i've been double-zipping my resources to stop shadow 1.3 from exploding my jars:
https://github.com/DexPatcher/dexpatcher-tool/blob/v1.2.0/tool/build.gradle#L67-L86

i'll try 1.4 at some point and report whether this has been fixed.

thanks!

**Comment by johnrengelman** [comment]
@Lanchon this is fixed in shadow 1.2.4

**Comment by Lanchon** [comment]
oh, awful mind trickery converted my used version from 1.2.3 to 1.3, sorry!
ok i'll test it when i can, thank you!

**Comment by Lanchon** [comment]
it doesn't seem to be fixed.

when replacing 1.2.3 for 1.2.4 i expected a single ["dexpatcher-annotation-nested" jar](https://github.com/DexPatcher/dexpatcher-tool/blob/v1.2.0/tool/build.gradle#L70) to be included in the shadow jar, but no change: the contents of that jar are included in the shadow instead.

**Comment by johnrengelman** [comment]
Correct because this issue is for zip files not jars. Embedding a jar file into the shadow jar is not supported. There isn't a way for shadow at the moment to determine your intent here because the dependencies are jars too.

**Comment by johnrengelman** [comment]
See the referenced #111 for what you are tying to do.
