### ISSUE TITLE
Conflict when using together with spring-boot-gradle-plugin

### ISSUE THREAD

**Issue by paulvi** [johnrengelman/shadow#199]
in https://github.com/szjug/monolith project

	D:\Workspaces\GitHub\monolith>gradle :shadow:shadowJar
	                                                                                                                       
	FAILURE: Build failed with an exception.
	                            
	* What went wrong:          
	Could not resolve all dependencies for configuration ':shadow:runtime'.
	> Could not find org.springframework.boot:spring-boot-starter-data-mongodb:.
	  Searched in the following locations:
	      https://jcenter.bintray.com/org/springframework/boot/spring-boot-starter-data-mongodb//spring-boot-starter-data-mongodb-.pom
	      https://jcenter.bintray.com/org/springframework/boot/spring-boot-starter-data-mongodb//spring-boot-starter-data-mongodb-.jar
	  Required by:              
	      monolith:shadow:1.0 > monolith:io.github.szjug.greeting:1.0
	      monolith:shadow:1.0 > monolith:io.github.szjug.who:1.0
	> Could not find org.springframework.boot:spring-boot-starter-web:.
	  Searched in the following locations:
	      https://jcenter.bintray.com/org/springframework/boot/spring-boot-starter-web//spring-boot-starter-web-.pom
	      https://jcenter.bintray.com/org/springframework/boot/spring-boot-starter-web//spring-boot-starter-web-.jar
	  Required by:              
	      monolith:shadow:1.0 > monolith:io.github.szjug.greeting:1.0
	      monolith:shadow:1.0 > monolith:io.github.szjug.who:1.0
	                            
	* Try:                      
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
	                            
	BUILD FAILED                
	                            
	Total time: 10.006 secs

**Comment by johnrengelman** [comment]
This is not a Shadow problem. You have something niacin figures with the Spring Boot plugin. Looking at the output you posted there is no version for the spring boot dependencies that it is trying to to resolve.

**Comment by paulvi** [comment]
yes, exactly.

Raise at https://github.com/spring-projects/spring-boot/tree/master/spring-boot-tools/spring-boot-gradle-plugin as well
