### ISSUE TITLE
Rsync-friendly JAR

### ISSUE THREAD

**Issue by MartyIX** [johnrengelman/shadow#200]
Hi,

can I make the resulting `.jar` file rsync-friendly? I mean the same thing as `gzip --rsyncable`:

>        --rsyncable
>               While  compressing, synchronize the output occasionally based on
>               the input.  This increases size by  less  than  1  percent  most
>               cases,  but  means that the rsync(1) program can much more effi‐
>               ciently synchronize files compressed  with  this  flag.   gunzip
>               cannot  tell  the  difference  between a compressed file created
>               with this option, and one created without it.
(http://linuxcommand.org/lc3_man_pages/gzip1.html)

Thank you,
Martin

**Comment by johnrengelman** [comment]
Never heard of this. This project uses the standard Java APIs for creating a JAR output.
