### ISSUE TITLE
Custom ShadowJar task in subprojects does not regard inclusion of any depenencies

### ISSUE THREAD

**Issue by liach** [johnrengelman/shadow#202]
Shadow Version: 1.2.3

Before:
https://github.com/liachmodded/UHC-Reloaded/blob/1ed0ee8a1c5c20eed805e3b3888e541815963971/sponge/build.gradle

After:
https://github.com/liachmodded/UHC-Reloaded/blob/7b36888b18fe3967d561b6f93b3876b85dac4aa9/sponge/build.gradle

In the custom task called `pluginJar` in the case above, the shadowJar does not handle the dependencies correcly. Before, it neither regards classifiers, nor statements like `dependencies.include(dependency('somegroup:someartifact:someversion'))`.
When I switch to use `shadowJar` extension, `dependencies.include(dependency('somegroup:someartifact:someversion'))` works, and I also assume that the usage of classifiers will work. Could you help find out the issue?

**This issue only observed in modular projects, and only in subprojects. Custom `ShadowJar` task in a single project works.**

**Comment by johnrengelman** [comment]
In your first example you want:
` configurations = [configuration.runtime]`

That's the default for the `shadowJar` task.
If you want to see how the default task is configured, the code is here: https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy#L38-L63

**Comment by liach** [comment]
This time I bring up the 3rd example:
https://github.com/liachmodded/UHC-Reloaded/blob/289ca76f7b3ad4232d07f20d3b1e20a4d932ec68/sponge/build.gradle

![image](https://cloud.githubusercontent.com/assets/7806504/14450319/2541e63e-0032-11e6-9a59-b5b08c2ffeeb.png)

As shown in this picture the `-all` jar which is the shadowjar still does not include the one with custom configuration `ship`.

**Comment by liach** [comment]
![image](https://cloud.githubusercontent.com/assets/7806504/14479472/d02f323a-00d3-11e6-8195-fac1db061415.png)

The version for comparision:
https://github.com/liachmodded/UHC-Reloaded/blob/53fb4dbd0616c740c0a40ccb498acf3df4be6fd5/sponge/build.gradle

The `pluginJar` and `shadowJar` generally has the same configuration. But the output differs as shown in the screenshot above, which `shadowJar` is bigger with the dependency shipped.

**Comment by asandroq** [comment]
I see something similar in a multiproject build. A subproject depends on another for the `testRuntime` configuration. When I use `configurations = [project.configurations.testRuntime]` the output of that project is not included.

**Comment by liach** [comment]
Note even the one below does not work.
```gradle
task xxx(type: ShadowJar) {
    dependencies {
        include(dependency("somedep"))
    }
}
```

**Comment by liach** [comment]
@johnrengelman Any updates?

**Comment by johnrengelman** [comment]
can you output the content table of the Jars and compare them? That will tells use what files are missing in the `-plugin` output compared to the `-all`

**Comment by liach** [comment]
![image](https://cloud.githubusercontent.com/assets/7806504/14758281/efe67ffc-08b2-11e6-9d36-2f0f9dc4e0d0.png)
![image](https://cloud.githubusercontent.com/assets/7806504/14758290/4d970ce8-08b3-11e6-96d5-61e4db4e80e8.png)

Note I removed `-all` classifier.

**Comment by johnrengelman** [comment]
change this line (https://github.com/liachmodded/UHC-Reloaded/blob/53fb4dbd0616c740c0a40ccb498acf3df4be6fd5/sponge/build.gradle#L45) to read `configurations = [ project.configurations.ship ]`
and test again.

**Comment by liach** [comment]
I've already fixed that typo. Yet the next commit on master fixed this, but it still does not work as intended

**Comment by johnrengelman** [comment]
I'm looking at the latest commit on master right now and that line is wrong (https://github.com/liachmodded/UHC-Reloaded/blob/53fb4dbd0616c740c0a40ccb498acf3df4be6fd5/sponge/build.gradle#L45)

you have to explicitly call `project.configurations` when setting the `configurations` block because of delegate resolution in Groovy.

**Comment by liach** [comment]
See https://github.com/liachmodded/UHC-Reloaded/tree/347c01a76ec9bbcbfddb3ceda058608306e63049

Yes you are right, the `configurations` worked, but
```gradle
dependencies {
    include(dependency('net.minecrell.mcstats:statslite-sponge:0.2.2'))
}
```
doesn't. Could you help?

**Comment by farrukhnajmi** [comment]
I am running to what seems is this same issue in a multproject build.

```
plugins {
    id 'com.github.johnrengelman.shadow' version '4.0.3'
    id 'java'
    id 'groovy'
}

dependencies {
    implementation project(':my-client')
}
...
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

task testJar(type: ShadowJar) {
    classifier = 'tests'
    from sourceSets.test.output
    configurations = [project.configurations.testRuntime]
}
```

My project-tests-version.jar only contains the classes for the tests but none for dependency `implementation project(':my-client')`

What am I doing wrong?
