### ISSUE TITLE
Is ZipEntryCompression.STORED supported?

### ISSUE THREAD

**Issue by MartyIX** [johnrengelman/shadow#203]
Hi, 

I use Shadow plugin 1.2.3 and I tried the following configuration:

```
    shadowJar {
        zip64 true
        entryCompression = org.gradle.api.tasks.bundling.ZipEntryCompression.STORED
        exclude 'META-INF/*.RSA', 'META-INF/*.SF','META-INF/*.DSA'
        manifest {
            attributes 'Main-Class': 'com.MyProject.Main'
        }
    }
```

However, an exception was thrown:

```
Caused by: java.util.zip.ZipException: uncompressed size is required for STORED method when not writing to a file
        at org.apache.tools.zip.ZipOutputStream.validateSizeInformation(ZipOutputStream.java:699)
        at org.apache.tools.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:648)
        at org.apache.tools.zip.ZipOutputStream$putNextEntry$1.call(Unknown Source)
        at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$StreamAction.visitDir(ShadowCopyAction.groovy:305)
        ... 129 more
:App:shadowJar FAILED
```

Is `ZipEntryCompression.STORED` supported?
Thanks

**Comment by johnrengelman** [comment]
What version of Gradle?

**Comment by MartyIX** [comment]
2.12

**Comment by saurfang** [comment]
@MartyIX were you able to solve the problem you mentioned in this thread? If so, can you share how you did it?

**Comment by MartyIX** [comment]
@saurfang I ended up using simply http://stackoverflow.com/questions/4871656/using-gradle-to-build-a-jar-with-dependencies It works better for me.

**Comment by johnrengelman** [comment]
^ that solution will be orders of magnitude slower than shadow since it will decompress each JAR to disk before then creating a new JAR.

**Comment by MartyIX** [comment]
Just a note: My project is at most "medium sized" so it is a sufficient solution for me at the moment. Build time is up to 10 seconds. Obviously the faster, the better.. :+1:

**Comment by saurfang** [comment]
Okay I also ended up using the workaround for now. It would be nice if shadow plugin can support this instead. JAR produced this way is rsync friendly (#229)

**Comment by johnrengelman** [comment]
Looks like this broke because of this change https://github.com/johnrengelman/shadow/pull/171
I'm reverting that change and have added a spec to test this.

**Comment by saurfang** [comment]
Thanks a lot! Any chance you will publish a new version soon?

**Comment by johnrengelman** [comment]
There should be a 2.0.0-SNAPSHOT available for testing, I'm still working to finalize that build. Note that if you want to try it, you'll have to be running Gradle 3.0 or higher.

**Comment by digvijay7** [comment]
Hey! Any update on when this will get released?
