### ISSUE TITLE
"Failed to notify dependency resolution listener. > GC overhead limit exceeded" when running "gradle shadowJar" on a large project with imported BOM file

### ISSUE THREAD

**Issue by alexeyOnGitHub** [johnrengelman/shadow#204]
Gradle 2.12
com.github.johnrengelman.shadow 1.2.3
Windows 7 64bit
JDK 1.8 64bit

the build downloads a bunch of jars and poms and then fails with 

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Failed to notify dependency resolution listener.
> > GC overhead limit exceeded
> 

I see the java process has 98% CPU and 4.5Gb "working set" memory shown in Windows Task Manager right before the crash.

don't know if that's important, but the project uses Maven-style BOM file via Spring's "dependency-management-plugin" plugin:

```
dependencyManagement {
  imports {
    mavenBom 'companygroup:companyartifact:1.xxxxx-SNAPSHOT'
  }
}



buildscript {
    // for Maven BOM import
    repositories {
        jcenter()
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:0.5.6.RELEASE"
    }

    // for building self-contained jar
    repositories {
        maven {
            name 'Shadow'
            url 'https://plugins.gradle.org/m2/'
        }
    }
    dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:1.2.3'
    }
}


```

I ran the same command with debug info enabled. I see io.spring.dependency-management going into seemingly endless loops:

> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-sca-api
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                         org.apache.tuscany.sca:tuscany-interface-wsdl
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                             org.apache.tuscany.sca:tuscany-xsd
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-assembly
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-monitor
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.ws.commons.schema:XmlSchema
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-contribution
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-assembly
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                         org.apache.tuscany.sca:tuscany-monitor
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                         org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-assembly-xsd
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-common-xml
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                         org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-common-java
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                         org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                         org.apache.tuscany.sca:tuscany-sca-api
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                             org.apache.tuscany.sca:tuscany-contribution
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-assembly
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-monitor
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-assembly-xsd
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-common-xml
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-common-java
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-sca-api
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                             org.apache.ws.commons.schema:XmlSchema
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                             wsdl4j:wsdl4j
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                             org.apache.tuscany.sca:tuscany-assembly-xml
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-assembly
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-monitor
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-contribution
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-assembly
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                         org.apache.tuscany.sca:tuscany-monitor
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                         org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-assembly-xsd
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-common-xml
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                         org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-common-java
> 

maybe that's a problem in io.spring.dependency-management and some circular dependencies in the project...

**Comment by wilkinsona** [comment]
@johnrengelman FYI, this issue has also been opened here: https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/79. FWIW, I'd close this issue. The problem is almost certainly with the dependency management plugin and not this plugin.

@alexeyOnGitHub If you really must open the same issue against multiple projects, please make it clear that you have done so. If you don't, it's likely that people will waste time diagnosing the same problem.

**Comment by alexeyOnGitHub** [comment]
you are totally right, I was going to remove the shadow plugin from the build and isolate the problem today, then update one or both issues.
I was sure nobody would look at these issues for a while, so I didn't do that yesterday. sorry!
