### ISSUE TITLE
Some jars not packaged when jar artifact is missing from maven local but pom is not.

### ISSUE THREAD

**Issue by itissid** [johnrengelman/shadow#205]
Hi I have raised an issue https://discuss.gradle.org/t/missing-jar-in-maven-local-ignored-from-build/16701 with some reproduction steps https://github.com/itissid/gradle_shadow_jar_issue. I am not sure if this is the shadow jar plugin issue. Let me know what you think.

**Comment by johnrengelman** [comment]
The plugin relies on Gradle's dependency resolution mechanism. It doesn't do any resolving on its own. So this isn't a problem with the plugin.
