### ISSUE TITLE
How to merge Log4j2Plugins.dat?

### ISSUE THREAD

**Issue by PatrickHuetter** [johnrengelman/shadow#207]
Regarding to this issue https://issues.apache.org/jira/browse/LOG4J2-954 i would like to know how to merge/concat the **Log4j2Plugins.dat** with shadowJar?

I already tested some configuration patterns but they didn't work.
For maven users there is a workaround like this https://github.com/edwgiz/maven-shaded-log4j-transformer but i could figure out how to get similar working with gradle.

Best regards

**Comment by PatrickHuetter** [comment]
Using a custom jar task without shadowJar and downgrading log4j2 dependencies to 2.0.2 seems to work partly:
```
jar {
    doFirst {
        from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
    }

    // This is optional, needed if you have signature problems while starting your created jar.
    // This often happens while including foreign depdendencies wich are signed.
    exclude 'META-INF/*.RSA', 'META-INF/*.SF','META-INF/*.DSA'

    // change to your main class with full package name
    manifest.attributes("Main-Class":"com.app.MyApp", 'Class-Path': '/')
}
```
The fat jar is able to start and log4j2 is able to find the configuration. Now it fails because it can't find the AsyncAppender which seems to be only included in newer log4j2 revisions.

```
org.apache.logging.log4j.core.config.ConfigurationException: No appenders are available for AsyncAppender async
        at org.apache.logging.log4j.core.appender.AsyncAppender.start(AsyncAppender.java:106)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:168)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:359)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:420)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:138)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:147)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:175)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:426)

```

**Comment by johnrengelman** [comment]
You'd need to write your own `Transformer` class (https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/Transformer.groovy) and then add it to your build using:
```
shadowJar {
  transform(MyTransformer.class)
}
```

The workaround you are using is highly non-performant as you are expanding all of your dependencies onto disk using the `zipTree` method.

**Comment by PatrickHuetter** [comment]
Thank you @johnrengelman . I don't use zipTree and the code above anymore. It was only for testing another approach. I got it already working with shadowJar using the steps described in my last post. If i get further problems i'll investigate in writing a Transformer. Best regards

**Comment by reutsharabani** [comment]
I encountered the same problem (I think) with log4j versions that are greater than 2.5.

Downgrading log4j to 2.5 made shadow work again.

**Comment by TheBoegl** [comment]
@johnrengelman could you include the _converted_ [maven-shaded-log4j-transformer](/edwgiz/maven-shaded-log4j-transformer) like in this [gist](//gist.github.com/TheBoegl/695eaa6837764bcfb08137a48d873c60)? This could be a solution for TheBoegl/gradle-launch4j#40.

**Comment by johnrengelman** [comment]
@TheBoegl if someone wants to submit it as PR, I'd be happy to merge it.

**Comment by TheBoegl** [comment]
@johnrengelman I think a own _plugin_ would be better to avoid the log4j2 dependency in the shadow plugin, therefore, my previous comment only hints a workaround.

**Comment by TheBoegl** [comment]
I created a [gradle plugin](https://github.com/TheBoegl/shadow-log4j-transformer), but typo'd to reference this issue.

**Comment by johnrengelman** [comment]
@TheBoegl neat. No need for it to be a full plugin though. Could just be a library that a user can add to the buildscript classpath.

**Comment by TheBoegl** [comment]
@johnrengelman Thanks. It really is just one class that applies this plugin and adds the transformation. I could not think of an easier use case though you seem to have one in mind. Could you please elaborate on that?

**Comment by johnrengelman** [comment]
Your library really only needs the transformer class. You don't need a gradle plugin. so you woudl do this

```
buildscript {
  dependencies {
    classpath "com.github.jengelman.gradle.plugins:shadow:1.2.4"
    classpath 'de.sebastianboegl.gradle.plugins:shadow-log4j-transformer:1.0.1'
  }
}

apply plugin: 'com.github.johnrengelman.shadow'

shadowJar {
  transform(de.sebastianboegl.gradle.plugins.shadow.transformers.Log4j2PluginsFileTransformer)
}
```

**Comment by TheBoegl** [comment]
You are absolutely right, hence, I've added the description to the readme.  I've thought you meant a much more difficult way...

**Comment by Corionis** [comment]
For those wanting to merge multiple Log4j2Plugins.dat files and any custom log4j plug-ins using the annotation-generated Log4j2Plugins.dat in an **Ant script** see the GitHub project [MergeLog4j2Plugins](https://github.com/Corionis/MergeLog4j2Plugins).
