### ISSUE TITLE
ZipException: invalid literal/lengths set

### ISSUE THREAD

**Issue by Favorlock** [johnrengelman/shadow#208]
Here is the exception I'm getting: http://pastebin.com/yfUJzA8S

A temporary solution is renaming the extension from .zip to .zipx. If a file is in the resource folder you shouldn't be attempting to explode it whatsoever. It's in the resource folder for a reason.

**Comment by johnrengelman** [comment]
Duplicate of https://github.com/johnrengelman/shadow/issues/196
