### ISSUE TITLE
Android: Renaming the Package of a Dependency

### ISSUE THREAD

**Issue by vapoyan** [johnrengelman/shadow#209]
I need to rename the Java package of a 3rd party library, e.g. Firebase to include it directly in project while avoiding possible conflicts. Imagine situation that you are creating library Foo which depends on Firebase library and someone who use your library also use Firebase so we will have conflict.

build.gradle

```
buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:1.2.3'
    }
}

apply plugin: 'com.github.johnrengelman.shadow'

task shadowJar(type: com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    archiveName = "firebase-client-android-2.5.2.jar"
}

shadowJar {
    // Filtering shadow jar contents by file pattern.
    exclude 'LICENSE.txt'
    exclude 'META-INF/LICENSE'
    exclude 'META-INF/LICENSE.txt'
    exclude 'META-INF/NOTICE'
    exclude 'META-INF/NOTICE.txt'

    // Relocating dependencies.
    relocate 'com.firebase', 'com.viktor.firebase'
}
```

As soon as I try yo use my library in project which use same dependency I got following error.

> Error:Execution failed for task ':mapsapp:transformClassesWithDexForDevDebug'.
> 
> > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

What I'm doing incorrect ? and will shadowJar help me solve my issue ?

**Comment by johnrengelman** [comment]
can you run with `gradle -s` and get the stack trace?
What version of Gradle?

Yes, this is exactly the user case for Shadow.

**Comment by vapoyan** [comment]
After your suggestion I add following line to gradle 

```
dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:1.2.3'
        classpath 'com.android.tools.build:gradle:2.0.0'
    }
```

and I go one step further, now I have following issue 

```
Error:Execution failed for task ':mapsapp:transformResourcesWithMergeJavaResForDevDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/maven/com.fasterxml.jackson.core/jackson-core/pom.properties
  	File1: /Users/viktora/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.2.2/d20be6a5ddd6f8cfd36ebf6dea329873a1c41f1b/jackson-core-2.2.2.jar
  	File2: /Users/viktora/AndroidProjects/concierge-android-sdk/Concierge-SDK/mapsapp/build/intermediates/exploded-aar/com.gotoassist/concierge/unspecified/internalDebug/jars/classes.jar
```

How I can resolve this?

**Comment by johnrengelman** [comment]
That error is coming from the Android plugin (per the exception class), why do you think this is a shadow problem?

**Comment by devinmorgan** [comment]
For anybody that arrives on this thread like I did from Google, here is [a link to a repo](https://github.com/devinmorgan/shadow-plugin-for-aar) containing an example Gradle Plugin that allows you to use the ShadowJar task on Android Artifact dependencies. Hopefully it's helpful!
