### ISSUE TITLE
Classes are not relocated properly between transitive dependencies and its dependant jars

### ISSUE THREAD

**Issue by averabaqsncr** [johnrengelman/shadow#210]
In my use case, I'm trying to rename the package of a transitive dependency (e.g. javax.ws.rs:javax.ws.rs-api) that my jersey library depends to (see dependency tree below). The classes are renamed properly in the project but they are not renamed in the dependant jar (org.glassfish.jersey.core:jersey-client). So this is causing my project to fail at runtime:

Caused by: java.lang.NoSuchMethodError: org.glassfish.jersey.model.internal.CommonConfig.<init>(Lrepackaged/javax/ws/rs/RuntimeType;Ljersey/repackaged/com/google/common/base/Predicate;) 

Is this the expected behaviour? 

Any feedback is much appreciated.

```
+--- project :myProject
+--- org.glassfish.jersey.core:jersey-client:2.22.2
|    +--- javax.ws.rs:javax.ws.rs-api:2.0.1
```
```
dependencies {

  compile 'org.slf4j:slf4j-api:1.7.18'
  compile 'org.glassfish.jersey.core:jersey-client:2.22.2'
  compile 'org.glassfish.jersey.connectors:jersey-apache-connector:2.22.2'
  compile 'org.glassfish.jersey.media:jersey-media-json-jackson:2.22.2'

  testCompile group: 'junit', name: 'junit', version: '4.10'
  testCompile group: 'org.mockito', name :'mockito-all', version: '1.8.5'
}

shadowJar {
  classifier = ''
  dependencies {
    include(dependency('org.glassfish.jersey.core:jersey-client:2.22.2'))
    include(dependency('org.glassfish.jersey.connectors:jersey-apache-connector:2.22.2'))
    include(dependency('org.glassfish.jersey.media:jersey-media-json-jackson:2.22.2'))
    include(dependency('javax.ws.rs:javax.ws.rs-api:2.0.1'))
  }
  relocate 'javax.ws.rs', 'repackaged.javax.ws.rs'
}
```

**Comment by johnrengelman** [comment]
@averabaqsncr I'm assuming you found an error or a solution? Mind sharing it in case other people come find this ticket?
