### ISSUE TITLE
Proper example: shadow jar plugin in multi-project builds

### ISSUE THREAD

**Issue by itissid** [johnrengelman/shadow#212]
Hi I have put together a minimal [example](https://github.com/itissid/test_multi_jar_shadow): Two sub projects foo and bar,  foo depends on bar and a compile dependency. I want a shadow jar that has sources of foo and bar. 
NOTE: In the real world there are multiple subprojects with dependency on bar and all of them need to be bundled up into a fatjar.

How might I do this?

Calling the Shadow jar  plugin from the root project does not do the trick. But it seems I am doing something obviously wrong.

**Comment by liach** [comment]
Move the shadowJar task to the foo project.

**Comment by itissid** [comment]
Actually that does the trick for foo, but if there are multiple projects all dependent on bar I want to create *one* jar for all of them
