### ISSUE TITLE
can't find ZipOutputStream

### ISSUE THREAD

**Issue by akir94** [johnrengelman/shadow#215]
Trying to copile a vertx module. My build.gradle looks like this:

```
buildscript {
    dependencies {
        classpath fileTree(dir: "/path/to/dir", include: "shadow-1.2.3.jar")
    }
}

plugins {
    id 'java'
    id 'application'
}

apply plugin: com.github.jengelman.gradle.plugins.shadow.ShadowPlugin

/* boring stuff */

shadowJar {
    classifier = 'fat'
    mergeServiceFiles = {
        include 'META-INF/services/io.vertx.core.api.VerticleFactory'
    }
}
```

I'm using gradle 2.10 and shadow 1.2.3.
(I'm working in an offline environment, so I'm applying the plugin from a jar file).

When trying to build, I get an error:
`ClassNotFoundException: org/apache/tools/zip/ZipOutputStream`

**Comment by johnrengelman** [comment]
That won't work. You'll have to also include any of Shadow's dependencies as specified in its POM. 

A better way to do the offline install would be to use the Maven Local cache.
