### ISSUE TITLE
Using several include statements

### ISSUE THREAD

**Issue by akir94** [johnrengelman/shadow#216]
I have the following configuration:

```
dependencies {
    compile 'io.vertx:vertx.core:3.2.1'
    compile 'io.vertx:vertx.web:3.2.1'

    shadow 'io.netty:netty-transport:4.0.33Final'
}

// boring stuff

shadowJar {
    classifier = 'fat'

    dependencies {
        include(dependency('io.vertx:.*:3.2.1'))
        include(dependency('io.netty:.*:4.0.33Final'))
    }
}
```

However, the resulting shadow jar doesn't contain the netty classes, only the vertx ones. What could be wrong?
I'm using gradle 2.10 and shadow 1.2.3.

**Comment by johnrengelman** [comment]
You've put the `netty` classes into the `shadow` scope, so they will never be included in the fat jar. If you want them to be in there, just add them to `compile`

Also you don't need the `include` if you're wanting to have all your dependencies in the shadow jar.

`shadow` scope is for dependencies that are not merged into the shadow jar and then become the "runtime" dependencies of teh resulting shadow jar...i.e. if you look at the POM for the shadow JAR, dependencies that are in `shadow` scope will be listed as `runtime` dependencies in the POM.
