### ISSUE TITLE
Filtering license doesn't work

### ISSUE THREAD

**Issue by leventov** [johnrengelman/shadow#219]
This instruction doesn't work: https://github.com/johnrengelman/shadow#filtering-shadow-jar-contents-by-file-pattern

LICENSE files are located in META-INF directory.

Also, from documentation it is not clear what is the pattern syntax (glob? regex?) is expected and what is the basedir of those patterns. But none of combination I've tried works.

**Comment by leventov** [comment]
This works like the follows
```
shadowJar {
  exclude 'META-INF/LICENSE'
}
```

**Comment by johnrengelman** [comment]
The `exclude` method is inherited from Gradle's `Jar` task (which is inherited from Gradle's `Copy` task).
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:exclude(java.lang.Iterable)
It's an ANT pattern.
if you can post an example that exhibits the problem I can look. By there is an acceptance spec that tests this functionality and passes (and I've use it successfully) (https://github.com/johnrengelman/shadow/blob/master/src/test/groovy/com/github/jengelman/gradle/plugins/shadow/FilteringSpec.groovy#L47-L63)

**Comment by leventov** [comment]
I think readme and docs just need a little update because currently they are unclear. And example with filtering licenses doesn't filter licenses in real life, because Jars have licenses in `META-INF` subdirectory, not the root of the jar, and expression `exclude 'LICENSE'` doesn't filter them.

**Comment by johnrengelman** [comment]
The intent is not to document every possible use case but to provide an example of how to configure your project accordingly.

**Comment by johnrengelman** [comment]
Also, there's no standard that says that `LICENSE` has to be in `META-INF`.

**Comment by leventov** [comment]
There is no such stardard, but this is the de-facto convention to put license and notice files in META-INF.

The example that is currently in the Readme has little practical sense and eats time and efforts of users, who stumbles why it doesn't work (like it did for me).

**Comment by johnrengelman** [comment]
If you take such an issue with the documentation, then please take the time to issue a PR with how you feel it should be written.
