### ISSUE TITLE
Support Gradle 2.12+ compileOnly configuration

### ISSUE THREAD

**Issue by prokod** [johnrengelman/shadow#220]
I t would be nice if shadowJar could take advantage of this native configuration that was added from Gradle version 2.12 onward and provides the similar functionality as Maven provided scope.

By taking advantage I mean it would be nice to have the plugin calculating the needed default dependencies to include based on compileOnly configuration input also.

**Comment by johnrengelman** [comment]
How would you intend this to work? If they are compileOnly then I would imagine you don't want them merged into the shadow jar.

**Comment by prokod** [comment]
Exactly. Sorry for not stating that from the beginning.

**Comment by johnrengelman** [comment]
Have you actually tried this? Without trying, I'm pretty sure this will just work because of the way that `compileOnly` is implemented. `runtime` doesn't extend from it AFAICT.

**Comment by johnrengelman** [comment]
@prokod this is works out of the box. `compileOnly` dependencies will not be present in the Shadow jar.
However, dependencies in `compileOnly` wont' be added to the Jar Manifest file like they are for dependencies in the `shadow` configuration. So you would have to manually manage that.
