### ISSUE TITLE
Plugin with id 'com.github.johnrengelman.shadow' not found.

### ISSUE THREAD

**Issue by dbraynard** [johnrengelman/shadow#221]
I get the following error:

> Plugin with id 'com.github.johnrengelman.shadow' not found.

I am using exactly this:
```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "com.github.jengelman.gradle.plugins:shadow:1.2.3"
  }
}

apply plugin: "com.github.johnrengelman.shadow"
```

I have tried putting it under subprojects, all projects, root, individual project sections.

Any help would be appreciated.

```
------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_77 (Oracle Corporation 25.77-b03)
OS:           Linux 4.2.0-16-generic amd64
```

**Comment by dbraynard** [comment]
I solved my issue. The java plugin must be applied as prior to the shadow plugin, even though the subprojects section already applies the java plugin.

**Comment by johnrengelman** [comment]
there no ordering required for plugin application. The error you are receiving would not have anything to do with applying the java plugin. It's indicative of the JAR for shadow not being on the buildscript classpath.

I would need to see your full buildscripts to determine the real reason.

**Comment by alon-unifi** [comment]
FYI I've had the same happened to me, after patching my local jdk from 8.0_45 to 8.0_131. It was happening consistently until it suddenly started working (with not changes to the build script). No clue what the RC is. I'm on gradle 4.10.3

**Comment by alon-unifi** [comment]
looks like the plugin jars are occasionally not available - and that was the problem
https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/4.0.4/ (and the same for other versions) in the last few days was showing the jars and at times they were gone. This is why things magically started working again for me (and later on failed again). @johnrengelman just wondering if you've seen this before? thanks.

**Comment by pavelkostyurin** [comment]
Happened to me as well
```
Plugin [id: 'com.github.johnrengelman.shadow', version: '5.1.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:5.1.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

```

```
plugins {
    id 'java'
    id "com.github.johnrengelman.shadow" version "5.1.0"
}
```

**Comment by logkashunmughum** [comment]
plugins {
    id 'java'
    id "com.github.johnrengelman.shadow" version "5.1.0"
}

this worked! Thanks

**Comment by cyberpwnn** [comment]
Why is this closed? Still doesnt work.

**Comment by johnrengelman** [comment]
It’s closed because it’s not something I control (the artifacts are in either Bintray or Gradle’s maven repository), Nothing has changed about them, so if there is issues resolving or retrieving them, that’s because of issues with their infrastructure.

**Comment by cyberpwnn** [comment]
> It’s closed because it’s not something I control (the artifacts are in either Bintray or Gradle’s maven repository), Nothing has changed about them, so if there is issues resolving or retrieving them, that’s because of issues with their infrastructure.

Then why is it ONLY this project that never resolves? Why does every other plugin work as intended except for shadow?

**Comment by tasosz** [comment]
@johnrengelman - it looks like there are 2 different locations for the plugin.
The expected location: https://plugins.gradle.org/m2/com/github/johnrengelman/shadow/ ("johnrengelman") which only has the 8.1.0 and 8.1.1 versions.
This location also contains this: https://plugins.gradle.org/m2/com/github/johnrengelman/shadow/com.github.johnrengelman.shadow.gradle.plugin/ under which **all** versions exist.

Then there is also this location: https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/ ("jengelman") which also has the <=6.1.0 versions

Maybe the above are related to the "not found" issues many are having with this plugin.

**Comment by ryantheleach** [comment]
At least a few people here judging by github profiles are ending up here from PaperMC related projects.

I believe that a change that isn't well represented in git, due to the unique structure of that project and a structural change they made, is causing this error, and it's not immediately obvious.

Advice given on their discord was to delete and reclone if possible, and we should stop annoying poor John and the gradleup plugin team about it.

**Comment by Goooler** [comment]
https://central.sonatype.com/artifact/com.gradleup.shadow/shadow-gradle-plugin

**Comment by gptshubham595** [comment]
https://github.com/GradleUp/shadow?tab=readme-ov-file

<img width="855" alt="Image" src="https://github.com/user-attachments/assets/39ba71b9-c5d7-4f0b-96c1-296917fbdfb3" />

https://plugins.gradle.org/plugin/com.gradleup.shadow
