### ISSUE TITLE
Documentation could use improvement

### ISSUE THREAD

**Issue by sc1478** [johnrengelman/shadow#222]
> Shadow is an extension of the Gradle Jar task that optimizes FatJar/UberJar creation by using JarInputStream and JarOutputStream to copy file contents. This avoids the unnecessary I/O overhead of expanding jar files to disk before recombining them. Shadow provides the similar filtering, relocation, and transformation capabilities as the Maven Shade plugin. 

The problem I see in this is that you have to understand what the Maven Shade plugin is to understand what all this stuff is for.  And the various tasks described.  What is "shadowing" exactly?  What does "shadow" as a dependency configuration do?  None of these things are explained.

You shouldn't have to refer back to Maven Shade documentation to understand the basic concepts being described here.

For instance, it required a forum query for me to even FIND this plugin: [https://discuss.gradle.org/t/jar-with-some-dependencies/17784](https://discuss.gradle.org/t/jar-with-some-dependencies/17784 ).  "Shadow" or "Shade" is not an obvious answer to the question, how do I include some but not necessarily all of my jar project's dependencies in the jar.

**Comment by johnrengelman** [comment]
Duplicate of https://github.com/johnrengelman/shadow/issues/87

Please understand that this is an open source project that I do in my spare time. There is a goal to create better documentation (hopefully ready in the next couple months, but no promise). Life and my full time job come first.

**Comment by johnrengelman** [comment]
And as an open source project, if someone wants to write and submit documentation as a PR, I'd be more than happy to consider it.

**Comment by sc1478** [comment]
I'd volunteer but I wouldn't know what the hell I was talking about, unfortunately.  Do you know WHY the type of functionality your plugin (which works quite well by the way and thanks - didn't mean to pester you!) provides, is called "shading" or "shadowing"?  And also let me compliment you for providing the "knows" task.  A sense of humor is helpful.

**Comment by johnrengelman** [comment]
This plugin started as a port of Maven's Shade plugin to Gradle. As such, the name Shadow is supposed to play off the name of the source code (Shade). I believe "shading" refers to the plugin's ability to relocate (or shade) packages to a different package name.

At this point, Shadow has been rewritten and is no longer a direct port of Shade. It uses some of common concepts and strives to provide the similar features but it is it's own entity now.

**Comment by johnrengelman** [comment]
User Guide now available - http://imperceptiblethoughts.com/shadow/

**Comment by sc1478** [comment]
Thank you!
