### ISSUE TITLE
Runnable Jar which runs directly from shell without needing java -jar 

### ISSUE THREAD

**Issue by faizanahemad** [johnrengelman/shadow#233]
### Shadow Version
1.2.3
### Gradle Version
2.13
### Expected Behavior
Runnable jar which can be run on shell by doing ./jar-name.jar
### Actual Behavior
Currently jars need to be run by `java -jar jar-name.jar`
### Gradle Build Script(s)
[build.gradle](https://github.com/faizanahemad/splash-screen/blob/master/build.gradle)
[gradle.properties](https://github.com/faizanahemad/splash-screen/blob/master/gradle.properties)
[setting.gradle](https://github.com/faizanahemad/splash-screen/blob/master/settings.gradle)
If you clone the [repo](https://github.com/faizanahemad/splash-screen.git) you can use `./gradlew clean build fatCapsule shadowJar` for building, then go to _build/libs_ execute `java -jar splash-screen-0.0.1-shadow.jar` to see Shadow Jar running. You can see the Capsule plugin output which does create a runnable jar by  `./splash-screen-0.0.1-release.jar`
### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
META-INF/
META-INF/MANIFEST.MF
io/
io/faizan/
io/faizan/SplashDemo$1.class
io/faizan/SplashDemo.class
loader.gif

### More Details
[Another Plugin-Gradle Capsule Plugin](https://github.com/danthegoodman/gradle-capsule-plugin) does implement this feature.

**Comment by johnrengelman** [comment]
This comes up every so often. I feel that this is outside the scope of Shadow. I think it would be better implemented in another plugin (perhaps the gradle-capsule plugin) to be Shadow aware.
