### ISSUE TITLE
shadow with ratpack-groovy error

### ISSUE THREAD

**Issue by faquad** [johnrengelman/shadow#235]
ratpack1.4 with lazybones-template, jdk 8,  using groovy-sql  in groovy-class.
unit-tests (spock) works fine.
running artifact on productive from shadowJar throws exception on call Date.toTimeStamp:
trace:

ERROR:No signature of method: java.util.Date.toTimestamp() is applicable for argument types: () values: [].

rebuild with installDist fixed the problem.
### Shadow Version

1.2.3
### Gradle Version

2.9
### Expected Behavior

groovy code works
### Actual Behavior

exception

**Comment by faquad** [comment]
related slack-msg:
https://ratpack.slack.com/archives/ratpack/p1470826504001909

**Comment by johnrengelman** [comment]
Can you post an example project?

**Comment by johnrengelman** [comment]
Can you try adding this your Gradle file and see if it makes it work?
```
shadowJar {
  mergeGroovyExtensionModules()
}
```

**Comment by johnrengelman** [comment]
@faquad have you tried my suggestion above?

**Comment by johnrengelman** [comment]
Closing due to lack of response. Please re-open if the issue persists and you have tried the above suggestion.
