### ISSUE TITLE
Problem with scriptsShadow/* related to lib/libs

### ISSUE THREAD

**Issue by rodgarcialima** [johnrengelman/shadow#236]
**scriptsShadow/all scripts** are pointing to **lib** instead of **libs** directory.
### Shadow Version

1.2.3
### Gradle Version

2.14.1

**Comment by johnrengelman** [comment]
Why is this a problem? Are you saying the scripts don't work currently? This behavior should be following the Gradle Application plugin which uses `lib` and `bin`: https://docs.gradle.org/current/userguide/application_plugin.html

**Comment by rodgarcialima** [comment]
My project's name is `mtef-server`. Generated `scriptsShadow/mtef-server.bat` is pointing to:
`@rem Execute mtef-server
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %MTEF_SERVER_OPTS%  -jar "%APP_HOME%\lib\mtef-server.jar" %CMD_LINE_ARGS%`, but my `mtef-server.jar` is inside libs directory.

**Comment by johnrengelman** [comment]
Can you post an example project that exhibits this? All of my projects put the jar in `%APP_HOME%\lib\`

**Comment by johnrengelman** [comment]
Closing due to lack of response.

**Comment by tuvistavie** [comment]
I had the same issue, adding

```
sourceSets {
    libsDirName = 'lib'
}
```

to my `build.gradle` file did the job.

**Comment by paulmckenzie** [comment]
I also observe the same behaviour. The solution from @danhper works for me too.
