### ISSUE TITLE
Cannot refer to Windows environment variables in applicationDefaultJvmArgs

### ISSUE THREAD

**Issue by jlepropre** [johnrengelman/shadow#238]
### Shadow Version

1.2.3
### Gradle Version

2.13
### Expected Behavior

I would like to be able to use some Windows environment variables in applicationDefaultJvmArgs:
`applicationDefaultJvmArgs << '-Djava.ext.dirs=../lib/ext' + ((targetPlatform == 'windows') ? ';%JAVA_HOME%' : ':$JAVA_HOME') + '/lib/ext'`
### Actual Behavior

The percentage signs are repeated because of `com.github.jengelman.gradle.plugins.shadow.internal.StartScriptGenerator.generateWindowsScriptContent` hence the resulting script does not work.
### Gradle Build Script(s)

See above.

**Comment by jlepropre** [comment]
Maybe we should use some escape mechanisms?

**Comment by johnrengelman** [comment]
Have you tried this with a standard Gradle project using the application plugin? I'm wondering if I just need to sync up the scripts that get generated.

**Comment by jlepropre** [comment]
Hi,

I have just tried with application plugin only (see [test-shadow.zip](https://github.com/johnrengelman/shadow/files/424377/test-shadow.zip)) and I have the same issue.

Here are the steps to reproduce:
1. Unzip the project.
2. Run `gradlew clean distZip`
3. Ensure that `JAVA_HOME` refers to a JRE directory, not JDK.
4. Try to run the application by using `test-shadow.bat`. You should get `Error: Could not find or load main class lu.nowina.test.shadow.TestShadow`.
5. Edit `test-shadow.bat` and delete the two extra `%`.
6. Run the application again and it will work now.

Do you think it is rather an application plugin issue?

Thanks in advance for your answer,
Jean.

**Comment by jlepropre** [comment]
See https://discuss.gradle.org/t/application-plugin-percent-char/853 for similar issue with application plugin.

**Comment by johnrengelman** [comment]
This is not an issue with shadow per-say. v2.0.0 of shadow will remove the custom implementation and rely solely on Gradle's `CreateStartScript` task. In the 3.x line of Gradle, this task allows you to specify your own template file and your own generator if needed. So i'm going to close this as this is either an upstream issue in Gradle or can be worked around using those methods.
