### ISSUE TITLE
Simpler directory structure for installShadow- and distShadow- tasks

### ISSUE THREAD

**Issue by NikitaMerinov** [johnrengelman/shadow#239]
### Shadow Version
1.2.3
### Gradle Version
2.14

Preconditions: Application plugin applied.

Currently when we invoke installShadowApp it will do things similar to installDist task from application plugin: create two folders bin and lib, put startup scripts to bin folder, put single fat jar to the lib folder. (Same is applied to "dist" tasks)

While it makes sense to do this for usual case when we have many dependencies, for fat jar it seems to be unnecessary: having single executable jar we can just pack startup scripts and single jar together in one folder.

So instead of
app/
--bin/
----scripts
--lib/
----single fat jar

we can get
app/
--scripts
--single fat jar

which seems to be more feasible.

Currently it can be achieved by customizing startup scripts and doing some additional file manipulations to implement that single directory structure for install and dist tasks.

Does this single directory structure look viable and will be there any plans to incorporate this into shadow plugin?

**Comment by johnrengelman** [comment]
I'd prefer to keep it to mimic the application plugin so that I can leverage the behavior from that plugin.
