### ISSUE TITLE
dependencies from custom configuration

### ISSUE THREAD

**Issue by eprst** [johnrengelman/shadow#240]
I think I'm missing something obvious here, but I can't make shadow to work with a simple custom configuration:

```
plugins {
  id 'com.github.johnrengelman.shadow' version '1.2.3'
}

apply plugin: 'base'

configurations {
  foo
}

dependencies {
  foo files("$projectDir/test.jar") // put some real jar here
}

task jar(type: com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) << {
  configurations = [project.configurations.foo]
}
```

Resulting jar built by `gradle jar` is empty, `test.jar` doesn't get included. What's the catch?

Thanks

### Shadow Version
1.2.3

### Gradle Version
2.14

**Comment by johnrengelman** [comment]
Don't use << when trying to configure task. 
shadowJar {
 configurations = [....]
}

**Comment by eprst** [comment]
oh, of course. Thanks!
