### ISSUE TITLE
Compile dependencies are included in output jar

### ISSUE THREAD

**Issue by jvmlet** [johnrengelman/shadow#241]
I'm running `shadowJar` task and compile dependencies appear in output jar.
Am i missing some configuration ?
Thanks
### Shadow Version
1.2.3
### Gradle Version
2.14.1
### Expected Behavior
compile dependencies don't appear in -all.jar
### Actual Behavior
lombok classes are included in X-all.jar
### Gradle Build Script(s)
plugins {
    id "com.github.johnrengelman.shadow" version "1.2.3"
}
apply plugin: 'java'
    repositories {
        mavenCentral()
    }
    dependencies{
        compile  'org.projectlombok:lombok:1.16.6'
        runtime 'net.sf.ucanaccess:ucanaccess:3.0.6'
    }
build.dependsOn(shadowJar)

**Comment by lbergelson** [comment]
@jvmlet 

I think you're thinking of `compileOnly` dependencies.  The `runtime` scope depends on `compile`.

See https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_plugin_and_dependency_management for more information.

**Comment by johnrengelman** [comment]
This is correct behavior.

**Comment by jvmlet** [comment]
You are right, thanks. 
I think it's worth to mention it in the documentation that compile dependencies are added implicitly with default configuration.
