### ISSUE TITLE
Could not find com.github.jengelman.gradle.plugins:shadow:1.2.3

### ISSUE THREAD

**Issue by gautamram** [johnrengelman/shadow#242]
Hi,

Below is the code i'm having in my code snippet that i'm trying to use for shodow plugin.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:1.2.3'
    }
}

apply plugin: 'com.github.johnrengelman.shadow'

Currently i'm getting the below exception when I do a gradle clean,

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':Integration'.
> Could not resolve all dependencies for configuration ':Integration:classpath'.
   > Could not find com.github.jengelman.gradle.plugins:shadow:1.2.3.
     Searched in the following locations:
         https://jcenter.bintray.com/com/github/jengelman/gradle/plugins/shadow/1.2.3/shadow-1.2.3.pom
         https://jcenter.bintray.com/com/github/jengelman/gradle/plugins/shadow/1.2.3/shadow-1.2.3.jar
     Required by:
         com.myproj:Integration:5.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.306 secs

Kindly let me know if there is something I'm missing.

**Comment by johnrengelman** [comment]
Try again. It's there. When I click on the links you posted, I get promoted to download.
