### ISSUE TITLE
    Is there a way to skip the exception when shadowJar processes the class files within a JAR file?

### ISSUE THREAD

**Issue by mukilansai** [johnrengelman/shadow#243]
Please check the (User Guide)[http://imperceptiblethoughts.com/shadow] before submitting "how do I do 'x'?" questions!
    Is there a way to skip the exception when shadowJar processes the class files within a JAR file?
### Shadow Version

   Latest
### Gradle Version

Latest

**Comment by johnrengelman** [comment]
Not sure what you are asking. What exception?

**Comment by mukilansai** [comment]
When i execute the shadowjar task to re-locate a package inside jar I got
"Array Index Out of Bound" exception while processing some class files.
The task stops after that. Is there a way to continue building the jar,
skipping the classes that leads to exception?

**Comment by johnrengelman** [comment]
No, there is no way to arbitrarily suppress exceptions during the process.
an Array Index Out Of Bounds exception would not be good, if you post the stack trace and your `build.gradle` file, I can take a look to see if there is something obvious or if there is a real bug here.

**Comment by johnrengelman** [comment]
Closing due to lack of response. Please comment if you are still having issues and can provide a reproducible example.
