### ISSUE TITLE
Could not find method shadowJar()

### ISSUE THREAD

**Issue by gautamram** [johnrengelman/shadow#244]
Hi @johnrengelman!

Thanks for that great library. I have a use case and even with the docs I couldn't figure out how to implement that. Could you please let me know if that works and also maybe how.

I have a multi-project where I need to shadow some dependencies of the sub-project and others too.

    buildscript {
        repositories {
           maven {
               url "https://plugins.gradle.org/m2/"
           }
       }
    }

    dependencies {
      compile project(':OVC-JAXRS')
      compile project(':Generic-Server')
      compile "com.github.jengelman.gradle.plugins:shadow:1.2.3"
      testCompile group: 'org.testng', name: 'testng', version:'6.8.8'
      compile group: 'org.eclipse.jetty', name: 'jetty-servlet', version:'8.1.16.v20140903'
    }

    shadowJar {

	configurations = "proj-integration-5.7.0"

    include 'com.oneview:Generic-Util'
    include 'org.glassfish.hk2:hk2-api'
    include 'org.glassfish.hk2:hk2-utils'
    include 'org.glassfish.hk2:hk2-locator'
    include 'org.glassfish.hk2:osgi-resource-locator'
    include 'org.glassfish.hk2.external:aopalliance-repackaged'
    include 'org.codehaus.jackson:jackson-core-asl'
    include 'org.codehaus.jackson:jackson-mapper-asl'
    include 'org.codehaus.jackson:jackson-jaxrs'
    include 'org.codehaus.jackson:jackson-xc'
    include 'org.javassist:javassist'
    include 'javax.annotation:javax.annotation-api'
    include 'org.glassfish.hk2.external:javax.inject'
    include 'javax.ws.rs:javax.ws.rs-api'
    include 'org.glassfish.jersey.core:jersey-client'
    include 'org.glassfish.jersey.core:jersey-common'
    include 'org.glassfish.jersey.bundles.repackaged:jersey-guava'
    include 'org.glassfish.jersey.media:jersey-media-json-jackson'
    include 'org.json:json'
    include 'com.proj:OVC-JAXRS'

    relocate 'jersey.repackaged', 'ovc.repackaged'
    relocate 'javassist','ovc.repackaged.javassist'
    relocate 'org.aopalliance','ovc.repackaged.org.aopalliance'
    relocate 'org.apache.logging','ovc.repackaged.org.apache.logging'
    relocate 'org.codehaus.jackson','ovc.repackaged.org.codehaus.jackson'
    relocate 'org.glassfish.hk2','ovc.repackaged.org.glassfish.hk2'
    relocate 'org.glassfish.jersey','ovc.repackaged.org.glassfish.jersey'
    relocate 'org.json','ovc.repackaged.org.json'
    relocate 'org.jvnet','ovc.repackaged.org.jvnet'
    relocate 'javax.annotation','ovc.repackaged.javax.annotation'
    relocate 'javax.inject','ovc.repackaged.javax.inject'
    relocate 'javax.ws','ovc.repackaged.javax.ws'
    }
    task genericIntegrationJar(type: ShadowJar) {
	   shadowJar {
	     manifest {
	       inheritFrom ovc.repackaged.genericIntegrationJar
	     }
	   }
	   baseName = 'proj-integration-5.7.0-SNAPSHOT'
       from { configurations.external.collect { it.isDirectory() ? it : zipTree(it) } }
       with jar
    }

Also when I make a gradle clean, it is throwing the below exception,

    FAILURE: Build failed with an exception.

	* Where:
	Build file '/Users/mac/Desktop/Generic-Integration/build.gradle' line: 24

	* What went wrong:
	A problem occurred evaluating project ':Generic-Integration'.
	> Could not find method shadowJar() for arguments [build_3odpjaloj234e20gr1e7ys74q$_run_closure2@6af65f29] on project ':Generic-Integration' of type org.gradle.api.Project.

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

	BUILD FAILED

I just tried adding the plugin in the other way as below, but i was getting another exception.

    buildscript {
	    repositories {
	        jcenter()
	    }
	    dependencies {
	        classpath 'com.github.jengelman.gradle.plugins:shadow:1.2.3'
	    }
	}

	apply plugin: 'com.github.johnrengelman.shadow'

Then i'm getting the exception like below,

    FAILURE: Build failed with an exception.

	* What went wrong:
	A problem occurred configuring project ':Generic-Integration'.
	> Could not resolve all dependencies for configuration ':Generic-Integration:classpath'.
	   > Could not find com.github.jengelman.gradle.plugins:shadow:1.2.3.
	     Searched in the following locations:
	         https://jcenter.bintray.com/com/github/jengelman/gradle/plugins/shadow/1.2.3/shadow-1.2.3.pom
	         https://jcenter.bintray.com/com/github/jengelman/gradle/plugins/shadow/1.2.3/shadow-1.2.3.jar
	     Required by:
	         com.oneview:Generic-Integration:5.7.0-SNAPSHOT

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

	BUILD FAILED

**Comment by gisgnanavel** [comment]
Hi @johnrengelman!

Me also facing similar issue .

**Comment by johnrengelman** [comment]
So, a few things. 
1) You are putting the plugin dependency inside the application `dependencies` block. This is incorrect. It needs to be inside the `buildscript` block.
```
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath 'com.github.jengelman.gradle.plugins:shadow:1.2.3'
  }
}
```
2) You need to explicitly apply the `java` or `groovy` plugins to the project along with `shadow` otherwise it won't automatically create any tasks. This is as is documented at the very end of this section: http://imperceptiblethoughts.com/shadow/#getting_started
3) this section make no sense:
```
task genericIntegrationJar(type: ShadowJar) {
   shadowJar {
     manifest {
       inheritFrom ovc.repackaged.genericIntegrationJar
     }
   }
   baseName = 'proj-integration-5.7.0-SNAPSHOT'
   from { configurations.external.collect { it.isDirectory() ? it : zipTree(it) } }
   with jar
}
```
Not sure why you are doing that...the most obvious thing is that you are configuring the `genericIntegrationJar`, so you don't need the nested `shadowJar` block inside it.
4) This line makes no sense: `configurations = "proj-integration-5.7.0"`. Again not sure what you are trying to accomplish. it should be something like `configurations = project.configurations.runtime`, but this wouldn't be necessary.

I'm closing this ticket because there is not anything wrong with shadow for your uses cases. This is clearly an implementation issue on your side.
