### ISSUE TITLE
Can not find shadowJar

### ISSUE THREAD

**Issue by trywarrior** [johnrengelman/shadow#245]
### Shadow Version
1.2.3
### Gradle Version
3.0(android studio)
### Expected Behavior
when run gradlw tasks, Shadow tasks contains knows and shadowJar
### Actual Behavior
![image](https://cloud.githubusercontent.com/assets/7802026/18342442/84510ce8-75e1-11e6-9d24-9608b479c01e.png)
### Gradle Build Script(s)
1.root build.gradle
![image](https://cloud.githubusercontent.com/assets/7802026/18342497/befca08c-75e1-11e6-93db-9323754be181.png)
2.module build.gradle 
![image](https://cloud.githubusercontent.com/assets/7802026/18342526/d8ed3556-75e1-11e6-85fd-6a1e8cce9274.png)
3. run gradle tasks
can not find shadowJar!

I want to know how apply the plugin in android studio,thanks

**Comment by johnrengelman** [comment]
Shadow reacts to the presence of the Java plugin being installed. I'm guessing with android projects that you don't have it and thus the `shadowJar` task is not created.

**Comment by isometriq** [comment]
and `apply plugin: 'java'` will output..
Error:The 'java' plugin has been applied, but it is not compatible with the Android plugins.
So there is no way around isn't ?

**Comment by johnrengelman** [comment]
You can still apply shadow, you just have to manually configure your own ShadowJar task there is not one automatically set up for you without the Java plugin.

**Comment by isometriq** [comment]
After playing around I was able to make it work.

```
dependencies {
    shadow "com.google.code.gson:gson:2.3.1"
    shadow "org.apache.httpcomponents:httpclient-android:4.3.5.1"
    
    compile "com.google.code.gson:gson:2.3.1"
    compile "org.apache.httpcomponents:httpcore:4.4.4"
    compile "org.apache.httpcomponents:httpmime:4.5.2"
}

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
task shadowJar(type: ShadowJar) {
    configurations = [project.configurations.shadow]
}
tasks.withType(JavaCompile) {
    compileTask -> compileTask.dependsOn shadowJar
}
```
It creates a jar in `./build/libs/MyProject.jar`

To make it work, I had to create a task like you said and also import the ShadowJar symbol. By the using the shadow configuration, I can "handpick" only what I need to include, but I'm aware I could have done `configurations = [project.configurations.testRuntime]` instead to include from every `compile` statements.

The only thing I'm unsure is when to execute the task. What would be the correct `dependsOn` ?

I think also it would save trouble to have a short snippet like this in the docs
