### ISSUE TITLE
Package not relocation

### ISSUE THREAD

**Issue by Favorlock** [johnrengelman/shadow#248]
Please check the (User Guide)[http://imperceptiblethoughts.com/shadow] before submitting "how do I do 'x'?" questions!

### Shadow Version
1.2.3

### Gradle Version
2.14.1

### Expected Behavior
com.google.gson relocated to net.fancycow.shadow.gson

### Actual Behavior
never relocated

### Gradle Build Script(s)
build.gradle (root) http://pastebin.com/WKy9Y9xP
build.gradle (utils) http://pastebin.com/6HvRJGmE

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
http://pastebin.com/QH42qMz4

**Comment by johnrengelman** [comment]
dependencies added to `configurations.shadow` are not candidates for relocation.
That scope is reserved for dependencies that you do not want to bundle into your JAR.
If you do want them bundled, you should add them to `configurations.compile` or `configurations.runtime`.

**Comment by Favorlock** [comment]
That doesn't really resolve the problem I'm experiencing though. If I use compile/runtime it ends up turning into dependency hell with having to manage a ton of transitive dependencies and appears that I have to re-declare those dependencies for modules that depend on another module. It's unusable for such a setup and the year+ I've been using shadow it has never worked anywhere remotely like I'd expect it to, no matter how many different configurations I tried.

**Comment by johnrengelman** [comment]
I'm sorry it doesn't work the way you expect it to, but that's the way it does. And many other people are successfully using this project for the over 3 years that it has existed.

**Comment by Favorlock** [comment]
I can't even get it to work the way it says it should in the documentation... it says if I want to depend on another project that I specify the shadow configuration, but that just makes gradle throw a bunch of "cannot find symbol" errors for the modules classes. That doesn't match up with the explanation in the documentation.

**Comment by Favorlock** [comment]
@johnrengelman 

You mention in the documentation to depend on the shadow jar of a sibling module that you would do something like this: compile project(path: ':common', configuration: 'shadow') but this isn't producing a new jar that contains the contents of the sibling shadow jar and the project's shadow jar contents.

What I'm getting is a shadow jar that contains everything, even the dependencies marked with shadow, which you said should be excluded from shadow jars.

**Comment by johnrengelman** [comment]
can you describe in simple terms what you are trying to accomplish?

**Comment by Favorlock** [comment]
I have project that consist of many modules. Here is the structure:

common
network-monitor (depends on and should shade common)
proxy (depends on and should shade common)
spigot-lib (depends on and should shade common shadowjar)
core (depends on and should shade spigot-lib shadowjar)
---
from that point I have various modules that depend on core but do not shade it:

hub (depends on core)
game (depends on core)
money-wars (depends on game and core)
party-battles (depends on game and core)
survivalgames (depends on game and core)

Only network-monitor module is a standalone application, the rest are plugins for a game server called spigot, which is a dependency in spigot-lib that shouldn't be shaded. I'm finding that if I try to shade in the shadowjar of common into spigot-lib and similarily spigot-lib into core it's shading the shadow dependencies of a project dependency being shaded.

**Comment by Favorlock** [comment]
changing project(path: ':common', configuration: 'shadow') to project(path: ':common', configuration: 'runtime') appears to work. From my understanding of the documentation and what you said in your first reply in this issue the former should have created a dependency on the shadowjar, not the shadow dependencies of the project dependency.

**Comment by Favorlock** [comment]
Appears that intellij still won't resolve the dependencies of project dependencies of a project dependency though.

**Comment by johnrengelman** [comment]
Not exactly simple terms so I'll try my best:

common.gradle
```
apply plugin: 'java'
apply plugin: 'com.github.johnrengelman.shadow'

dependencies {
  compile 'some:dep:version'
}
```

network-monitor.gradle
```
apply plugin: 'java'
apply plugin: 'com.github.johnrengelman.shadow'

dependencies {
  compile project(path: ':common', configuration: 'shadow')
}
```

And you basically should be repeating this over and over.
Anytime you run the `shadowJar` task it will combine *all* dependencies that a part of the configurations specified by `shadowJar.configurations` (by default this only `configurations.runtime`)
Runtime extends from compile, so *by default* `shadowJar` which merge any compile/runtime dependencies into the final output.

> it's shading the shadow dependencies of a project dependency being shaded.
I don't understand the point you are trying to make here. Shadow doesn't know anything about any dependency. It just combines the classes in a JAR into a single Jar. The rest of the dependency resolution is all core Gradle stuff.

Are you willing to share this project at all? It seems like you have a simple misunderstanding of the configuration and i'd be happy to take a look at the real code. You could remove any of the files in the `src` directories and share just the gradle files.

**Comment by Favorlock** [comment]
Here is a link to the project setup as I have it at the moment. https://db.tt/ZY7nT7v1

**Comment by johnrengelman** [comment]
I think you need to step back and ask yourself what you're trying to accomplish with this.
First, shadow really only serves 2 purposes: 1) to create a jar distribution that you can run by doing `java -jar` and 2) to relocate packages so they don't conflict with other versions used later.

If you aren't doing either of those things, then you don't need Shadow in your project. It provides nothing for you then.

**Comment by johnrengelman** [comment]
Also, perhaps this would be easier if we can chat on IRC...If so, jump into `#gradle-shadow` on FreeNode

**Comment by Favorlock** [comment]
I need both of those, and that's what I'm trying to accomplish. It's not shading properly for my project though. It ends up shading dependencies that shouldn't be shaded.

**Comment by johnrengelman** [comment]
Ok, after talking with @Favorlock we figured out the issue. I've create a ticket to improve the docs (https://github.com/johnrengelman/shadow/issues/257)

But here's the issue:

project a:
  compile "foo"
  shadow "bar"

project b:
  compile project(path: "a", configuration: "shadow")

this is what happens, `a.shadowJar` contains the classes from `foo` and then `bar` becomes the effective "runtime" dependencies for it. So if you generated a POM for `a.shadowJar`, it would contain `runtime "bar"` in it.

so in project b, `a.shadowJar` is pulled in as a `compile` dependency and Gradle resolves the dependency graph for that jar, which includes `bar` as a "runtime" dependency.
Thus `b.shadowJar` contains the contents of `a.shadowJar` (and any transformations), but also the classes from `bar`.

This was unexpected for @Favorlock (and may differ from the behavior of Maven Shade), has it was expected that since `bar` was declared as `shadow "bar"`, it would never be merged into a Jar even downstream.

The way to do this, is to exclude the transitives like so:
```
dependencies {
  compile project(path: "a", configuration: "shadow") {
    transitive = false
  }
}
```

**Comment by Favorlock** [comment]
@johnrengelman I'm running into another issue that may be caused by transitive=false. Any shared dependencies that are redeclared in another module that are also a transitive in a project dependency aren't resolving in the ide. Changing the order of dependencies doesn't appear to make a difference. :\

**Comment by johnrengelman** [comment]
@Favorlock I had a thought about this issue this morning. Have you tried using the `compileOnly` scope provided in the in newer Gradle release (3.x) instead of `configurations.shadow`?
I would suggest maybe giving that a try and see if that provided better behavior.
I haven't tested it yet...but I believe `compileOnly` dependencies will not be merged into the shadow jar.
