### ISSUE TITLE
How do I invoke shadowJar task instead of jar task when invoking assemble from the java pugin?

### ISSUE THREAD

**Issue by imochurad** [johnrengelman/shadow#249]
I am new to Gradle and Gradle Shadow. I am building an api project that is internally using a dropwizard framework. It's a Java project. There are a bunch of dependencies that have same files under `META-INF/services/`. When my application loads it fails to properly configure one of the auto-discoverable services and fails miserably. I learned that shadowJar can be of help in this situation.  Here is what I have in my `build.gradle` file:

```
jar {
    zip64 true
    from { configurations.runtime.collect { it.isDirectory() ? it : zipTree(it) } }
    manifest {
        attributes(
        'Main-Class': mainClassName,
        'version': project.version,
        'lastBuild': buildTime()
        )
    }
}
shadowJar {
    mergeServiceFiles()
    classifier = null
}
```
I build my project in the console by specifying: `./gradlew assemble`
As the gradle outputs info while building, it doesn't indicate invocation of the `shadowJar` task. It shows calling `jar` task, and I'd like assemble to invoke `shadowJar` instead.
Question: Is there a way to invoke shadowJar task automatically when running assemble? And what should be done for it? How do I override dependency of the built-in tasks?

### Shadow Version
1.2.3

### Gradle Version
3.0

**Comment by imochurad** [comment]
I tried combining jar and shadowJar tasks into one as following:

```
shadowJar {
    mergeServiceFiles()
    classifier = null
    zip64 true
    from { configurations.runtime.collect { it.isDirectory() ? it : zipTree(it) } }
    manifest {
        attributes(
        'Main-Class': mainClassName,
        'version': project.version,
        'lastBuild': buildTime()
        )
    }
}
```

And then I've added these 2 lines to my script:
```
jar.enabled = false
startScripts.dependsOn shadowJar
```

But then I get 
```
Could not determine the dependencies of task ':shadowJar'.
> Could not find property 'runtime' on configuration ':runtime'.
```

**Comment by johnrengelman** [comment]
why are you doing this? `from { configurations.runtime.collect { it.isDirectory() ? it : zipTree(it) } }`
That's not needed and doesn't exist in any of the examples in the User Guide.

`assemble` is a lifecycle task, so you can add shadow to it by adding the following line to your build file.
`project.tasks.assemble.dependsOn project.tasks.shadowJar`

**Comment by johnrengelman** [comment]
regarding the error you receive, see the note in section 2.5 of the User Guide. http://imperceptiblethoughts.com/shadow/#configuring_shadowed_dependencies

**Comment by imochurad** [comment]
When I removed that line from the script it works as expected.
Regarding you suggestion 

> assemble is a lifecycle task, so you can add shadow to it by adding the following line to your build file.
> project.tasks.assemble.dependsOn project.tasks.shadowJar

This will be invoking `shadowJar` as the last step before invoking `assemble`.  I want to completely replace `jar` with `shadowJar` in the invocation sequence.

**Comment by johnrengelman** [comment]
The assemble tasks is created and configured by the built-in Java plugin for gradle. There are ways to remove/replace tasks in the task dependency graph but that question would be better suited for the [Gradle Forums](https://discuss.gradle.org/).

alternatively, you could simply write a new task `assemble-shadow` that has the dependencies you want.

**Comment by contradiction154** [comment]
dependencies {
        classpath "com.github.jengelman.gradle.plugins:shadow:$shadowVersion"
        classpath 'de.gesellix:gradle-debian-plugin:14'
    }

apply plugin: 'com.github.johnrengelman.shadow'
shadowVersion=1.1.1

when i try to build this everytime it says stackoverflow error. I am stuck here

**Comment by johnrengelman** [comment]
@contradiction154 please open a new issue with all the details that it requests including your entire build file and the output of Gradle.
