### ISSUE TITLE
Docs are wrong regarding `inheritFrom`

### ISSUE THREAD

**Issue by johnrengelman** [johnrengelman/shadow#251]
`inheritFrom` requires specifying `jar.manifest`
https://github.com/johnrengelman/shadow/blob/5a80aa3aef898511d027d154a9732e55a5851d34/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy#L48

But the docs omit this: https://github.com/johnrengelman/shadow/blob/master/src/docs/asciidoc/10-configuring.adoc

**Comment by melix** [comment]
:+1:
