### ISSUE TITLE
exclude resources in dependency

### ISSUE THREAD

**Issue by abelsromero** [johnrengelman/shadow#252]
The manual states that the exclusion of files can be done using the Jar options which allow to define paths but not the actual library where the file is located. So I assume my case is not covered, or at least not in a simple way.
In my case I have some files repeated in different dependencies and I need to make sure which one is the included.
In Maven I can do something like this no ensure that the proper bindings are included, but not in Gradle.
```
    <filters>
        <filter>
            <artifact>ch.qos.logback:logback-classic</artifact>
            <excludes>
                <exclude>org/slf4j/impl/**</exclude>
            </excludes>
        </filter>
    </filters>
```
Is there an alternative?

### Shadow Version
1.23
### Gradle Version
3.1

**Comment by johnrengelman** [comment]
No, this is not currently possible.

**Comment by abelsromero** [comment]
![baby-crying-450](https://cloud.githubusercontent.com/assets/5781153/18927889/0cb59f22-85be-11e6-9567-daf522792fdb.jpg)

**Comment by johnrengelman** [comment]
I should clarify in that you cannot scope an exclusion to a specific artifact. You can however use the standard `shadowJar.excludes 'org/slf4j/impl/**'` and the will exclude the file. It just will exclude it regardless of which dependency jar provides it.

**Comment by abelsromero** [comment]
> I should clarify in that you cannot scope an exclusion to a specific artifact. You can however use the standard shadowJar.excludes 'org/slf4j/impl/**' and the will exclude the file. It just will exclude it regardless of which dependency jar provides it.

That's the first thing I tried, but then I saw that I was missing some files and the jar did not run. Thing is I am migrating an inherited project from Maven and I imagine I can rework the dependencies to avoid this exclusions. Bu I don't have much time, and I was hoping I could just reproduce the same configuration, it would have been sweet.

If you consider this does not make sense as a possible future feature, feel free to close the issue.

**Comment by johnrengelman** [comment]
The issue is that Gradle doesn't pass the dependency information the same way. 
Seems old that you are adding the adding an slf4j implementation library and then excluding all of the implementation classes from it. can you just exclude the dependency as a whole?

**Comment by abelsromero** [comment]
For indirect dependencies there are several logging frameworks being added and this trick in the shade plugins allows for a quick fix. I guess I'll have to go through all the logging implementation and review it,  but I fear this will become a "nice-to-have" feature that won't be fixed anytime soon due to project priorities.

Thanks a lot for your time.

**Comment by dylanpiergies** [comment]
This would be a really useful feature here, too.

**Comment by johnrengelman** [comment]
@dylanpiergies it's a limitation of the framework the last time I looked.

**Comment by dylanpiergies** [comment]
Do you know of any clean workarounds?

**Comment by dylanpiergies** [comment]
I guess not, otherwise the feature would be easy to implement. :D

**Comment by AHeise** [comment]
I looked into the current gradle version and while it's indeed not possible to set the exclusion by dependency, we could at least add it by jar file name. That's probably enough for most folks.
