### ISSUE TITLE
When classifier is not set `shadowJar.archiveName` returns name without it

### ISSUE THREAD

**Issue by abelsromero** [johnrengelman/shadow#253]
### Shadow Version
1.2.3

### Gradle Version
3.0

### Expected Behavior
`project.tasks.shadowJar.archiveName` should return the name according to Jar specificarion https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar:archiveName

### Actual Behavior
When no classifier is set returns the name without the `[classifier]` component, even when by default the jar is generated with the "all" classifier.
Manually setting the classifier in the shadowJar tasks to `all` fixes the issue.

**Comment by johnrengelman** [comment]
The plugin be default configures the `shadowJar` task with the classifier of  `all`. If you want to whipe out the classifier, then the you should need to add `shadowJar.classifier = ""` to your build file.

Please post your build file and what you are getting as an output (as the issue template asks you to do) if you are getting different behavior.

**Comment by abelsromero** [comment]
Odd, I've been doing many changes to the project and the issue is not happening now. So I guess I was doing something wrong and fixed it accidentally.
project.tasks.shadowJar.archiveName return the full name, classifier included even when none is set.
