### ISSUE TITLE
How do I replace unix/windows start script template?

### ISSUE THREAD

**Issue by grumbler** [johnrengelman/shadow#258]
Application plugin allows to customise start script template - https://docs.gradle.org/current/dsl/org.gradle.jvm.application.tasks.CreateStartScripts.html

I didn't find a way to do the same with shadow+application integration.
Maybe I'm just missing something?

So, this is the source of generator in application plugin - https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCreateStartScripts.groovy

And this one is from shadow - https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCreateStartScripts.groovy

Note, that application generator uses unix/windows generators which may be replaced as shown in the documentation.

How do I do the same thing for shadow+application?

Thanks in advance!

**Comment by johnrengelman** [comment]
Looks like we need to pull in the last source for the `CreateStartScripts` task so that we are in sync. The reason it's duplicated here to is to avoid some classpath issues with common dependencies with Gradle core.

**Comment by Hillkorn** [comment]
I think this one can be closed now.
We tested it with new commits you did and it worked.

Thank you.

**Comment by johnrengelman** [comment]
Yeah, the next version will fix this be getting rid of the custom task class and using Gradle's builtin one.
