### ISSUE TITLE
ClassNotFoundException for relocated Class

### ISSUE THREAD

**Issue by MiniDigger** [johnrengelman/shadow#272]
### Shadow Version
1.2.4
### Gradle Version
3.1
### Expected Behavior
class gets relocated and works fine
### Actual Behavior
class gets relocated but throws ClassNotFoundException
### Gradle Build Script(s)
sub module that does the relocation: https://github.com/MiniDigger/VoxelGamesLib/blob/master/api/build.gradle#L16
parent: https://github.com/MiniDigger/VoxelGamesLib/blob/master/build.gradle
### Content of Shadow JAR
https://gist.github.com/MiniDigger/e5e5e651e7c2e026e57b6e483906f9ff (sorry for the size, don't have time currently to setup a test project....)

onto the description I guess.
I work with a lib (bukkit, framework for developing plugin for minecraft) which shades JPA1.0. since I wanted to try hibernate and that uses JPA2.1, I figured that I need to shade and relocate my own version. so I did that. the problem now is, that, even tho the relocation seems to be successful (can see that in the decompiled class and the raw bytecode), I get a class not found exception for one of the relocated classes: https://gist.github.com/MiniDigger/355f91cba1db0d035346cb3de784c1f1
the exception is raised here https://github.com/MiniDigger/VoxelGamesLib/blob/master/api/src/main/java/me/minidigger/voxelgameslib/api/persistence/HibernatePersistenceProvider.java#L27 (Ignore all the mess I caused while trying to debug it, that exception is not the first while trying to set stuff up...)
I don't see why it is still trying to load the original version. 
a bit more about the setup. as you can see in the stack trace, bukkit comes with its own class loader which loads my bukkit.jar (build by the bukkit module where I basically shade everything in, the content of the class is on that gist), so that could have an effect somehow. 
I am not even sure if this issue is caused by shadow, but I would appreciate every hint I can get to debug this further. 
if we don't get this done till the weekend, I might get time to setup a test project that is a biiit smaller to remove some variables...

**Comment by johnrengelman** [comment]
have you decompiled the `HibernatePersistenceProvider` class and looked at the import statements? The import should be for thew new class location.

**Comment by MiniDigger** [comment]
yes, thats what I meant when saying that the relocation seems to be successful, this is the decompiled class https://gist.github.com/MiniDigger/ad1b8745d27f6d4d84bd52d296d25743
I also inspected the class in a normal editor and couldn't find a reference to the old location, thats why this is so strange

**Comment by johnrengelman** [comment]
What is in the content of the `META-INF/persistence.xml` in your output JAR?

**Comment by johnrengelman** [comment]
I think this has something to do with the `bukkit` library.

See that the error is actually being generated from there:
```
Caused by: java.lang.ClassNotFoundException: javax.persistence.spi.PersistenceProviderResolverHolder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

Might be that it's using some other means of loading classes? I dunno. Not familiar with minecraft stuff.

**Comment by johnrengelman** [comment]
Maybe check the `plugin.yml` file in your JAR?

**Comment by MiniDigger** [comment]
https://gist.github.com/MiniDigger/bbc8bbdebd257dd573d969a17ed3583d

you got me an idea tho. something generates a META-INF/service/javax.persistence.spi.PersistenceProvider file (guess it gets shaded in with JPA or hibernate?). I renamed that to me.minidigger.voxelgameslib.libs.javax.persistence.spi.PersistenceProvider but that didn't help. I also checked the content of that but that doesn't reference any jpa classes too, just one Hibernate class.

that PluginClassLoader is just a URLClassLoader that loads my bukkit.jar from a folder. it loads to plugin.yml from my jar, as that contains the entry point of my plugin. I don't reference any libs in there. 

guess ill have to setup a clean project without bukkit when I have time to test it then...

**Comment by johnrengelman** [comment]
Try adding:
```
shadowJar {
  mergeServiceFiles()
}
```

and see if that makes a difference.

**Comment by MiniDigger** [comment]
that actually renames the file in services, doesn't solve the problem. still the same class not found exception

**Comment by johnrengelman** [comment]
it also combines various service descriptors into a single one.

Anyway, I don't know what would be causing this. I think it's unlikely to be an issue with shadow since the class file itself is being correctly rewritten.

**Comment by MiniDigger** [comment]
ok, thanks for your effort, I will report back in a few days when I can test it in a cleaner environment.

**Comment by MiniDigger** [comment]
turns out this was a weird combination of relocating, bukkits class loading and jrebel, works now.

**Comment by johnrengelman** [comment]
good to hear! Was there a special config you had to do with Shadow? If so, can you post it for reference?

**Comment by MiniDigger** [comment]
I have honestly no idea why it is working now. I didn't change stuff in my build scripts.
