### ISSUE TITLE
How to disable shadow dependencies adding Class-Path?

### ISSUE THREAD

**Issue by Shevchik** [johnrengelman/shadow#274]
Currently shadow dependencies are added to Class-Path and i want to avoid it somehow. They do nothing because the jar is not executable by itself (it's actually a plugin, so shadow dependencies are provided by a platform), but i want to see my manifest clean.

**Comment by rozza** [comment]
I would also like to know if this is possible.  

As I've relocated the shadowed library, its my understanding I don't need it listed in the `MANIFEST.MF`.

**Comment by Shevchik** [comment]
Using compileOnly configuration kinda works. and can be used as workaround.
