### ISSUE TITLE
Shadow should handle new dependencies options in Gradle 3.4

### ISSUE THREAD

**Issue by sc1478** [johnrengelman/shadow#275]
### Shadow Version
1.2.4
### Gradle Version
3.4
### Expected Behavior
dependencies declared with the new "api" configuration should be included in the shadow jar.
### Actual Behavior
dependencies declared with the new "api" configuration are not included in the shadow jar.  They must continue to be declared with the older "compile" configuration to be included.

I am guessing that shadow is not looking for this configuration.

See https://docs.gradle.org/current/userguide/java_library_plugin.html
https://discuss.gradle.org/t/new-java-library-plugin-and-shadowjar/21800/2?u=sc1478

**Comment by oehme** [comment]
The shadow plugin should not be looking for specific `Configuration`s (like `compile`), but use `sourceSet.main.runtimeClasspath`. That way it will always get the correct content, no matter what new `Configuration`s we add in the future.
