### ISSUE TITLE
compilation error using shadow configuration

### ISSUE THREAD

**Issue by IceMan81** [johnrengelman/shadow#277]
Please check the (User Guide)[http://imperceptiblethoughts.com/shadow] before submitting "how do I do 'x'?" questions!
I did and do not see a reason why my script won't work.
### Shadow Version
1.2.4

### Gradle Version
3.4.1

### Expected Behavior
Code compiles without issues when adding a dependency to the shadow configuration

### Actual Behavior
Code does not compile. 

### Gradle Build Script(s)
group 'com.test'
version '1.0-SNAPSHOT'

buildscript {
    dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:1.2.4'
    }
}

apply plugin: 'java'
apply plugin: 'maven-publish'

apply plugin: 'com.github.johnrengelman.shadow'

sourceCompatibility = 1.8

repositories {
    maven { url "http://xxxxxxx:8082/repository/gtr-aggregate-repo" }
    mavenCentral()
}

dependencies {
    shadow "io.projectreactor:reactor-core:3.0.5.RELEASE"
    compile 'net.openhft:chronicle-queue:4.5.15'
    compile 'com.google.guava:guava:19.0'
    compile 'org.eclipse.collections:eclipse-collections:8.0.0'
    compile 'org.eclipse.collections:eclipse-collections-api:8.0.0'
    compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.21'

    testCompile group: 'junit', name: 'junit', version: '4.11'
}

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)

**Comment by johnrengelman** [comment]
Fixed in https://github.com/johnrengelman/shadow/commit/bba0c9cf7a1cc733e05b89d58dde1a0c7a5ceaef#diff-28155880f85b941b00c41303c4c86fcc
