### ISSUE TITLE
Bundling XML files from dependencies' META-INF folder into the shadow JAR's META-INF

### ISSUE THREAD

**Issue by utybo** [johnrengelman/shadow#280]
### Shadow Version
1.2.4
### Gradle Version
3.4.1
### Expected Behavior
The shadowJar command automatically takes every file from the dependencies' META-INF's to add them to the final JAR, merging them on the way.

### Actual Behavior
The files aren't included. Using the example given (here)[http://imperceptiblethoughts.com/shadow/#controlling_jar_content_merging] only gives an error.

```
Could not get unknown property 'XmlAppendingTransformer' for task ':shadowJar' of type com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.
```

**Comment by utybo** [comment]
Nevermind, this was a problem on my side.

**Comment by demersb** [comment]
@utybo - What was the problem on your side?  I am encountering the same problem.
