### ISSUE TITLE
error: archive contains more than 65535 entries

### ISSUE THREAD

**Issue by lahngp** [johnrengelman/shadow#281]
When I apply the shadowJar task, then the "archive contains more than 65535 entries" was raised, I put this information here. Following is the detailed message:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':KanxxxxSystem:shadowJar'.
> org.apache.tools.zip.Zip64RequiredException: archive contains more than 65535 entries.

To build this archive, please enable the zip64 extension.
See: https://docs.gradle.org/3.3/dsl/org.gradle.api.tasks.bundling.Zip.html#org.gradle.api.tasks.bundling.Zip:zip64

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 30.57 secs
archive contains more than 65535 entries.

**Comment by johnrengelman** [comment]
Did you add the `zip64 = true` config to the `shadowJar` task as the error tells you to do?

**Comment by johnrengelman** [comment]
Closing for no response

**Comment by davidghiurco** [comment]
@johnrengelman I just tried to start using your plugin today. I have a multi-module project. I want all jars that are built to bet uber jars. so in the top level build.gradle I put the recommended:
"
shadowJar {zip64=true}
"

when I run gradle shadowJar from the top-level project directory to build my project, I still get the same error: shadow.org.apache.tools.zip.Zip64RequiredException: archive contains more than 65535 entries.

Please advise.

**Comment by sirgl** [comment]
Well, I still got the same issue, probably the issue needs to be reopened

**Comment by davidghiurco** [comment]
Have you properly enabled zip64 for all your gradle modules? This hasn't been an issue for me in literally years.

**Comment by seunggabi** [comment]
### my case 
```kotlin
withType<Jar> {
    enabled = true
    isZip64 = true
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    archiveFileName.set("$project.jar")

    from(
        configurations.compileClasspath.map { config ->
            config.map {
                if (it.isDirectory) {
                    it
                } else {
                    zipTree(it)
                }
            }
        }
    )
}
```
