### ISSUE TITLE
User guide unavailable

### ISSUE THREAD

**Issue by cretz** [johnrengelman/shadow#282]
The user guide hosted on your own site is sending too many redirects. I see gh_pages, but trying to navigate to https://johnrengelman.github.io/shadow starts doing those redirects again. It would be nice if https://johnrengelman.github.io/shadow worked so the uptime of your personal site didn't affect people's ability to learn the software.

**Comment by johnrengelman** [comment]
@cretz thank you for the report. This is fixed now.
The site is completely hosted in GitHub as a static page, there issue here was that somehow GoDaddy messed up some DNS settings. Not sure how that happened since I didn't do it and the account is set to autorenew.
Apologies for the inconvenience.
