### ISSUE TITLE
Avoid use of deprecated Gradle API Manifest.writeTo(Writer)

### ISSUE THREAD

**Issue by eriwen** [johnrengelman/shadow#286]
### Shadow Version: `master`
Shadow currently uses a deprecated API `Manifest.writeTo(Writer)` at https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/DefaultInheritManifest.groovy#L70

### Gradle Version: 4.0
This method has been removed in Gradle 4.0 and so plugin consumers may break.

I hope this will give you sufficient advanced warning to correct this. Gradle 4.0 is tentatively scheduled for May 2017.

**Comment by johnrengelman** [comment]
Thanks @eriwen I'll get this fixed in 2.0.0 which will be out in the next week or so

**Comment by eriwen** [comment]
@johnrengelman brilliant, thanks!

**Comment by johnrengelman** [comment]
@eriwen the issue here is that I'm extending the interface, so while that method is there, I have to provide an implementation for it.

**Comment by johnrengelman** [comment]
Fixed in https://github.com/johnrengelman/shadow/commit/f255b929e419a5b512cde1202943798a977c22c7
