### ISSUE TITLE
Avoid use of deprecated Gradle API (constructor of JavaLibrary)

### ISSUE THREAD

**Issue by bmuschko** [johnrengelman/shadow#287]
### Shadow Version: `master`

Shadow currently uses a deprecated constructor of `JavaLibrary` at https://github.com/johnrengelman/shadow/blob/db81a8eb296b9ec9bde016e2ed7412146bf08fc9/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy#L94

### Gradle Version:

This method may be removed in Gradle 4.0 and so plugin consumers may break.

I hope this will give you sufficient advanced warning to correct this. Gradle 4.0 is tentatively scheduled for May 2017.

**Comment by johnrengelman** [comment]
@bmuschko so, an alternative constructor for this class only appeared in Gradle 3.4 which means I'll lose compatibility to <= 3.3 if I change it.
Is there a public API for adding a component?

**Comment by johnrengelman** [comment]
I tried just copying the `JavaLibrary` code to my own class and having it implement `SoftwareComponent` which is a public API, but the `maven-publish` plugin blows up because it tries to cast it to `SoftwareComponentInternal` - 

```
Cause 1: java.lang.ClassCastException: com.github.jengelman.gradle.plugins.shadow.internal.ShadowJavaLibrary cannot be cast to org.gradle.api.internal.component.SoftwareComponentInternal
        at org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.from(DefaultMavenPublication.java:119)
```

**Comment by johnrengelman** [comment]
And implementing `SoftwareComponentInternal` doesn't work because it requires `org.gradle.api.internal.component.UsageContext` which doesn't exist pre 3.4

**Comment by bmuschko** [comment]
I helped two other projects on a similar issue before. Could you please read through my comments and links [here](https://github.com/gradle/gradle/issues/1361) to see if that helps? Are you only using `SoftwareComponentInternal` because of the `from` method? I made a proposal for the use of a public API [here](https://github.com/palantir/gradle-docker/commit/c553eb684988f46af7879e7d92fb3b7603277320#commitcomment-20934651).

**Comment by johnrengelman** [comment]
I need a way to be able to configure publishing for the shadow JAR easily. This involves publishing a different artifact from the standard JAR and also configuring the proper dependencies. In the case of shadow, dependencies in `configurations.shadow` should be written to the POM as `runtime` dependencies.

This is what I currently provide:
```
publishing {
  publications {
    shadow(MavenPublication) {
      from components.shadow
    }
  }
}
```

**Comment by johnrengelman** [comment]
Also, I'm not using `SoftwareComponentInternal` at all right now. I'm just extending `JavaLibrary` but that is also an internal class. I would use the public `SoftwareComponent` but when implementing my own, it throws an error when trying to configure publishing.

Perhaps there is something I need to do to properly registry my type?

**Comment by johnrengelman** [comment]
@bmuschko yeah - I'm mostly using `SoftwareComponent` so I can use the `from` method on the publication when using `maven-publish`.

I can look at simply using the `project.artifacts` instead, but I guess my question is if `project.componenets` and `SoftwareComponent` are publish APIs, why can't I use them? (They can't be used because anything that implements the public `SoftwareComponent` and is added to `project.components` can't be used in the `publication.from` method because it's coerced into the private `SoftwareComponentInternal`.

That to me seems like a Gradle bug.

**Comment by johnrengelman** [comment]
I can't seem to figure out how to tell Gradle what the dependencies are when using `project.artifacts.add`

**Comment by bmuschko** [comment]
@johnrengelman It's definitely a bit weird not being able to use the `from` method for types that you define yourself. At the moment you can only pass in the ones that are predefined e.g. `compontents.java` or `components.web`. I think we should 1) have better documentation and 2) allow users to define their own component as public API.

I was thinking the following to avoid using the `from` method after all.

1. For your Shadow JAR file you create a dedicated task (which you likely already have).
2. You register that task with the Maven publish plugin using the `artifact` method.
3. In order to include the dependencies you need you simply modify the POM at generation time using `withXml`.

I hope the following pseudo-code makes sense. Let me know what you think. As you can see the code does not include `components.java`.

```
apply plugin: 'java'
apply plugin: 'maven-publish'

group = 'com.company'
version = '1.0'

configurations {
    shadow
}

dependencies {
    shadow 'commons-lang:commons-lang:2.5'
}

repositories {
    mavenCentral()
}

task shadowJar(type: Jar) {
    ...
}

publishing {
    publications {
        shadow(MavenPublication) {
            artifact shadowJar
            pom.withXml {
                def dependenciesNode = asNode().appendNode('dependencies')

                configurations.shadow.allDependencies.each {
                    def dependencyNode = dependenciesNode.appendNode('dependency')
                    dependencyNode.appendNode('groupId', it.group)
                    dependencyNode.appendNode('artifactId', it.name)
                    dependencyNode.appendNode('version', it.version)
                    dependencyNode.appendNode('scope', 'runtime')
                }
            }
        }
    }
    repositories {
        maven {
            url "$buildDir/repo"
        }
    }
}```

**Comment by johnrengelman** [comment]
Fixed in https://github.com/johnrengelman/shadow/commit/f0e3eedd305050822a31b8bfc834fa9d56414a56
