### ISSUE TITLE
new gradle plugin java-library use: 'configurations = project.configurations.runtimeClasspath'

### ISSUE THREAD

**Issue by jessevdam** [johnrengelman/shadow#288]
If one uses the java-library plugin, one must set 'configurations = [project.configurations.runtimeClasspath]' otherwise the resulting jar will not contain any of the files of the dependencies. Either add to the documentation or change the default value of 'configurations'.

### Shadow Version
1.2.4

### Gradle Version
3.4.1

### Expected Behavior
If plugin java-library is used then set
configurations = [project.configurations.runtimeClasspath]
or update the documentation

### Actual Behavior
configurations = [project.configurations.compile]
which is empty if you use the java-library plugin

### Content of Shadow JAR 
None of the dependency classes are included

**Comment by johnrengelman** [comment]
Duplicate of https://github.com/johnrengelman/shadow/pull/284, will be fixed in 2.0.0
