### ISSUE TITLE
How to: Rename a file

### ISSUE THREAD

**Issue by MarcMagnin** [johnrengelman/shadow#293]
### Shadow Version
1.2.3

### Gradle Version
3.3

That should be something simple to do but I haven't found a solution yet: How do you rename a file during the jar creation? It is something required for shading Netty natives libraries.

I've tried some things such as  `rename '/META-INF/native/libnetty-transport-native-epoll.so','/META-INF/native/libshade-netty-transport-native-epoll.so'` without success.
Many thanks for your help.

**Comment by johnrengelman** [comment]
You'd need to provide your own implementation of the `Transformer` interface that can modify the `ZipOutputStream`. Basically you'd capture the file contents in the `transform` method and then write the contents to the desired path in the `modifyOutputStream` method.

**Comment by badabapidas** [comment]
@johnrengelman 
Hi, I am trying out someting the same sort. Shadow plugin dont rename the native libraries automatically for relocate. I can see you suggest something here. Can you please give any snippet to do the same. Here the requirement is same rename the tcnative native libaries to append the relocate path. 

/META-INF/native/libnetty-transport-native-epoll.so' -> /META-INF/native/new_relocate_path_libnetty-transport-native-epoll.so'

Thanks in Advance.

**Comment by davidrabinowitz** [comment]
We have the same issue . It is worth to mention that the shade plugin of both Maven and SBT support renames
