### ISSUE TITLE
The document need fixed the plugin name wrong

### ISSUE THREAD

**Issue by netroby** [johnrengelman/shadow#298]
The plugin name list on document page was wrong.
http://imperceptiblethoughts.com/shadow/

```
plugins {
  id 'com.github.johnrengelman.shadow-plugin' version '2.0.0'
  id 'java'
}
```

the real package name was

```
#https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow

plugins {
  id "com.github.johnrengelman.shadow" version "2.0.0"
}
```

**Comment by johnrengelman** [comment]
There are 2 different plugins. `shadow` is the main plugin that most people will use.
`plugin-shadow` is used to automatically configure certain shadow parameters for gradle plugins.
You are correct in that the documentation is wrong for that particular plugin though but unless you are writing a Gradle plugin (has stated in the docs) you want to be using the main plugin.

**Comment by netroby** [comment]
oh, yes. you are right.

**Comment by netroby** [comment]
But using plugin-shadow, got error
```

* What went wrong:
An exception occurred applying plugin request [id: 'com.github.johnrengelman.plugin-shadow', version: '2.0.0']
> Failed to apply plugin [id 'com.github.johnrengelman.plugin-shadow']
   > Could not get unknown property 'shadowJar' for task set.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

**Comment by netroby** [comment]
And using com.github.johnrengelman.shadow can success run gradle shadowJar

What's cause this ?

**Comment by johnrengelman** [comment]
You'll need to post a sample app that exhibits the problem.
There really isn't a need for anyone to be using `plugin-shadow`. It's a very advanced configuration that will relocate *all* dependencies. This is typically not desired.
However, Shadow itself is built using this plugin, so it does work.
