### ISSUE TITLE
Just no simple way to remove 'Class-Path' attribute in MANIFEST.MF?

### ISSUE THREAD

**Issue by vbnetvbnet** [johnrengelman/shadow#300]
As stated above. We'd like to use this plugin to filter the jars of Apache Flink which already exist in its deployment environment. Because these jars are about 100MB of size. The 'shadow' configuration is so convenient for use, except the auto-generated 'Class-Path' attribute in MANIFEST.MF.

I've found no approach in all your docs. Is not there an easy way to just remove this attribute?

**Comment by vbnetvbnet** [comment]
Or is there any way to overrite this file with my customized one?

**Comment by n0mer** [comment]
@vbnetvbnet have you found the way to customize MANIFEST.MF?
