### ISSUE TITLE
Adding includes results in empty JAR (containing META-INF/MANIFEST.MF only)

### ISSUE THREAD

**Issue by DevJavaVue** [johnrengelman/shadow#301]
Operating system: Windows 10

Shadow Version: 2.0.0 

Gradle Version: 3.5

Expected Behavior:
A file added to final JAR.

Actual Behavior:
Using includes results in META-INF/MANIFEST.MF alone to be packed inside the JAR, missing all the other packages/classes.

Gradle Build Script(s):
```

shadowJar {
    
    include 'resource' // Plain text file.
    
    dependencies {
        exclude(dependency('junit:junit:.*'))
        exclude(dependency('org.quartz-scheduler:.*'))
    }

    manifest {
        attributes 'Main-Class': 'org.test.main.Main'
    }
}

```

Content of Shadow JAR:
META-INF/MANIFEST.MF

Hi,

I just started using Gradle and for final packaging of executable JAR, I choose Shadow plugin.

Everything seems to be working fine (also excluding non-runtime libraries), producing runnable JAR. But when I tried to include another file to JAR using include statement, the resulting JAR is empty, containing META-INF/MANIFEST.MF file only.

This is perhaps unrelated, but exclude don't seem to be working as expected either: when I added `exclude '*.xml'` to exclude XMLs from resulting JAR, they are all packaged anyway.

I already encountered similar (or identical) [issue](https://github.com/johnrengelman/shadow/issues/49), but it seems it resurfaced again.

Thank you for your effort, best regards,

Albert

**Comment by johnrengelman** [comment]
You'll need to add an include for *.jar
This is because currently there includes happen in a 2 pass method. The first pass has to include the dependency jar files so that they are processed by exploding them and looking at the contents.

**Comment by DevJavaVue** [comment]
Hi,

thank you for your reply. Including `*.jar` helps and I'm going to store additional resources inside the `src/main/resources/` folder anyway so they will be automatically packed to final JAR.

Best regards,

Albert

**Comment by centic9** [comment]
Would be good to mention this in the official doc. I also stumbled across this and had to look for quite a while until I found this issue and workaround.
