### ISSUE TITLE
How to package an Apache CXF application into a monolithic JAR with the Gradle “shadowJar” plugin?

### ISSUE THREAD

**Issue by stianlagstad** [johnrengelman/shadow#309]
I'm having [this exact problem](https://stackoverflow.com/questions/6831954/how-to-package-an-apache-cxf-application-into-a-monolithic-jar-with-the-maven-s), only that I'm using Gradle with the shadow plugin. Is there something I can do (similar to the answer in that stackoverflow question) for the gradle plugin to make this work?

(Stackoverflow question for this: https://stackoverflow.com/questions/44941629/how-to-package-an-apache-cxf-application-into-a-monolithic-jar-with-the-gradle)

### Shadow Version
1.2.4

### Gradle Version
2.14.1

### Expected Behavior
SOAP calls using apache cxf should work like it does when the app is run directly from IntelliJ.

### Actual Behavior
I get `org.apache.cxf.service.factory.ServiceConstructionException: Could not resolve a binding for null` when the app (in the fat jar) is doing SOAP calls.

### Gradle Build Script(s)
Using `id "com.github.johnrengelman.shadow" version "1.2.4"` in the plugin block. I'm also depending on an application that I cannot share, but has these dependencies:
```
    provided compile('org.apache.cxf:cxf-rt-frontend-jaxws:3.1.6')
    provided compile('org.apache.cxf:cxf-rt-transports-http:3.1.6')
    provided compile('org.apache.cxf:cxf-rt-ws-security:3.1.6')
```

**Comment by johnrengelman** [comment]
Do you configure `shadowJar` with the `mergeServiceFiles()` option?

**Comment by stianlagstad** [comment]
I had not, and that solved my problem. Thank you very much! :)

**Comment by stianlagstad** [comment]
I've made a test project to reproduce the error here: https://github.com/stianlagstad/mainclass-and-jxf-problems-demo (see the readme).

**Comment by stianlagstad** [comment]
After reading these two and trying a bunch of different things I finally stumbled upon something that works!  
https://stackoverflow.com/questions/6831954/how-to-package-an-apache-cxf-application-into-a-monolithic-jar-with-the-maven-s?noredirect=1&lq=1  
https://discuss.gradle.org/t/how-do-i-use-the-gradle-shadow-plugin-to-merge-spring-handlers-and-spring-schemas-files-of-multiple-spring-jar-dependencies/6713/6  

Using the plugin with this task solved the problem:

```
import com.github.jengelman.gradle.plugins.shadow.transformers.ServiceFileTransformer
shadowJar {
    // Make sure the cxf service files are handled correctly so that the SOAP services work.
    // Ref https://stackoverflow.com/questions/45005287/serviceconstructionexception-when-creating-a-cxf-web-service-client-scalajava
    transform(ServiceFileTransformer) {
        path = 'META-INF/cxf'
        include 'bus-extensions.txt'
    }
}
```

Where can I read more about this to learn _why_ it works?

**Comment by johnrengelman** [comment]
http://imperceptiblethoughts.com/shadow/#controlling_jar_content_merging

`mergeServiceFiles` assumes a default path (`META-INF/services`) for processing files to merge. As you stated above, the CXF files are in `META-INF/cxf`, so you need to add the `ServiceFileTransformer` and configure it to merge that directory.

**Comment by chairbender** [comment]
On apache cxf 2.6.1, this doesn't work for me. Looking at bus-extensions.txt, I see this line after shadowJar processes it:
shadow.org.apache.cxf.ws.policy.PolicyEngineImpl:org.apache.cxf.ws.policy.PolicyEngine:false

Some lines have multiple class names in them, something which the ServiceFileTransformer seems to skip over.

**Comment by petternordholm** [comment]
Hi!

I ran into the same problems as @chairbender . Solved it by using the AppendingTransform to merge all bus-extensions into one big file:
```
import com.github.jengelman.gradle.plugins.shadow.transformers.AppendingTransformer
shadowJar {
  transform(AppendingTransformer) {
    resource = 'META-INF/cxf/bus-extensions.txt'
  }
}
```
