### ISSUE TITLE
[Q] does "from [project]" imply "dependsOn [project]"?

### ISSUE THREAD

**Issue by Lanchon** [johnrengelman/shadow#315]
### Shadow Version
1.2.3
### Gradle Version
2.14.1

hi, quick question...

does "from [project]" imply "dependsOn [project]"?
or is an explicit dependsOn necessary?
sample: https://github.com/DexPatcher/dexpatcher-tool/blob/v1.2.0/tool/build.gradle#L84
(i guess the same is valid fo Jar task etc, but i'm not certain on the answer.)

thank you!

**Comment by johnrengelman** [comment]
that should imply a dependency between the tasks.

**Comment by Lanchon** [comment]
thanks!
