### ISSUE TITLE
How to create self-contained, self-executing jar?

### ISSUE THREAD

**Issue by noel-yap** [johnrengelman/shadow#320]
Please check the (User Guide)[http://imperceptiblethoughts.com/shadow] before submitting "how do I do 'x'?" questions!

### Shadow Version

2.0.1

### Gradle Version

4.1

### Expected Behavior

Some task that will create a self-contained, self-executing jar as per http://en.newinstance.it/2012/04/17/self-executing-jar-files/

### Actual Behavior

I'm not finding one if one exists.

I've hand-crafted the following task to fill this need:

```
task createJarExe(dependsOn: installShadowDist) {
  final outputFile = file("${buildDir}/install/jprotoc-shadow/bin/${project.name}.exe")

  doLast {
    outputFile.text = '#!/bin/bash\n'
    outputFile.append('exec java -jar "$0" "$@"')
    outputFile.append(inputs.files.first().readBytes())
    outputFile.setExecutable(true)
  }

  inputs.files file("${buildDir}/install/${project.name}-shadow/lib/${project.name}-all.jar")
  outputs.file outputFile
  doFirst {
    mkdir outputFile.getParent()
  }
}
```

but I'd prefer using one that already exists.

**Comment by daberkow** [comment]
I use this project to create 1 jar that contains all the dependencies I have. You seem to be making a file that ends in .exe for Windows, but then writes bash commands into the file? By default this project makes 1 jar that any system with Java can execute, could you elaborate on what you are trying to accomplish?

**Comment by noel-yap** [comment]
While it has an `.exe` extension, it's not meant for Windows.

The `protoc` compiler has a hook that allows the caller to provide an executable that `protoc` will call. IOW, the file (with jar contents) itself must be a standalone executable (ie not requiring it to be passed as an argument to a `java` executable).

The task provided above creates such a file. It would be nice if the `shadow` plugin provided such a task OOTB.

**Comment by johnrengelman** [comment]
I’m not interested in providing this support in Shadow. 
I think this would better exist as it’s own plugging the can “exec”-if any JAR

**Comment by noel-yap** [comment]
Fair enough. Thanks for considering it.

**Comment by daberkow** [comment]
I will mention if you set the "Main-class" attribute, then on Windows, and other systems where java automatically handles .jar you get a one click launch of your all. :)

**Comment by noel-yap** [comment]
FWIW, that's not helpful in the `protoc` use case.
