### ISSUE TITLE
SimpleWorkResult is deprecated in gradle 4.2

### ISSUE THREAD

**Issue by gyscos** [johnrengelman/shadow#326]
### Shadow Version
2.0.0, 2.0.1

### Gradle Version
4.2

### Expected Behavior
Clean build.

### Actual Behavior
Gradle prints a deprecation warning:
```
> Task :shadowJar
The SimpleWorkResult type has been deprecated and is scheduled to be removed in Gradle 5.0. Please use WorkResults.didWork() instead.
```

**Comment by karolhor** [comment]
Solution for this fix is really simple. Unfortunately it requires to drop support for Gradle < 4.2

Change needs to be applied in `ShadowCopyAction` class

before:

```groovy
import org.gradle.api.internal.tasks.SimpleWorkResult

@Override
WorkResult execute(CopyActionProcessingStream stream) {
  // ...
  return new SimpleWorkResult(true)
}
```

after:

```groovy
import org.gradle.api.tasks.WorkResults

@Override
WorkResult execute(CopyActionProcessingStream stream) {
  // ...
  return WorkResults.didWork(true)
}
```

**Comment by REPLicated** [comment]
The class `WorkResults` appeared in Gradle 4.2. Version 4.0 has just been released back in June and Shadow itself is currently built using 3.5 as I see.

While I understand and appreciate that things are progressing fast in the gradle world, I would also hope that plugins (and libraries in general) provide a reasonable continuity/backward compatibility. As an example of such an approach, see how Gradle continues to support building with java 7 until version 5.0.

I will create a PR that both avoids this warning and continues to be backward compatible (until Shadow starts to support the future 5.0 version, at which point it will probably be inevitable without hacks).

**Comment by lbergelson** [comment]
That's even better!

**Comment by DuncanCasteleyn** [comment]
I still have this issue.

Gradle version 4.4.1

![afbeelding](https://user-images.githubusercontent.com/10881109/34413704-6651c69e-ebe5-11e7-9a23-059b3b10ba5b.png)

**Comment by johnrengelman** [comment]
@DuncanCasteleyn your error is not the same problem as this issue. Please find an existing open issue that corresponds to this, or open a new one.
