### ISSUE TITLE
Automatic shadowJar call

### ISSUE THREAD

**Issue by lukyer** [johnrengelman/shadow#331]
Hi,
i don't understand why are shadow's tasks executed when i do not explicitly call them? Extended debug log when i call just "gradlew build --debug --stacktrace" (with no configuration for shadow except applying plugin):

`17:54:55.057 [INFO] [org.gradle.internal.buildevents.BuildLogger] Tasks to be executed: [task ':clean', task ':annotationProcessor:clean', task ':annotationProcessor:compileJava', task ':annotationProcessor:processResources', task ':annotationProcessor:classes', task ':annotationProcessor:jar', task ':compileKotlin', task ':compileJava', task ':processResources', task ':classes', task ':jar', task ':startScripts', task ':compileKotlinAfterJava', task ':distTar', task ':distZip', task ':shadowJar', task ':startShadowScripts', task ':shadowDistTar', task ':shadowDistZip', task ':assemble', task ':check', task ':build', task ':annotationProcessor:assemble', task ':annotationProcessor:compileTestJava', task ':annotationProcessor:processTestResources', task ':annotationProcessor:testClasses', task ':annotationProcessor:test', task ':annotationProcessor:check', task ':annotationProcessor:build']`

What could i be doing wrong? I'm using Java9 and 2.0.1 shadow.
Thanks.

**Comment by REPLicated** [comment]
Could you provide your build.gradle file or a working example exhibiting that behavior? Otherwise it's hard to answer.

**Comment by lukyer** [comment]
After more investigation i found out it is caused by Kotlin compilation. I removed all kotlin files, compiler and it started to work again.
