### ISSUE TITLE
Shadow jar task not included in build process

### ISSUE THREAD

**Issue by chjan** [johnrengelman/shadow#335]
Gradle 4.2.1 run by Gradle plugin for Netbeans 8.1, for a pure Java project

This script, the only build.gradle file in this small project, will not include the shadowJar task in the build.

The script builds without error messages of any kind, but the shadowJar task is not included.

Thanks for any hints. (I have read the user manual).

`
buildscript {
    repositories {
        jcenter() 
        dependencies {
           classpath 'com.github.jengelman.gradle.plugins:shadow:2.0.1'
        }
    }
}

plugins {
    id 'java'
    id 'java-library'
    id 'com.github.johnrengelman.shadow' version '2.0.1'
}

repositories {
    mavenCentral()
    jcenter() {
        url "http://jcenter.bintray.com/"
    }

    flatDir { //flatdir searches for .jar files in given directory
        dirs 'libs'
    }
}

sourceCompatibility = '1.8'
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

//to show log for deprecated classes
compileJava {
   // options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
}

version '1.0'

//Create a single JAR including dependencies stated in this build file
shadowJar {
   baseName = 'tmp_HDSL_ClientServer'
   classifier = null
}

`

**Comment by johnrengelman** [comment]
By default shadow doesn't configure the `build` task to depend on the `shadowJar` task.
You can configure this in your own build by adding:

```
tasks.build.dependsOn tasks.shadowJar
```
