### ISSUE TITLE
[newbie] create Groovy libs without embedded groovy

### ISSUE THREAD

**Issue by amiracam** [johnrengelman/shadow#337]
Please check the (User Guide)[http://imperceptiblethoughts.com/shadow] before submitting "how do I do 'x'?" questions!

### Shadow Version
2.0.1
### Gradle Version
4.2
### Expected Behavior
expect ? I would like to create a Groovy lib that does not have Groovy embedded
### Actual Behavior
the fat jar indeed has Groovy embedded

thanks

**Comment by johnrengelman** [comment]
Add your groovy compile dependency to the `shadow` configuration instead of the compile` configuration.
