### ISSUE TITLE
Is there a way to specify transitive dependency for a shadow jar

### ISSUE THREAD

**Issue by zxcware** [johnrengelman/shadow#343]
Hi team,

At the time, if I am correct, a shadow jar is a leaf of the dependency tree. It won't bring further dependency. If it's not correct. How can I specify a transitive dependency, which won't be packaged into the shadow jar but will be brought in when the shadow jar is a dependent.

Thanks,
Zhixiong

**Comment by johnrengelman** [comment]
http://imperceptiblethoughts.com/shadow/#shadow_configuration_and_publishing
