### ISSUE TITLE
shadowJar doesn't run with gradle build

### ISSUE THREAD

**Issue by johnbyers** [johnrengelman/shadow#344]
I followed the "Getting Started" section on the User Guide, and section 1.3 says that in the presence of the 'java' plugin, the shadowJar task will automatically be added to the project. So I figured that running `gradle build` would automatically run the shadowJar task. But it doesn't seem to, the only way I've found to get a "fat jar" is by running `gradle shadowJar` on its own. Is this how it is supposed to be? Or am I misunderstanding?

### Shadow Version 
2.0.1

### Gradle Version 
4.2

### Expected Behavior
Fat jar would be created after running `gradle build`.

### Actual Behavior
Fat jar only created after running `gradle shadowJar`

### Gradle Build Script(s)
    `buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath 'com.github.jengelman.gradle.plugins:shadow:2.0.1'
        }
    }
    
    apply plugin: 'com.github.johnrengelman.shadow'
    apply plugin: 'java'
    
    sourceCompatibility = 1.8
    
    repositories {
        mavenCentral()
    }
    
    dependencies {
        runtime 'net.sourceforge.jtds:jtds:1.3.1'
    }`

**Comment by johnrengelman** [comment]
Correct the `shadowJar` task is added but it is not automatically wired to the `build` task.
You can wire the dependency yourself:
```
tasks.build.dependsOn tasks.shadowJar
```

**Comment by arturbosch** [comment]
Heyho, I want exactly the opposite behaviour. 
In shadow 1.X the shadowJar task was not executed during the build task.
How can I achieve this again? Thanks.
