### ISSUE TITLE
Problem with gradle and expected format

### ISSUE THREAD

**Issue by StasBalia** [johnrengelman/shadow#350]
Hi guys, can someone explain me why i got this error? I can't build my project. Also same error with gradle v.4.3.1. I use oracle java 9.

Error resolving plugin [id: 'com.github.johnrengelman.shadow', version: '2.0.1']
> The response from https://plugins.gradle.org/api/gradle/3.4.1/plugin/use/com.github.johnrengelman.shadow/1.2.3 was not a valid response from a Gradle Plugin Resolution Service: content type is 'text/html', expected 'application/json' (status code: 407)

**Comment by johnrengelman** [comment]
This would be for the Gradle forums, not here.
