### ISSUE TITLE
Compiled module descriptor in shadow-2.0.2.jar

### ISSUE THREAD

**Issue by sormuras** [johnrengelman/shadow#352]
`shadow-2.0.2.jar` contains the `module-info.class` from ASM project. It reports:

- `org.objectweb.asm.commons` (6.0)

as its name to the JPMS. Compiled module desriptors from other artifacts should **not** be present.

`jar --describe-module` reports:
```
org.objectweb.asm.commons@6.0 jar:file:///[...]shadow-2.0.2.jar/!module-info.class open
exports shadow.org.objectweb.asm.commons
requires java.base mandated
requires org.objectweb.asm transitive
requires org.objectweb.asm.tree transitive
```

**Comment by johnrengelman** [comment]
This is a Java 9 thing right?
I'm thinking we need to auto-configure Shadow to exclude `module-info.class` from dependencies.

**Comment by sormuras** [comment]
Sounds reasonable.

**Comment by swankjesse** [comment]
FYI, I tried to use `exclude` to exclude `module-info.class` but it didn’t work. Perhaps class files are special?

```
task shadedJar(type: ShadowJar) {
  classifier = null
  manifest.attributes 'Main-Class': 'com.squareup.exemplar.ExemplarServiceKt'

  from(project.convention.getPlugin(JavaPluginConvention).sourceSets.main.output)
  configurations = [project.configurations.runtime]
  exclude('META-INF/INDEX.LIST', 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA', 'module-info.class')
}
```

**Comment by johnrengelman** [comment]
Hmm, that should work. Theres nothing special about the file types for the exclude filter.

**Comment by johnrengelman** [comment]
Added this in https://github.com/johnrengelman/shadow/commit/275382cef77df1cdce2b2b53568541933fd5d9cd
