### ISSUE TITLE
shadowJar does not create MANIFEST entries for rest-management-private-classpath from ehcache jar file

### ISSUE THREAD

**Issue by sebawagner** [johnrengelman/shadow#354]
Please check the (User Guide)[http://imperceptiblethoughts.com/shadow] before submitting "how do I do 'x'?" questions!

### Shadow Version
1.2.x to 2.0.2(latest)

### Gradle Version
3.4

### Expected Behavior
Should include all classes from dependencies. And it tdoes. But there are some special classpath files in the ehcache directory.
It should create the relevant MANIFEST entries in the fat jar so that you can simply use it same as include in the ehcache.jar in your classpath.

At the moment there is a difference: If you an application manually including ehcache.jar in the classpath it will behave different from shad'ing it. As the classes in rest-management-private-classpath are not loaded into the classpath.

### Actual Behavior
Does not include certain classes from ehcache-2.10.3.jar in the classpath of the fat jar's MANIFEST.MF
Those classes are in the sub-folder of the Jar file called "rest-management-private-classpath"

See for example in ehcache 2.10.0:
http://grepcode.com/file/repo1.maven.org/maven2/net.sf.ehcache/ehcache/2.10.0/net/sf/ehcache/management/resource/CacheManagerEntityV2.java?av=f

### Gradle Build Script(s)
Just the defaults

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
I unpacked the JAR file generated, it definitely does not contain those classes from the rest-management-private-classpath folder of the Jar file.

**Comment by sebawagner** [comment]
My proposal is actuall prone :)

You can't add a classpath resource via the Manifest.MF that is already inside the jar file (see Note section in https://docs.oracle.com/javase/tutorial/deployment/jar/downman.html) 

But this can be fixed by adding the following to the gradle build file:
```
shadowJar.doFirst {
  mergeServiceFiles ('rest-management-private-classpath')
}
```

Cheers
Seb

**Comment by johnrengelman** [comment]
You shouldn’t need the “doFirst” part. Just

shadowJar {
  mergeServiceFiles(...)
}

Should be sufficient

**Comment by sebawagner** [comment]
Cheers John. Yeah I am not quite sure yet how Gradle treats overwriting methods. So I did the doFirst.
