### ISSUE TITLE
How to include another jar in shadow jar?

### ISSUE THREAD

**Issue by Barteks2x** [johnrengelman/shadow#355]
I'm trying to include some other jar files within the shadow jar. It works fine with normal jar task, when done this way:
```
jar {
    into("/") {
        from(embed)
    }
}
```
But when I attempt to do the same for shadowJar, it just includes the contents of those jar files. I know the behavior is described [here](http://imperceptiblethoughts.com/shadow/#embedding_jar_files_inside_your_shadow_jar) but how am I supposed to do that, while also keeping the `.jar` extension after the files being put into the shadow jar?

**Comment by dnault** [comment]
Duplicate of #349 ?

**Comment by Barteks2x** [comment]
Looks like it. I didn't find that issue before.
