### ISSUE TITLE
Enhancement: bundled unixStartScript and jar

### ISSUE THREAD

**Issue by pdeschen** [johnrengelman/shadow#360]
Hi,

Just a small enhancement suggestion we've been using internally: why not offer a bundled unixStartScript and jar into onto one single executable (leveraging a uni* shell behaviour)?

1. From [unixStartScript](https://github.com/johnrengelman/shadow/blob/master/src/main/resources/com/github/jengelman/gradle/plugins/shadow/internal/unixStartScript.txt), change CLASSPATH to point to self

```
CLASSPATH=\$(which "\$0" 2>/dev/null)
```

1. Add a `exit 1` at the end of the `unixStartScript`

1. Concat both the script and the shadow jar into one single file

1. Voila. Fully standalone executable binary.

That could be exposed as a configuration option.

For the record, here is our gradle workaround for it, which is a bit messy:

```groovy
task shellExecutable(type: Copy, dependsOn: 'installShadowDist') {
    description 'Copy executable script and replace classpath variable for self location.'

    from(file("${baseShadowInstallDir}/bin/${project.name}"))
    into(file("${baseShadowInstallDir}/lib/"))
    filter {
        line -> line.replaceAll(/^CLASSPATH=.*$/, 'CLASSPATH=\\$(which "\\$0" 2>/dev/null)')
    }
}

task shellExecutableWithJarPayload(dependsOn: 'shellExecutable') {
    description 'Turn executable script into a standalone one with embedded jar file.'
    doLast {
        def output = new File("$buildDir/${project.name}")
        output.write('') // clear-off
        output << file("${baseShadowInstallDir}/lib/${project.name}").text
        output << '\nexit 1\n'
        output << file("${baseShadowInstallDir}/lib/${project.tasks.shadowJar.archiveName}").bytes
    }
}

// This obviously won't work on Windows.
task changeShellExecutablePermission(dependsOn: 'shellExecutableWithJarPayload') {
    description 'Change shell executable permission.'
    doLast {
        project.exec {
            commandLine('chmod',  '+x', "$buildDir/${project.name}")
        }
    }
}

task release(dependsOn: ['changeShellExecutablePermission']) {
  description 'Create release artifacts.'
}

```

**Comment by johnrengelman** [comment]
this has been asked for before but I'm not interested in including it in Shadow. Thanks for offering up the implementation!
