### ISSUE TITLE
ShadowCopyAction isn't closing input streams

### ISSUE THREAD

**Issue by dbrewster** [johnrengelman/shadow#364]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version
2.0.2
### Gradle Version
4.5
### Expected Behavior
Everyplace the code is calling archive.getInputStream or otherwise opening a stream should be closed.  For example, copyArchiveEntry should close the inputStream from archive.getInputStream as IOUtils.copyLarge does not.

### Actual Behavior
Our build process runs out of file handles while building our shadow jars.

**Comment by johnrengelman** [comment]
I've published 2.0.4-SNAPSHOT with this change, a release should be just a day away.
