### ISSUE TITLE
Provide transformer to merge MANIFEST.MF

### ISSUE THREAD

**Issue by asarkar** [johnrengelman/shadow#369]
### Shadow Version
2.0.3
### Gradle Version
4.6
### Expected Behavior
A transformer that allows for merging MANIFEST.MF, documented here: http://imperceptiblethoughts.com/shadow/#controlling_jar_content_merging
### Actual Behavior
No such transformer available
### Gradle Build Script(s)
N/A
### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
N/A

**Comment by johnrengelman** [comment]
The interface and methods are provided such that you can implement this yourself.
Merging the manifest would require great care in what fields are getting merged vs. overwritten.

**Comment by effad** [comment]
There seems to be a real need for this feature as can be seen here: https://stackoverflow.com/questions/66333597/how-to-merge-manifest-sections-with-gradle-and-shadowjar

**Comment by johnrengelman** [comment]
@effad that’s why the Transformer interface is available. If this is a capability that people need, then it can be implemented via that interface. Pull requests welcome. Or if someone wants to build the implementation and host it as a third party library? I’m happy to include a docs section that references other community plugins to Shadow.
