### ISSUE TITLE
Use of internal Gradle API in DependencyFileCollection

### ISSUE THREAD

**Issue by lptr** [johnrengelman/shadow#370]
### Shadow Version

Present in `master`, tested with `1.2.4`, `2.0.3`.

### Gradle Version

N/A

### Expected Behavior

Shadow plugin should not implement `FileCollection` on its own in `DependencyFileCollection`. Instead of this in `ShadowJar`:

```java
    @InputFiles @Optional
    public FileCollection getIncludedDependencies() {
        return new DependencyFileCollection(dependencyFilter, configurations);
    }
```

...it could do this:

```java
    @InputFiles
    public FileCollection getIncludedDependencies() {
        return getProject().files(new Callable<FileCollection>() {
            @Override
            FileCollection call() {
                return dependencyFilter.resolve(configurations);
            }
        });
    }
```

Note that there's no need for the `@Optional` annotation as this method never returns `null`.

### Actual Behavior

`DependencyFileCollection` extends the internal `AbstractFileCollection` Gradle type. This came to light when removing the `AbstractFileCollection.getBuildDependencies()` method.

**Comment by johnrengelman** [comment]
I've published 2.0.4-SNAPSHOT with this change, a release should be just a day away.

**Comment by lptr** [comment]
Great, thanks! Any chance to fix this for the 1.x line as well?

**Comment by johnrengelman** [comment]
The 1.x line is deprecated. Users should upgrade.
