### ISSUE TITLE
significant performance regression between 2.0.2 and 2.0.3

### ISSUE THREAD

**Issue by lbergelson** [johnrengelman/shadow#374]
### Shadow Version
2.0.3

### Gradle Version
4.6

### Expected Behavior
`./gradlew shadowJar` should take the same amount of time as vs 2.0.2 (~1:30)

### Actual Behavior
./gradlew shadowJar` takes much longer (~4:40)

### Gradle Build Script(s)
using 2.0.3 -> https://gist.github.com/lbergelson/193c0e0d1c60b98ba15743e0e164ab79#file-build-gradle

### Content of Shadow JAR
https://gist.github.com/lbergelson/193c0e0d1c60b98ba15743e0e164ab79#file-shadowcontents2-0-3-txt

If you run the same exact build with 2.0.2 it runs dramatically faster.  The contents of the jars created seem to be the same based on the jar -tf list.  The project is https://github.com/broadinstitute/gatk.  If you want to test it yourself the build instructions are in the readme.  (the only catch is that it requires git-lfs to get some large binaries).

**Comment by johnrengelman** [comment]
Hm. There was an ASM upgrade to 6.1. I wonder if there was a perf regression in that project.

**Comment by johnrengelman** [comment]
Looks related to this - https://gitlab.ow2.org/asm/asm/issues/317816

I’ll publish a snapshot with this new dependency tomorrow and post back here. If you can try it and confirm thto fix, I’ll cut a release.

**Comment by lbergelson** [comment]
I'm happy to test out a snapshot tomorrow.

**Comment by johnrengelman** [comment]
@lbergelson 2.0.4-SNAPSHOT is available for testing. Let me know if it helps and I can cut a release.

**Comment by johnrengelman** [comment]
You’ll need to add a maven repository to your repositories block configured with the following url: http://oss.jfrog.org/artifactory/simple/oss-snapshot-local/

**Comment by cmuchinsky** [comment]
I have tested the 2.0.4-SNAPSHOT version and I'm seeing ~25% better performance than 2.0.3.

**Comment by cmuchinsky** [comment]
I have also verified that the newer ASM version fixes a problem where certain packages (like the ones in the JVM's charsets.jar) could not be relocated successfully, with 2.0.3 the build hangs indefinitely, but with 2.0.4-SNAPSHOT it works fine. Is there an ETA on when a 2.0.4 release with this fix might be cut?

**Comment by lbergelson** [comment]
@johnrengelman Sorry for disappearing.  2.0.4 fixes the problem for me.  Thank you for your help.
