### ISSUE TITLE
Make compatible with Gradle 5.0

### ISSUE THREAD

**Issue by Xerus2000** [johnrengelman/shadow#375]
Gradle warns 

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings
```

when running `gradle shadowJar --warning-mode=all` then it reports this:

```
A problem was found with the configuration of task ':shadowJar'. Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been deprecated and is scheduled to be removed in Gradle 5.0.
 - No value has been specified for property 'mainClassName'.
```

However, `mainClassName` is correctly configured and the resulting jar is completely fine. So this is by now only a warning, but it should be addressed.

**Comment by maikelsteneker** [comment]
See issue #336.

**Comment by johnrengelman** [comment]
Closing as duplicate

**Comment by JamesXNelson** [comment]
The original issue here regarding the warnings is resolved, but now that 5.0-rc-4 is out, there are a couple small incompatibilities.  I have a small patch locally where I just forced everything missing to work, including deleting some code for (much) older versions that referenced a type which no longer exists.

We can certainly abstract around that or just use reflection, but I'd be happy to put up the patch if nobody else has done any work on it yet.

**Comment by johnrengelman** [comment]
@JamesXNelson can you open a new issues for any of the things you are seeing? The simple compatibility check against 5.0-rc-4 isn't showing any errors or warnings.

**Comment by johnrengelman** [comment]
We can also drop support for Gradle 4 once they release 5.0 final. That was my intent when I skipped to 4.0.0 for the most recent version.

**Comment by JamesXNelson** [comment]
Ah, ok.  I was just using `5.0-rc-1..4`, and had a couple compile errors / tweaks needed along the way.

The full set of changes was pretty minor.
https://github.com/JamesXNelson/shadow/pull/new/jxn/gradle_5

The only questionable thing was just commenting out https://github.com/johnrengelman/shadow/compare/master...JamesXNelson:jxn/gradle_5?expand=1#diff-5c6bcc91af73868ad66257c3e51ae8deR36

Could probably still use reflection, or other abstractions to keep supporting older versions, but anybody needing < gradle 4.2 probably isn't much concern for latest shadow version.

**Comment by JamesXNelson** [comment]
I did not create a pull request, but can do so if you find the changes unobjectionable.  Will make a new ticket / PR / etc after you've decided how you'd like it handled.
