### ISSUE TITLE
Include application arguments into a shadowJar

### ISSUE THREAD

**Issue by Xerus2000** [johnrengelman/shadow#377]
Is there a possibility of including application (not jvm) arguments into the jar, so I don't have to use an external script to specify them?

**Comment by johnrengelman** [comment]
No. There are methods to doing this (Google search for "executable JAR"). But this is not a feature I'm going to implement in Shadow.
Shadow is not intended as a method for packing an executable distribution. That is just a side effect of it. Ultimately, the resulting jar still needs to be executed by the JVM.
