### ISSUE TITLE
how to publish the jar without "-all " extension???!! thanks

### ISSUE THREAD

**Issue by lusong1986** [johnrengelman/shadow#378]
I used shadowjar in build.gradle, and found a problem.

My publish config:
"
        publications {

        mavenJava(MavenPublication) { publication ->
            project.shadow.component(publication)

            pom.withXml {
                def dep =
asNode().get("dependencies")[0].appendNode("dependency")
                dep.appendNode("groupId", project.group)
                dep.appendNode("artifactId", project.name)
                dep.appendNode("version", project.version)
                dep.appendNode("scope", "compile")
            }
        }

        }
"

then i got this jar:

kafka-client-1.0.0-SNAPSHOT-all.jar

so how can i remove the "-all" extension and other project can get the jar?

Thanks a lot.

**Comment by lusong1986** [comment]
so how can i remove the "-all" extension and other project can get the jar from maven repository?

**Comment by amdelamar** [comment]
You can remove "-all" classifier by setting it to null, in your build.gradle:

```groovy
shadowJar {
    classifier = null
}
```

**Comment by lusong1986** [comment]
so  how to generate source jar when i publish to maven?
now my publish shell is like this ? thanks


        publications {
		        mavenJava(MavenPublication) {
				 publication ->
				            project.shadow.component(publication)
				
					        pom.withXml {
			                	configurations.compile.allDependencies.each { ModuleDependency dp ->
				                    def dependencyNode = asNode().get("dependencies")[0].appendNode("dependency")
				                    dependencyNode.appendNode('groupId', dp.group)
				                    dependencyNode.appendNode('artifactId', dp.name)
				                    dependencyNode.appendNode('version', dp.version)
				                    dependencyNode.appendNode("scope", "compile")
				                 }
				            }
		        }

**Comment by amdelamar** [comment]
@johnrengelman This is no longer a shadow-plugin question, so I think this issue needs to be closed.

@lusong1986 I think this [Stackoverflow answer](https://stackoverflow.com/questions/11474729/how-to-build-sources-jar-with-gradle) is what you're after.

**Comment by arik-dig** [comment]
> You can remove "-all" classifier by setting it to null, in your build.gradle:
> 
> ```groovy
> shadowJar {
>     classifier = null
> }
> ```

A better way, assuming you need to publish this JAR, set it as empty string

```
shadowJar {
    classifier = ''
}
```
