### ISSUE TITLE
plugin-shadow not published as 2.0.4, only 2.0.3 available

### ISSUE THREAD

**Issue by karottenreibe** [johnrengelman/shadow#381]
It looks like only 2.0.3 of plugin-shadow was published even though the userguide says to use 2.0.4: https://plugins.gradle.org/plugin/com.github.johnrengelman.plugin-shadow

### Shadow Version
2.0.4

### Gradle Version
```
------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Linux 4.15.0-22-generic amd64
```

### Expected Behavior
```groovy
plugins {
  id 'com.github.johnrengelman.plugin-shadow' version '2.0.4'
}
```
Expecting gradle to be able to download the plugin

### Actual Behavior
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/k/proj/eu.cqse.teamscale.jacoco/client/build.gradle' line: 2

* What went wrong:
Plugin [id: 'com.github.johnrengelman.plugin-shadow', version: '2.0.4'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Gradle Central Plugin Repository (plugin 'com.github.johnrengelman.plugin-shadow' has no version '2.0.4' - see https://plugins.gradle.org/plugin/com.github.johnrengelman.plugin-shadow for available versions)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.218 secs
```

### Gradle Build Script(s)
see above

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
not relevant since it's not being produced

**Comment by johnrengelman** [comment]
Are you really wanting the `plugin-shadow` and not the default `shadow` plugin?
The `plugin-shadow` has customizations for very specific things (i.e. packaging Gradle plugins with Shadow).

**Comment by DanielThomas** [comment]
FWIW @johnrengelman I've found the `plugin-shadow` behavior is usually exactly what I want for most cases where we need shading. That is, take the dependencies for a whole configuration and relocate everything.

**Comment by mkobit** [comment]
It was introduced in 3.5 (but I think a little has changed since then) but you could use the `pluginManagement` configuration in your settings to set what artifact it comes from. It might look something like:

```groovy
pluginManagement {
  resolutionStrategy {
      eachPlugin {
          if (requested.id.namespace == 'com.github.johnrengelman.plugin-shadow') {
              useModule("com.github.jengelman.gradle.plugins:shadow:${requested.version}")
          }
      }
  }

}
```

see https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_resolution_rules

**Comment by stewartbryson** [comment]
I wasn’t clear on the answer. Should there be a 2.0.4 of `plugin-shadow`? If not, are there features/fixes in 2.0.4 that are not in `plugin-shadow`?

Thank you.

**Comment by johnrengelman** [comment]
The plugins are released together always. I don't know why Gradle's plugin portal doesn't show it. The binary is available in the bintray repository.
Please keep comments to constructive feedback.

Anyway, when I release the next version, I'll double check that they both show up in the portal.

**Comment by maguro** [comment]
Sorry, I didn't intend my comment to be snarky and apologize if you took it that way.  I often run into projects that do partial publications and, after reading this thread, thought that this project was of that ilk.  Again, I'm very sorry.

With that said, I did notice that if I emulated the way this project is organized, certain metadata files don't get published.  I'll try to dig up my notes on what I discovered.

**Comment by johnrengelman** [comment]
@maguro no worries.

I just released v4.0.0 of Shadow. However I did decide to remove the `plugin-shadow` plugin in favor of the simple `shadow` one. This requires users to declare their own `RelocateShadowConfiguration` task. I feel the duplicate plugins was causing more issues then it was solving for very little gain (since adding the task is a 4 lines in your build file). Please see the release note for v4.0.0 for details: http://imperceptiblethoughts.com/shadow/#change_log

**Comment by maguro** [comment]
Looking at the `build.gradle` file of the project, I don't understand why all that boilerplate Gradle DSL is preferred over having a simple `plugin-shadow` which takes care of all that.

**Comment by johnrengelman** [comment]
Because I found many people were using it incorrectly. And there’s no way in the plugin portal to make the default plugin show up first in searches.

**Comment by maguro** [comment]
I think that may be the source of my disconnect.  Is there any documentation/blog post that details this issue?
