### ISSUE TITLE
Why shadowJar produces binary-different jars 

### ISSUE THREAD

**Issue by Stqs** [johnrengelman/shadow#389]
Hi, 

I make jars and check their md5sum:

### Shadow Version
2.0.4

### Gradle Version
Gradle 4.7

### Expected Behavior
when I create jar 2 times in a row using shadowJar task - produced jars are equal on binary level.

### Actual Behavior
when I create jar 2 times in a row using shadowJar task - produced jars are not equal on binary level.

**Comment by charleskorn** [comment]
I am experiencing this issue as well with this project if you need a repro example: https://github.com/charleskorn/batect

**Comment by johnrengelman** [comment]
Jar file entries have time stamps. The time stamps change this the jars are different.

**Comment by JamesXNelson** [comment]
You can configure Jar tasks to ignore timestamps and use stable file ordering.

```
jar {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}
```
...as mentioned in https://github.com/johnrengelman/shadow/issues/229

I think this is worth a fix.  Even if it's an optional flag, stable jar output is really important when rsyncing fat jars all over the place.

**Comment by Macil** [comment]
@JamesXNelson Since https://github.com/johnrengelman/shadow/pull/391 was merged, the [Gradle-recommended config for making reproducible jars](https://docs.gradle.org/4.8/userguide/working_with_files.html#sec:reproducible_archives) should work with shadow.

**Comment by JamesXNelson** [comment]
Right; sorry, I should have been more clear that it's obvious one would want to apply it to more than just "the default jar task".  Applying it universally like that might be wise for some cases, but it does seem like something that should either be applied by default, or have a simple configuration flag.  Meh.

**Comment by Macil** [comment]
I think it's important to be consistent with what Gradle's documentation recommends if possible. I think it's great that the same config works for making reproducible jars with or without shadow. If Gradle gets a simpler config option for reproducible builds, then shadow should support that too. (If the option is implemented as a shortcut for the currently-recommended config, then shadow won't have to change at all.)

**Comment by johnrengelman** [comment]
What is the actual ask on this ticket now? The `preserveFileTimestamps` option was added in `v4.0.0`. Is the ask to also add the `reproducibleFileOrder`?

**Comment by johnrengelman** [comment]
Agreed. I'm not going to add anything to this beyond passing the proper configuration through to Gradle.
If setting:
```
shadowJar {
  preserveFileTimestamps = false
  reproducibleFileOrder = true
}
```
makes the resulting Jar binary reproducible, then that is the proper path to perform this configuration.
