### ISSUE TITLE
Failed build - Gradle publishing section

### ISSUE THREAD

**Issue by ChrisBNR** [johnrengelman/shadow#397]
### Shadow Version
2.0.4

### Gradle Version
Gradle 4.5.1

### Expected Behavior
Upgraded this plugin from older version to 2.0.4 and now gradle project will not compile. I would expect the project to compile.

### Actual Behavior
Gradle throws the following exception:

```
Exception is:
groovy.lang.MissingPropertyException: Could not get unknown property 'shadow' for SoftwareComponentInternal set of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.
```
Gradle points to line 58 which is the following build script section presented below.

### Gradle Build Script(s)
```
publishing {
    publications {
        shadow(MavenPublication) {
            from components.shadow
            artifactId = 'project-name'
        }
    }
}
```

**Comment by johnrengelman** [comment]
This was a breaking change in v2.0.0 of Shadow. Please read the changelog when updating across major version: http://imperceptiblethoughts.com/shadow/#change_log

**Comment by markwoon** [comment]
Could you please provide more details?  Based on the https://imperceptiblethoughts.com/shadow/changes/#v2-0-0-2017-05-09 I'm using:

```
publishing {
    publications {
        shadow(MavenPublication) {
            from project.shadow.component(MavenPublication)
            artifactId = 'project-name'
        }
    }
}
```

But now I'm getting:

```
> Exception thrown while executing model rule: PublishingPluginRules#publishing(ExtensionContainer)
   > Could not find method component() for arguments [interface org.gradle.api.publish.maven.MavenPublication] on object of type com.github.jengelman.gradle.plugins.shadow.ShadowExtension.
```

I'm trying to go from v1.2.4 to v4.0.4.  I don't see anything that would affect this in the changelog for 4.x either.

**Comment by markwoon** [comment]
StackOverflow to the rescue:

```
publishing {
    publications {
        shadow(MavenPublication) { publication ->
            from project.shadow.component(publication)
            artifactId = 'project-name'
        }
    }
}
```
