### ISSUE TITLE
Issue applying Shadow 4.0.1 in a script plugin on Gradle 4.0

### ISSUE THREAD

**Issue by varrix** [johnrengelman/shadow#407]
Having issues attempting to apply the plugin in a script plugin. Any ideas?

### Shadow Version
4.0.1
### Gradle Version
4.0
### Expected Behavior
I should be able to locate the plugin in the remote repository.
### Actual Behavior
```
FAILURE: Build failed with an exception.

* Where:
Script '/home/<redacted>/repos/<redacted>/vikari-sp/gradle/scripts/shadow.gradle' line: 17

* What went wrong:
A problem occurred evaluating script.
> Plugin with id 'com.github.johnrengelman.shadow' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

CONFIGURE FAILED in 0s
Plugin with id 'com.github.johnrengelman.shadow' not found.
```
### Gradle Build Script(s)
https://gist.github.com/varrix/d667c459a6e7344e2468d8c12534e6ec

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
Not applicable.

**Comment by varrix** [comment]
As it seems, I was un-aware the `buildscript` block cannot be in a script plugin. 

Although before I close this issue, I was wondering if anyone had an alternative? I'll be testing out using the fully-qualified plugin class-name as others seem to have had success with this.

**Comment by johnrengelman** [comment]
This is a questiin better suited for the Gradle forums.
