### ISSUE TITLE
QUERY: How to determine source of mystery folder in shadow jar?

### ISSUE THREAD

**Issue by nheitz** [johnrengelman/shadow#409]
The title gives most of the story.  I have inherited a legacy build that makes use of the latest shadowjar plugin to build.

However, a massive chunk of the jar file (upwards of 20mb) is taken up by useless json schema definitions that I am confident are not needed.  I cannot for the life of me determine the source of this folder in any of the subprojects that are built.

Given that these json files are not easily searchable via gradle dependencyInsight, nor excludable as a dependency, I am struggling to determine their source.  Is there any mechanism in the shadow plugin to audit the shadowing process as it copies files into the final fatjar?

**Comment by johnrengelman** [comment]
They must be embedded inside one of your dependencies. I’d look through the Gradle cache for jars that are larger than 20mb and take a peak in them.
