### ISSUE TITLE
How to exclude Gradle API from shadow jar

### ISSUE THREAD

**Issue by arahlf** [johnrengelman/shadow#414]
### Gradle Version: 4.10.2

On the user guide, under the "Automatically Relocating Dependencies" section, there is an info blurb that mentions:

> Be mindful that some Gradle plugins (such as java-gradle-plugin will automatically add dependencies to your class path (e.g. java-gradle-plugin automatically adds the full Gradle API to your compile configuratinon. You may need to remove these dependencies if you do not intend to shadow them into your library.

How is that meant to be done exactly -- by configuration in the shadowJar closure, or literally removing that plugin dependency?

I'm trying to use the shadowJar on a gradle plugin, and then running a tool called BlackDuck against the resulting jar to monitor the library for open source security issues... but the library's built shadow jar contains the full Gradle API in it, and results in some false positives of sorts in the scan because it ends up scanning a ton of stuff that's not used even transitively by the plugin itself.

**Comment by johnrengelman** [comment]
configurations.compile.dependencies.remove dependencies.gradleApi()

**Comment by arahlf** [comment]
Thanks for the reply.

I tried adding that to my build.gradle, but then that causes the build itself to now fail with with

> * What went wrong:
Execution failed for task ':compileGroovy'.
> Unable to load class <xyz> due to missing dependency org/gradle/api/Project

Is there a way to only have it removed from the shadowJar?

Sorry if these are silly questions, still new to this gradle plugin ecosystem.

Thanks

**Comment by Dkhusainov** [comment]
Full workaround
```
configurations.compile.dependencies.remove dependencies.gradleApi()
dependencies { compileOnly gradleApi() }

```
