### ISSUE TITLE
UnusedTracker produces `path may not be null or empty string. path='null'`

### ISSUE THREAD

**Issue by sormuras** [johnrengelman/shadow#425]
OpenJDK 11, Shadow 4.0.2, Gradle 4.10.2

Full stacktrace at https://scans.gradle.com/s/gubxbmanlcctc/failure?openFailures=WzBd&openStackTraces=WzEse31d#top=0 which contains the line `at com.github.jengelman.gradle.plugins.shadow.internal.UnusedTracker$_getApiJarsFromProject_closure5.doCall(UnusedTracker.groovy:59)`.

**Comment by sormuras** [comment]
Here is the Gradle build file producing the `null` path:

https://github.com/junit-team/junit5/blob/master/junit-jupiter-params/junit-jupiter-params.gradle.kts

**Comment by sormuras** [comment]
Going back to Shadow 4.0.1 solves the problem.

**Comment by fcurts** [comment]
Same here: 4.0.4 doesn't work, 4.0.1 does.

**Comment by marcphilipp** [comment]
@johnrengelman Shall we create a new issue or do you want to reopen this one?

**Comment by gabizou** [comment]
Having just encountered this in a rather complicated multi-project setup, I've found that if in an all projects configuration or similar, having `ParentProjectA` being `api(project(":parentProjectA"))` on `ProjectB`, and in `ProjectB`'s `build.gradle`
```
projectB = this
subprojects {
    dependencies {
        api(projectB)
    }
}
```
will end up causing `:projectB` to have a null path. I'm not 100% positive how specifically that is reproduced or whether that explanation is enough to reproduce the issue, but I'll be commenting back again once I do have a replicatable gradle setup in the next day or two.

**Comment by dealy663** [comment]
I am also having this same problem with my build since I went to Gradle 5.x.

Reverting the shadow plugin back to 4.0.1 seems to have fixed it for now.

**Comment by marcphilipp** [comment]
Could someone create a sample project to reproduce the problem and create a new issue?

**Comment by swankjesse** [comment]
I ran into this on 5.0.

In my multi-project build `UnusedTracker.getApiJarsFromProject()` attempts to get the .jar file for other projects like so:
```
apiJars.add(runtimeConfiguration.find { it.name.endsWith("${dep.name}.jar") } as File)
```

This doesn’t work. In my project `dep.name` is `okhttp` but the jar it’s trying to find ends with `okhttp-3.15-SNAPSHOT.jar`. So the `find()` call returns null. Once null is in `apiJars` that collection is poisoned, and later attempts to access it throw the exception above.

**Comment by sormuras** [comment]
As @swankjesse said, shadow `5.0.0` suffers the same issue. We (JUnit) need to upgrade to `5.0.0` as we need Java 11 support, thus staying on `4.0.1` is no longer an option for us.

@johnrengelman Does the hint Jesse gave help?

**Comment by sormuras** [comment]
Is it possible to disable the `UnusedTracker` via configuration?
