### ISSUE TITLE
Release 4.0.4

### ISSUE THREAD

**Issue by JamesXNelson** [johnrengelman/shadow#436]
I have a build requiring fixes in 4.0.4 I can't release w/out deploying my own copy of jars.  It's certainly possible, but sub-ideal.  If it's not too much trouble, cutting a release in the near future would be appreciated.

**Comment by johnrengelman** [comment]
Hey sorry @JamesXNelson, 4.0.4 is now availble.

**Comment by JamesXNelson** [comment]
No problems; thank you good sir.  I wound up just using a temporary repo, so no worries.  Will happily go click the delete button on it :-)
