### ISSUE TITLE
Build failure with Gradle 5.1

### ISSUE THREAD

**Issue by 3flex** [johnrengelman/shadow#446]
### Shadow Version
https://github.com/johnrengelman/shadow/commit/1f1d2162884388fada70ff5fdd9fa71ada98d17c

### Gradle Version
5.1

### Expected Behavior
A shadow JAR is built.

### Actual Behavior
The JAR is not built - the `shadowJar` task doesn't generate an error, but the JAR is not built. Also see https://github.com/johnrengelman/shadow/pull/445 and https://circleci.com/gh/johnrengelman/shadow/330

### Gradle Build Script(s)
See https://github.com/arturbosch/detekt/pull/1422

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
N/A - jar not being built.

**Comment by devoto13** [comment]
It looks like JAR is actually generated, but with the wrong name: `app-0.11.0.jar` instead of `app-0.11.0-all.jar`.

**Comment by tristanbuckner** [comment]
@devoto13 I have the same problem. The deprecated classifier property can be used as a work around: `shadowJar {
    mergeServiceFiles()
    classifier = "all"
}`

**Comment by nresare** [comment]
I can no longer reproduce this problem in plugins built from latest master (the fix seems to be part of 978d5d0527d6b9e2fa8408efa851372749cf2933) so now it's a simple matter of either building your own or wait for the 5.0.0 release.

**Comment by nresare** [comment]
A slightly less verbose workaround for the issue while waiting for next version would be to add
`shadowJar.archiveClassifier = 'all'` to your build.gradle

**Comment by mkobit** [comment]
I'm guessing this comes from convention mapping mixed with the `archiveClassifier` parts? https://github.com/johnrengelman/shadow/blob/c47b25517ba865b091020126a9bf74e8c406baf3/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy#L44-L51
