### ISSUE TITLE
Doesn't support Gradle 5.1

### ISSUE THREAD

**Issue by Trumeet** [johnrengelman/shadow#447]
### Shadow Version
2.0.1

### Gradle Version
5.1 Milestone 1

### Expected Behavior
It works perfectly without any errors.

### Actual Behavior
When I'm executing `./gradlew :module:shadowJar`, it throws the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Method com/github/jengelman/gradle/plugins/shadow/internal/DependencyFileCollection.getBuildDependencies()Lorg/gradle/api/tasks/TaskDependency; is abstract

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

### Gradle Build Script(s)
```grooxy
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:2.0.1'
    }
}

apply plugin: 'java'
apply plugin: 'com.github.johnrengelman.shadow'

group 'moe.yuuta'
version '1.0'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile "io.vertx:vertx-core:$vertxVersion"
    compile "io.vertx:vertx-web:$vertxVersion"
    compile "io.vertx:vertx-web-client:$vertxVersion"
    compile project(':common')
    testCompile("junit:junit:4.12")
    testCompile "io.vertx:vertx-unit:$vertxVersion"
    testCompile "org.mockito:mockito-core:2.23.4"
    testCompile "org.powermock:powermock-module-junit4:2.0.0-RC.1"
    testCompile "org.powermock:powermock-api-mockito2:2.0.0-RC.1"
}

shadowJar {
    baseName "server"
}
```

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
Sorry, it doesn't generate anything.

I'm waiting for your response :disappointed:

**Comment by adrian-baker** [comment]
2.0.1 is about 18 months old, try the latest version.

**Comment by Trumeet** [comment]
@adrian-baker Sorry, my bad :cry:, I'll try it later and give feedbacks.

**Comment by Trumeet** [comment]
Good news, I've updated my plugin to `4.0.3`, it works! :100:

**Comment by luoxiong94** [comment]
> ### 暗影版
> 2.0.1
> 
> ### 摇篮版本
> 5.1里程碑1
> 
> ### 预期行为
> 它完美地工作，没有任何错误。
> 
> ### 实际行为
> 当我执行时`./gradlew :module:shadowJar`，它引发以下错误：
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Method com/github/jengelman/gradle/plugins/shadow/internal/DependencyFileCollection.getBuildDependencies()Lorg/gradle/api/tasks/TaskDependency; is abstract
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 0s
> ```
> 
> ### Gradle构建脚本
> ```
> buildscript {
>     repositories {
>         jcenter()
>         mavenCentral()
>     }
>     dependencies {
>         classpath 'com.github.jengelman.gradle.plugins:shadow:2.0.1'
>     }
> }
> 
> apply plugin: 'java'
> apply plugin: 'com.github.johnrengelman.shadow'
> 
> group 'moe.yuuta'
> version '1.0'
> 
> sourceCompatibility = 1.8
> 
> repositories {
>     mavenCentral()
> }
> 
> dependencies {
>     testCompile group: 'junit', name: 'junit', version: '4.12'
>     compile "io.vertx:vertx-core:$vertxVersion"
>     compile "io.vertx:vertx-web:$vertxVersion"
>     compile "io.vertx:vertx-web-client:$vertxVersion"
>     compile project(':common')
>     testCompile("junit:junit:4.12")
>     testCompile "io.vertx:vertx-unit:$vertxVersion"
>     testCompile "org.mockito:mockito-core:2.23.4"
>     testCompile "org.powermock:powermock-module-junit4:2.0.0-RC.1"
>     testCompile "org.powermock:powermock-api-mockito2:2.0.0-RC.1"
> }
> 
> shadowJar {
>     baseName "server"
> }
> ```
> 
> ### Shadow JAR的内容（`jar tf <jar file>`如果太长，则发布至GIST的链接）
> 抱歉，它什么都不会产生。
> 
> 我正在等待您的回复 😞

I also encountered the same problem as you, can't run.
