### ISSUE TITLE
shadowJar classifier not set in gradle 5.1

### ISSUE THREAD

**Issue by dansanduleac** [johnrengelman/shadow#450]
After upgrading a repo to gradle 5.1, the classifier is no longer set, thus the `shadowJar` task overwrites the output of the `jar` task.

I suspect this code stopped working properly:

https://github.com/johnrengelman/shadow/blob/d7af1d3bdd1a9cfdc26de8290deea1b1cce90084/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy#L43-L47

Convention mappings are obsolete in gradle 4, so since the latest major version of the plugin supports only gradle 4, we should move away from configuring things in that way.

**Comment by klesniewski** [comment]
The same problem as described here: https://github.com/johnrengelman/shadow/issues/446
Solution is already on master, but not yet released.

**Comment by OdysseusLives** [comment]
We'd love to use the commited solution. Can you release a new version containing https://github.com/johnrengelman/shadow/commit/978d5d0527d6b9e2fa8408efa851372749cf2933 ?
