### ISSUE TITLE
installShadowDist bash script removes quotes from command arguments

### ISSUE THREAD

**Issue by kyrrigle** [johnrengelman/shadow#453]
### Shadow Version
4.0.4

### Gradle Version
4.10.2

### Expected Behavior
Running cmd` '{"foo": "bar"}'` will pass the argument with quotation marks to the java program
 
### Actual Behavior
The quotes are being removed by the "Escape application args" section of unixStartScript.txt and the java program gets only `{foo: bar}`.

```
$ gradle installShadowDist

BUILD SUCCESSFUL in 0s
4 actionable tasks: 4 executed
$ ./build/install/shadow-bug-shadow/bin/shadow-bug '{"foo": "bar"}'
ARG [{foo: bar}]
```

### Gradle Build Script(s)

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:4.0.4'
    }
}

apply plugin: 'application'
apply plugin: 'java'
apply plugin: 'com.github.johnrengelman.shadow'

version = '1.0-SNAPSHOT'
mainClassName = 'kyrrigle.Main'

description = """Shadown bug report"""

sourceCompatibility = 1.8
targetCompatibility = 1.8

shadowJar {
    mergeServiceFiles()
}
jar {
    manifest {
        attributes 'Main-Class': mainClassName
        attributes 'Implementation-Title':   description
        attributes 'Implementation-Version': version
    }
}

repositories {
    jcenter()
}

```

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)

```
$ jar tf ./build/install/shadow-bug-shadow/lib/shadow-bug-1.0-SNAPSHOT-all.jar
META-INF/
META-INF/MANIFEST.MF
kyrrigle/
kyrrigle/Main.class
```

[shadow-bug.tar.gz](https://github.com/johnrengelman/shadow/files/2809364/shadow-bug.tar.gz)

**Comment by RichardMarbach** [comment]
I ran into the same problem, when I added shadow to my application project. It seems the unix start script in the application plugin has fixed this issue, so I've incorporated their fixes in #455
