### ISSUE TITLE
Removing the default classifier with the archiveClassifier property

### ISSUE THREAD

**Issue by bmuschko** [johnrengelman/shadow#463]
### Shadow Version

5.0.0

### Gradle Version

5.2.1

### Expected Behavior

Default classifier set by `ShadowJar` task can be removed from a build script.

### Actual Behavior

I can only remove the `-all` classifier via the following code (which is deprecated):

```
tasks.named<ShadowJar>("shadowJar") {
    classifier = null
}
```

I was out of luck using the `archiveClassifier` attribute e.g. via the following code:

```
tasks.named<ShadowJar>("shadowJar") {
    archiveClassifier.set("")
}
```

The `-all` classifier is still added to the archive. Can you give an example on how to remove the `-all` classifier with the `archiveClassifier` property?

I see that the [relevant code](https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy#L44-L51) sets the classifier via convention mapping and the new attribute `archiveClassifier`. Should the convention mapping code go into an `else` branch to only kick in when you are using an older Gradle version than 5.2?

**Comment by silmeth** [comment]
I encountered similar problem – only we try to set a different classifier, not get rid of it. In Kotlin DSL the deprecated method works:

```kotlin
tasks.getByName<ShadowJar>("shadowJar") {
    classifier = "uber"
}
```

but when trying to set the property through the new getter:
```kotlin
tasks.getByName<ShadowJar>("shadowJar") {
    archiveClassifier.set("uber")
}
```
the created jar has `-uber.jar` in the name, but `uploadShadow` task still uploads it as `-all.jar`. Changing the config to:
```kotlin
tasks.getByName<ShadowJar>("shadowJar") {
    archiveClassifier.set("uber")

    conventionMapping.apply {
        map("classifier") {
            "uber"
        }
    }
}
```
fixes it.

**Comment by chrisr3** [comment]
Interesting, I just encountered a problem that looks a lot like this in Gradle 5.5, and I was wondering if maybe the solution was to change [these lines](https://github.com/johnrengelman/shadow/blob/bce1bae574b208c4aeb005c53675145b75f1dcb7/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy#L50) to use `convention()` instead of `set()`:
```groovy
        if (GradleVersion.current() >= GradleVersion.version("5.1")) {
            shadow.archiveClassifier.convention("all")
        }
```

**Comment by AceHack** [comment]
please fix
