### ISSUE TITLE
Creating fat jar with Bouncy Castle

### ISSUE THREAD

**Issue by dilan85desilva** [johnrengelman/shadow#489]
My question is the same as issue #227 
It's a bit unclear on if it's possible to make bouncycastle like crypto libs as an external dependency to the fat jar.
The convo in issue #227  seems to be incomplete somehow regarding this fact ?
I tried many different ways of configuring shadow dependencies with no luck.
The doco here : https://imperceptiblethoughts.com/shadow/configuration/#configuring-the-runtime-classpath seems to explain exactly what i want but was unable to get it going as the BC dependency always ended up in the final jar.

**Comment by eonwhite** [comment]
I was also a little confused by the documentation and #227, and spent a couple hours googling around to figure this out. Here's what ultimately worked for me.

(1) As noted in #227, you need to ensure that the crypto libs do not accidentally wind up anywhere in your fat jar. Use `gradle dependencies` to check this. I was using the `name.neuhalfen.projects.crypto.bouncycastle.openpgp:bouncy-gpg` library, which has dependencies on `bcprov-jdk15on` and `bcpg-jdk15on`, so I had to explicitly exclude them like so:

```
dependencies {
    ...
    compile('name.neuhalfen.projects.crypto.bouncycastle.openpgp:bouncy-gpg:2.+') {
        exclude(module: 'bcprov-jdk15on')
        exclude(module: 'bcpg-jdk15on')
    }
```

(2) When you include the `bcprov-jdk15on` and `bcpg-jdk15on` libs, you want to do so as a `shadow` dependency, which will tell shadow not to include them in the fat jar, like so:

```
dependencies {
    ...
    shadow 'org.bouncycastle:bcprov-jdk15on:1.60'
    shadow 'org.bouncycastle:bcpg-jdk15on:1.60'
```

(3) shadow will automatically set up the manifest's Class-Path for you to load those two jars as external dependencies. But it doesn't take care of actually installing those jars -- you're on your own for that. But it *does* add any shadow jars to `configurations.shadow`. So I added a gradle task to copy them into the target build folder, like so:

```
task copyShadowLibs(type: Copy) {
    from configurations.shadow
    into 'build/libs'
}
```

And ensure this task will always run alongside my `shadowJar` task:
```
shadowJar {
  ...
}
shadowJar.dependsOn(copyShadowLibs)
```

Hope the above helps!

**Comment by dilan85desilva** [comment]
Thanks @eonwhite, will give this a go 👍

**Comment by dilan85desilva** [comment]
@eonwhite this worked as expected !
Thanks heaps for taking the time to write up the detailed answer 👍

**Comment by dilan85desilva** [comment]
PS :
The unit tests in the jar started failing after shadowing the bouncy castle jars, so I had to do a conditional dependency for the shadowJar command vs other commands like 

`    if (project.hasProperty("shadow")) {
        compile(project(":common.sec")) {
            exclude group: "org.bouncycastle", module: "bcprov-jdk15on"
            exclude group: "org.bouncycastle", module: "bcpg-jdk15on"
        }
    shadow 'org.bouncycastle:bcprov-jdk15on:1.X'
    shadow 'org.bouncycastle:bcpg-jdk15on:1X'
    } else {
        compile project(":common.sec")
    }`

common.sec is the module that has the bouncy castle dependencies.
