### ISSUE TITLE
mergeGroovyExtensionModules() not working with multiple extension modules for groovy 2.5+

### ISSUE THREAD

**Issue by cebbec** [johnrengelman/shadow#490]
### Shadow Version
5.0.0 (currently latest)
### Gradle Version
5.1.1
### Groovy version
2.5.7 (same issue with 3.0.0-beta-1) (currently latest)
### Expected Behavior
While using Date.parse(String, String) or LocalDateTime(String, String) which are defined in extension classes, the shadow jar should be able to get the extension function.
### Actual Behavior
When running without shadow, no problem.
With runShadow :
groovy.lang.MissingMethodException: No signature of method: static java.time.LocalDateTime.parse() 
or 
groovy.lang.MissingMethodException: No signature of method: static java.util.Date.parse() 

### Gradle Build Script(s)
dependencies {
    implementation 'org.codehaus.groovy:groovy:2.5.7'
    implementation 'org.codehaus.groovy:groovy-dateutil:2.5.7'
    implementation 'org.codehaus.groovy:groovy-datetime:2.5.7'
}
[...]
shadowJar {
    mergeGroovyExtensionModules()
}
### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
The META-INF/groovy/org.codehaus.groovy.runtime.ExtensionModule file only contains one extension module reference :

moduleName=groovy-dateutil
moduleVersion=2.5.7
extensionClasses=org.apache.groovy.dateutil.extensions.DateUtilExtensions
staticExtensionClasses=org.apache.groovy.dateutil.extensions.DateUtilStaticExtensions

The file should contain all merged extensions classes (comma separated) : http://docs.groovy-lang.org/latest/html/documentation/#module-descriptor

**Comment by cebbec** [comment]
So manually editing the META-INF/groovy/org.codehaus.groovy.runtime.ExtensionModule file work.

Example with 3 extension modules.

moduleName=groovy-extensions
moduleVersion=2.5.7
extensionClasses=org.apache.groovy.sql.extensions.SqlExtensions,org.apache.groovy.dateutil.extensions.DateUtilExtensions,org.apache.groovy.datetime.extensions.DateTimeStaticExtensions
staticExtensionClasses=org.apache.groovy.dateutil.extensions.DateUtilStaticExtensions,org.apache.groovy.datetime.extensions.DateTimeStaticExtensions

**Comment by cebbec** [comment]
The org.codehaus.groovy.runtime.ExtensionModule file was in META-INF/services/ in groovy 2.4, in 2.5+ and 3.0+ it is in META-INF/groovy/ now. 

Looking at GroovyExtensionModuleTransformer.groovy, it only process the old path.

**Comment by rdoepke** [comment]
Same issue for me. Having just a small project I was able to rewrite my code. But looking forward for a workaround/fix.

**Comment by johnrengelman** [comment]
You can add the Groovy extension transformer manually and specify a different path for it to merge.

**Comment by augusteiner** [comment]
There is any info on how to do that. Same problem here.

**Comment by zman0900** [comment]
Since the path is hard-coded into a static variable, I had to copy the whole GroovyExtensionModuleTransformer class into my buildSrc, modify the string, and use that one instead.  I'm not seeing any way to override it in the class this plugin provides.

**Comment by gtiwari333** [comment]
I ran into similar situations and did the following fix as suggested by @zman0900 


**Skeleton of project with buildSrc**
```
├── build.gradle   //root project
├── buildSrc        //add this 
│   ├── build.gradle
│   └── src
│       └── main
│           └── groovy
│               └── com.github.jengelman.gradle.plugins.shadow.transformers
│                                           └── MyGroovyExtensionModuleTransformer.groovy
├── submodule-that-uses-shadowJar   //sub module
│   ├── build.gradle

```


### Contents:

**build.gradle inside buildSrc**
```
apply plugin: 'groovy'

repositories {
    mavenCentral()
    maven {
        url "https://plugins.gradle.org/m2/"
    }
}

dependencies {
    implementation gradleApi()
    implementation 'com.github.jengelman.gradle.plugins:shadow:6.1.0'
    implementation "org.codehaus.plexus:plexus-utils:3.3.0"
}
```


**MyGroovyExtensionModuleTransformer.groovy**

```
import org.codehaus.plexus.util.IOUtil
import org.gradle.api.file.FileTreeElement
import shadow.org.apache.tools.zip.ZipEntry
import shadow.org.apache.tools.zip.ZipOutputStream

@CacheableTransformer
class MyGroovyExtensionModuleTransformer implements Transformer {

    private static final GROOVY_EXTENSION_MODULE_DESCRIPTOR_PATH =
            "META-INF/groovy/org.codehaus.groovy.runtime.ExtensionModule"
```


**build.gradle inside the `submodule-that-uses-shadowJar`**
```

import com.github.jengelman.gradle.plugins.shadow.transformers.*

shadowJar {
    ...
    transform(MyGroovyExtensionModuleTransformer)
    ...
}
```

**Comment by jafarre-viewnext** [comment]
I hit the same problem. I have problems to use the extension modules that come with Groovy itself. Any plans to fix this? Thank you!

**Comment by ssadedin** [comment]
Based on @gtiwari333's solution,I was able to find a way to achieve this entirely inline within the build.gradle file. It comes to the same thing but just saves setting up all the extra build files, buildSrc etc etc.

So you can extend the original transformer class from within the build script itself and then use that. In which case, the whole solution is just to insert it as below:

```groovy
import com.github.jengelman.gradle.plugins.shadow.transformers.*
@groovy.transform.CompileStatic
@CacheableTransformer
class FixedGroovyExtensionModuleTransformer extends GroovyExtensionModuleTransformer {

	private static final String GROOVY_EXTENSION_MODULE_DESCRIPTOR_PATH =
			"META-INF/groovy/org.codehaus.groovy.runtime.ExtensionModule"

	private final Properties module = new Properties()

	@Override
	boolean canTransformResource(FileTreeElement element) {
		return element.relativePath.pathString == GROOVY_EXTENSION_MODULE_DESCRIPTOR_PATH
	}

	private handle(String key, String value, Closure mergeValue) {
		def existingValue = module.getProperty(key)
		if (existingValue) {
			mergeValue(existingValue)
		} else {
			module.setProperty(key, value)
		}
	}

	@Override
	boolean hasTransformedResource() {
		return module.size() > 0
	}

	@Override
	void modifyOutputStream(shadow.org.apache.tools.zip.ZipOutputStream os, boolean preserveFileTimestamps) {
		shadow.org.apache.tools.zip.ZipEntry entry = new shadow.org.apache.tools.zip.ZipEntry(GROOVY_EXTENSION_MODULE_DESCRIPTOR_PATH)
		entry.time = TransformerContext.getEntryTimestamp(preserveFileTimestamps, entry.time)
		os.putNextEntry(entry)
		module.store(os, null)
		os.closeEntry()
	}
}

shadowJar {
	transform(FixedGroovyExtensionModuleTransformer)
}
```
