### ISSUE TITLE
gradle 4.0 and java7 only. Still valid?

### ISSUE THREAD

**Issue by guenhter** [johnrengelman/shadow#497]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version
5.0.0

### Gradle Version
5.4.1

Is the documentation about gradle 4.0 and java 7 as supported versions only still valid?

**Comment by johnrengelman** [comment]
Fixed in the readme.
