### ISSUE TITLE
Doesn´t compile in Java 13 with Gradle 6 snapshot

### ISSUE THREAD

**Issue by jabrena** [johnrengelman/shadow#511]
I am compiling an example in Java 13 with latest Gradle plugin:
https://services.gradle.org/distributions-snapshots/gradle-6.0-20190821220044+0000-all.zip

But the plugin is not able to generate the fatJar.

```
* What went wrong:
Execution failed for task ':shadowJar'.
> Unsupported class file major version 57
```

Any help?

Juan Antonio

**Comment by anthraxx** [comment]
@johnrengelman can we get this fixed? Its most likely an `asm`/`cglib` or groovy dependency that needs a bump?

**Comment by mjpt777** [comment]
This still does not work with Gradle 6.1.

**Comment by davinchia** [comment]
@mjpt777 upgrading to `5.2.0` worked for me with `Gradle 6.0`. Give that a shot?

**Comment by mjpt777** [comment]
@davinchia That, unfortunately, does not work if you want to use `relocate`.

**Comment by lusu007** [comment]
Is a release planned for version 6.0?
A the moment shadow is unusable with Java 14 and 13.
