### ISSUE TITLE
Embedded unix start script does not make use of "optsEnvironmentVar"

### ISSUE THREAD

**Issue by sfitts** [johnrengelman/shadow#518]
### Shadow Version

5.1.0

### Gradle Version

5.6.2

### Expected Behavior

Both the previously customized version of `unixStartScript.txt` (in version 4.0.3) and the current default version of the script provided by Gradle add the environment variable defined by `optsEnvironmentVar` to the command line.

### Actual Behavior

The current version of the script no longer adds this environment variable to the command line used.

### Gradle Build Script(s)

Here is the relevant line from the Gradle version of `unixStartScript.txt` (line 181):

```
eval set -- \$DEFAULT_JVM_OPTS \$JAVA_OPTS \$${optsEnvironmentVar} <% if ( appNameSystemProperty ) { %>"\"-D${appNameSystemProperty}=\$APP_BASE_NAME\"" <% } %>-classpath "\"\$CLASSPATH\"" ${mainClassName} "\$APP_ARGS"
```

Here is what is in the same file from the plugin: (line 165):

```
eval set -- "\$DEFAULT_JVM_OPTS" "\$JAVA_OPTS" "\$GRADLE_OPTS" <% if ( appNameSystemProperty ) { %>"\"-D${appNameSystemProperty}=\$APP_BASE_NAME\"" <% } %>-jar "\"\$CLASSPATH\"" "\$APP_ARGS"
```

Note that `GRADLE_OPTS` appears in the place of `optsEnvironmentVar`.

This breaks startup of applications that relied on the ability to define the now missing environment variable.

**Comment by jnagels** [comment]
+1

**Comment by woutersmet** [comment]
For completeness / any others finding this / https://xkcd.com/979/ scennarios: the workaround we did for this issue was to move relevant environment vars over to the GRADLE_OPS env var.
