### ISSUE TITLE
Shadow cannot create an archive that contains more than 65535 entries

### ISSUE THREAD

**Issue by TMLWinston** [johnrengelman/shadow#548]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version
5.2.0
### Gradle Version
5.2.1
### Expected Behavior
using the shadowJar target will generate a Jar file.

### Actual Behavior
Gradle build error:  
shadow.org.apache.tools.zip.Zip64RequiredException: archive contains more than 65535 entries
### Gradle Build Script(s)
The build scripts pull in third party products I cannot share.  
### Additional Information:
This has been encountered by us with normal gradle jar operations.  The issue is the 32 zip system has a limit.  The solution is to add "zip64 true" to the creation of the jar target.

**Comment by sergeykad** [comment]
It is the standard Gradle configuration. Just use:
```Groovy
shadowJar {
    zip64 = true
}
```
