### ISSUE TITLE
Multiple jars from shadowJar task

### ISSUE THREAD

**Issue by jumpingfella** [johnrengelman/shadow#552]
Hello,
I'm looking for a way to produce multiple jars with different names from shadowJar task, is this possible?
Right now I'm producing 1 with archiveName. 
After that I have to resort to shell scripting, which is not that trivial in my case and I would rather avoid it.
Regards, Stepan.

**Comment by serega100** [comment]
Look at [this build.gradle](https://github.com/hoqhuuep/IslandCraft/blob/develop/build.gradle). It should help you.
(Use compileOnly to provide libs. It's better then exclude the groups)

**Comment by johnrengelman** [comment]
This is not a feature that I would implement as it would differ from gradle behavior. Shadow is a Jar task which outputs 1 Jar.
You can create multiple tasks of the `ShadowJar` type for different outputs.
