### ISSUE TITLE
Merge and include META-INF/jars/* from dependencies

### ISSUE THREAD

**Issue by martmists** [johnrengelman/shadow#573]
### Shadow Version

5.2.0

### Gradle Version

6.3

### Expected Behavior

Shadow merges `META-INF/jars` of shadowed dependencies

### Actual Behavior

Jars included by other projects are ignored, and when `include '*.jar'` is added to the shadowJar closure the jar is empty aside from a manifest file.

### Gradle Build Script(s)

<details><summary>build.gradle</summary>

    plugins {
        id 'java'
        id 'maven-publish'
        id 'net.minecrell.licenser' version "$licenser"
        id 'fabric-loom' version "$fabric_loom" apply false
        id 'org.jetbrains.kotlin.jvm' version "$kotlin"
        id "com.github.johnrengelman.shadow" version "5.2.0"
        id 'com.matthewprenger.cursegradle' version '1.4.0'
    }

    apply from: "dependencies.gradle"  // libs.*

    logger.lifecycle("""
        =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
        Building Essentials
        Version: $project.mod_version
        Minecraft Version: $project.minecraft
        Fabric-Loader Version: $project.fabric_loader
    
        Using:
        Fabric-API Version: $project.fabric_api
        PlayerAbilityLib Version: $project.playerabilitylib
        
        Output files will be in /build/libs
        =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    """)

    version = project.mod_version + "+" + project.minecraft

    // Project config

    allprojects { currentProject ->
        apply plugin: 'fabric-loom'
        apply plugin: 'maven-publish'
        apply plugin: 'org.jetbrains.kotlin.jvm'
        apply plugin: 'net.minecrell.licenser'
        apply plugin: 'com.github.johnrengelman.shadow'

        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8

        group = "io.github.nyliummc.essentials"
        version = project.mod_version + "+" + project.minecraft

        setBuildDir(rootProject.getBuildDir())

        configurations {
            dev
            compile.extendsFrom shade
            modCompile.extendsFrom modShade
        }

        license {
            header = rootProject.file('LICENSE')
            include '**/*.java'
            include '**/*.kt'
            style.java = 'BLOCK_COMMENT'
            style.kt = 'BLOCK_COMMENT'
        }

        repositories {
            mavenCentral()
            jcenter()
            maven {
                name = "Jitpack"
                url = "https://jitpack.io"
            }
            maven {
                name = "Ladysnake Libs"
                url = "https://dl.bintray.com/ladysnake/libs"
            }
        }

        dependencies {
            // Kotlin Stdlib
            compileOnly libs.kotlin_stdlib

            minecraft(libs.minecraft) {
                transitive = false
            }
            mappings libs.yarn
            modImplementation libs.fabric_loader

            // Hard Dependencies
            modImplementation libs.fabric_api
            modImplementation libs.fabric_language_kotlin

            // Database
            implementation libs.exposed_core
            implementation libs.exposed_jdbc
            implementation libs.exposed_java_time

            // Database drivers
            implementation libs.postgresql
            implementation libs.mysql_connector_java
            implementation libs.sqlite_jdbc

            // Configs
            implementation libs.jackson_core
            implementation libs.jackson_kotlin
            implementation libs.jackson_yaml

            // Dependency Injection
            implementation libs.guice

            // We use checker for annotations
            implementation libs.checker_qual

            // TODO: Permissions
        }

        // Jars

        if (currentProject.name.contains("-api")) {
            shadowJar {
                enabled = false
            }

            task sourcesJar(type: Jar, dependsOn: classes) {
                classifier = 'dev'
                from currentProject.sourceSets.main.allSource.srcDirs
            }
        } else {
            jar {
                enabled = false
            }

            shadowJar {
                // Only shadow implementation/modImplementation
                configurations = [project.configurations.shade, project.configurations.include]
                classifier = "dev"
            }

            task sourcesJar(type: Jar, dependsOn: classes) {
                classifier = 'sources'
                from currentProject.sourceSets.main.allSource.srcDirs
            }

            sourcesJar.dependsOn(shadowJar)
        }

        remapJar {
            input = file("${project.buildDir}/libs/$archivesBaseName-${project.version}-dev.jar")
            archiveName = "${archivesBaseName}-${project.version}.jar"
        }

        remapJar.dependsOn(sourcesJar)

        // Artifacts? Not sure why this is needed

        artifacts {
            dev file: file("${project.buildDir}/libs/$archivesBaseName-${project.version}-dev.jar"), type: "jar", builtBy: jar
        }

        // Set version in fabric.mod.json
        processResources {
            doFirst {
                delete fileTree('build/resources') {
                    include '**/*'
                }
            }

            inputs.property "version", project.version

            from(currentProject.sourceSets.main.resources.srcDirs) {
                include "fabric.mod.json"
                expand "version": project.version
            }

            from(currentProject.sourceSets.main.resources.srcDirs) {
                exclude "fabric.mod.json"
            }
        }

        // Fix some kotlin warnings
        compileKotlin.kotlinOptions.jvmTarget = "1.8"
    }

    // License shit

    task licenseFormatAll
    subprojects { p -> licenseFormatAll.dependsOn("${p.path}:licenseFormat") }

    subprojects {
        runClient {
            enabled = false
        }
        runServer {
            enabled = false
        }
    }

    // Build oddities

    subprojects.each {
        if (!it.name.contains("-api")) {
            remapJar.dependsOn("${it.path}:remapJar")
        }
    }

    dependencies {
        afterEvaluate {
            subprojects.each {
                shade project(path: ":${it.name}", configuration: 'shadow')
            }
        }

        // Runtime Only Dependencies
        modRuntime(libs.modmenu) {
            transitive = false // Naughty mods who JIJ fabric api
        }
        modRuntime(libs.playerabilitylib) {
            transitive = false
        }
        modRuntime(project(":essentials-api")){
            // patchy or something idfk
            transitive = false
        }
    }

    // Fat jar

    jar {
        enabled = false
    }

    shadowJar {
        // Only shadow implementation/modImplementation
        configurations = [project.configurations.shade, project.configurations.include]
        classifier = "dev"
        append "src/main/resources/fabric.mod.json"
    }

    remapJar.dependsOn(shadowJar)

    // Curseforge upload

    curseforge {
        apply from: 'curseforge.gradle'
        apiKey = project.apiKey
        project {
            id = "350123"
            releaseType = "beta"
            changelogType = "markdown"
            changelog = "Testing auto-upload from gradle"
            addGameVersion project.minecraft
            addGameVersion "Fabric"
            addGameVersion "Java 8"

            // Main jar as main artifact
            mainArtifact file("${project.buildDir}/libs/$archivesBaseName-${project.version}.jar")

            // Other files as sub-artifacts maybe?
            // addArtifact file("${project.buildDir}/libs/$archivesBaseName-${project.version}-dev.jar")
            // addArtifact file("${project.buildDir}/libs/$archivesBaseName-${project.version}-sources.jar")
            // addArtifact file("${project.buildDir}/libs/$archivesBaseName-${project.version}-sources-dev.jar")

            subprojects { sub ->
                // Add built modules
                addArtifact file("${project.buildDir}/libs/$sub.archivesBaseName-${project.version}.jar")

                // Maybe add dev and sources?
                // addArtifact file("${project.buildDir}/libs/$archivesBaseName-${project.version}-dev.jar")
                // addArtifact file("${project.buildDir}/libs/$archivesBaseName-${project.version}-sources.jar")
                // addArtifact file("${project.buildDir}/libs/$archivesBaseName-${project.version}-sources-dev.jar")
            }

            afterEvaluate {
                uploadTask.dependsOn(remapJar)
            }
        }
        options {
            forgeGradleIntegration = false
        }
    }

</details>

### Content of Shadow JAR

[<code>$ jar tf build/libs/essentials-0.1.0+1.15.2.jar</code>](https://gist.github.com/martmists/4d31b2a32b40113578a7a86af91e908e)

**Comment by martmists** [comment]
Update: Jars simply `include`d are also affected by this, losing the nested jars present. These are not added to the main jar.

**Comment by annunez** [comment]
Did you find a workaround for this?

**Comment by martmists** [comment]
Yeah, there were some issues with how another plugin handled things which got fixed by them, closing.
