### ISSUE TITLE
Unable to use shadow in plugin script

### ISSUE THREAD

**Issue by nacrotic** [johnrengelman/shadow#578]
### Shadow Version
5.2.0, 5.1.0

### Gradle Version
6.0

### Expected Behavior
Start a new gradle project (with eclipse in my case)
Verify that the default build finishes successfully
Create shadow.gradle and modify build.gradle to use it (see files below)
Everything should work and the jar should be generated

### Actual Behavior
Gradle crash with the following message

> FAILURE: Build failed with an exception.
> 
> * Where:
> Script '%USERPROFILE%\eclipse-workspace\test\shadow.gradle' line: 12
> 
> * What went wrong:
> A problem occurred evaluating script.
> \> Plugin with id 'com.github.johnrengelman.shadow' not found

/!\ If you replace `apply from: 'shadow.gradle'` by the content of the file 'shadow.gradle' everything works perfectly.

### Gradle Build Script(s)
**build.gradle**
```groovy
apply plugin: 'java'
apply from: 'shadow.gradle'

repositories {
    jcenter()
}

dependencies {
    implementation 'org.apache.commons:commons-math3:3.6.1'
    implementation 'com.google.guava:guava:28.0-jre'
    testImplementation 'junit:junit:4.12'
}
```
**shadow.gradle**
```groovy
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "com.github.jengelman.gradle.plugins:shadow:5.2.0"
  }
}

apply plugin: "com.github.johnrengelman.shadow"
```

**Comment by johnrengelman** [comment]
Plugin application is controlled by Gradle not the plugin. Please check the a Gradle forums.
