### ISSUE TITLE
Gradle 6.6.1 still reports shadowJar has a forward-incompatibility with Gradle 7.0

### ISSUE THREAD

**Issue by rdesgroppes** [johnrengelman/shadow#601]
This is to report that, despite all the good work to address #530, there seems to be a leftover `Property 'transformers.$1.data' is not annotated with an input or output annotation`.

### Shadow Version

```groovy
id 'com.github.johnrengelman.shadow' version '6.1.0'
```

### Gradle Version

```
------------------------------------------------------------
Gradle 6.6.1
------------------------------------------------------------

Build time:   2020-08-25 16:29:12 UTC
Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_265 (Private Build 25.265-b01)
OS:           Linux 5.4.0-47-generic amd64
```

### Expected Behavior

No forward-incompatibility with Gradle 7.0.

### Actual Behavior

```sh
$ ./gradlew --debug assemble
...
[LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :my:shadowJar UP-TO-DATE
[DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :my:shadowJar' started
[DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Putting task artifact state for task ':my:shadowJar' into context took 0.0 secs.
[WARN] [org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler] Property 'transformers.$1.data' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.6.1/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
[DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Snapshot inputs and outputs before executing task ':my:shadowJar'' started
...
```

### Gradle Build Script(s)

```groovy
plugins {
...
    id 'com.github.johnrengelman.shadow' version '6.1.0' apply false
...
}
...
project(':my') {
...
    apply plugin: 'com.github.johnrengelman.shadow'
...
    shadowJar {
        mergeServiceFiles()
        append('my.conf')
    }
...
}
```

**Comment by boris-petrov** [comment]
@johnrengelman - I understand that Gradle 7 is coming very soon so it would be nice to have these fixed for `Gradle Shadow` to work with it.

**Comment by liutikas** [comment]
Our team is seeing this as well. Any chance we can get an update?

```
> Task :wear:wear-tiles-proto:shadowJar
Execution optimizations have been disabled for task ':wear:wear-tiles-proto:shadowJar' to ensure correctness due to the following reasons:
  - Type 'ShadowJar': property 'transformers.$0.resource' is not annotated with an input or output annotation.

> Task :work:work-inspection:shadowDependenciesRelease
Execution optimizations have been disabled for task ':work:work-inspection:shadowDependenciesRelease' to ensure correctness due to the following reasons:
  - Type 'ShadowJar': property 'transformers.$0.renamed' is not annotated with an input or output annotation.

> Task :compose:ui:ui-inspection:shadowDependenciesRelease
Execution optimizations have been disabled for task ':compose:ui:ui-inspection:shadowDependenciesRelease' to ensure correctness due to the following reasons:
  - Type 'ShadowJar': property 'transformers.$0.renamed' is not annotated with an input or output annotation.
```

**Comment by effad** [comment]
We are in the process of migrating to Gradle 7 and are affected by this problem. ShadowJar doesn't work with Gradle 7.0-rc-1:

> * What went wrong:
> Some problems were found with the configuration of task ':project:products:WheelServer:shadowJar' (type 'ShadowJar').
>   - Type 'ShadowJar' property 'transformers.$0.serviceEntries' is missing an input or output annotation.
>     
>     Reason: A property without annotation isn't considered during up-to-date checking.
>     
>     Possible solutions:
>       1. Add an input or output annotation.
>       2. Mark it as @Internal.
>     
>     Please refer to https://docs.gradle.org/7.0-rc-1/userguide/validation_problems.html#missing_annotation for more details about this problem.
>   - Type 'ShadowJar' property 'transformers.$1.excludePackages' is missing an input or output annotation.
>     
>     Reason: A property without annotation isn't considered during up-to-date checking.
>     
>     Possible solutions:
>       1. Add an input or output annotation.
>       2. Mark it as @Internal.
>     
>     Please refer to https://docs.gradle.org/7.0-rc-1/userguide/validation_problems.html#missing_annotation for more details about this problem.
>   - Type 'ShadowJar' property 'transformers.$1.includePackages' is missing an input or output annotation.
>     
>     Reason: A property without annotation isn't considered during up-to-date checking.
>     
>     Possible solutions:
>       1. Add an input or output annotation.
>       2. Mark it as @Internal.
>     
>     Please refer to https://docs.gradle.org/7.0-rc-1/userguide/validation_problems.html#missing_annotation for more details about this problem.
>   - Type 'ShadowJar' property 'transformers.$2.data' is missing an input or output annotation.
>     
>     Reason: A property without annotation isn't considered during up-to-date checking.
>     
>     Possible solutions:
>       1. Add an input or output annotation.
>       2. Mark it as @Internal.
>     
>     Please refer to https://docs.gradle.org/7.0-rc-1/userguide/validation_problems.html#missing_annotation for more details about this problem.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org

**Comment by liutikas** [comment]
Is there an ETA for a release of the plugin with this fix? It would be very helpful to us to continue testing Gradle 7.0

**Comment by effad** [comment]
I've seen that there is a 7.0.0 release of shadowJar now and according to https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow this is the latest version.
However, https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/ does not (yet?) contain this version, which leads to this error when trying to use it:
> A problem occurred configuring root project 'java'.
> > Could not resolve all artifacts for configuration ':classpath'.
>    > Could not find com.github.jengelman.gradle.plugins:shadow:7.0.0.
>      Searched in the following locations:
>        - https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/7.0.0/shadow-7.0.0.pom
Is this just a lag of the processes involved or did sth. go wrong in the release process?

**Comment by johnrengelman** [comment]
@effad you are looking in the wrong maven coordinates for 7.0.0. The group name changed for this version to fall in line with the idiomatic configuration for Gradle plugins (due to the jcenter shutdown).

This is show in the example on the plugin page here: https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow/7.0.0

The correct location is:
https://plugins.gradle.org/m2/gradle/plugin/com/github/jengelman/gradle/plugins/shadow/

I will update the release notes to reflect this change.

**Comment by rdesgroppes** [comment]
It works like a charm. Thanks, @johnrengelman!

**Comment by effad** [comment]
> @effad you are looking in the wrong maven coordinates for 7.0.0. The group name changed for this version to fall in line with the idiomatic configuration for Gradle plugins (due to the jcenter shutdown).
Thanks for the hint, I was able to fix that. Will report new problems in separate issue.

**Comment by pacher** [comment]
@johnrengelman I am lost.. I used to use new and recommended plugins DSL, but
```
plugins {
  id "com.github.johnrengelman.shadow" version "7.0.0"
}
```
taken from https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow
no longer works for 7.0.0
I've tried to prepend it with `gradle.plugin.` and other variants with no luck.
Do I have to switch back to legacy apply plugin syntax to be able to specify an exact location of artifact? 
This would be very much not desirable..
