### ISSUE TITLE
How to publish *without* ShadowJar

### ISSUE THREAD

**Issue by CLOVIS-AI** [johnrengelman/shadow#604]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version
Shadow version 6.0.0

### Gradle Version
Gradle version 6.6

### Expected Behavior
With configuration:
```kotlin
// build.gradle.kts
plugins {
    `maven-publish`
    id("com.github.johnrengelman.shadow") version "6.0.0"
}
tasks {
    shadowJar {
        archiveBaseName.set("projectName")
        archiveClassifier.set("all")
        archiveVersion.set("")
    }
}
publishing {
    publications {
        create<MavenPublication>("maven") {
            // setup groupId, artifactId, version
            from(components["java"])
        }
    }
    // setup repositories
}
```
When running `./gradlew publish`, Gradle should upload a `.pom`, a `.module` and a normal `.jar`, but not the `-all.jar` FatJar.

### Actual Behavior
Gradle publishes the three expected files __and__ a `-all.jar` FatJar, even though the configuration says `from(components["java"])` and not `from(components["shadow"])`

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
The contents of the JAR are completely working

**Comment by kisssadam** [comment]
Same problem: #586

**Comment by CLOVIS-AI** [comment]
Thanks, I missed it. Two months without a reply, I guess I'll try to find another plugin.
