### ISSUE TITLE
The spring webmvc project using embedded tomcat cannot run after packaging

### ISSUE THREAD

**Issue by TheForgetTime** [johnrengelman/shadow#617]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version
6.1.0

### Gradle Version
6.7-all

### Expected Behavior

Start a spring web program in the form of a jar package and access it normally

### Actual Behavior

Only tomcat is started, spring web is not loaded

### Gradle Build Script(s)

```gradle
plugins {
    java
    application
    id("com.github.johnrengelman.shadow") version "6.1.0"
}

group = "io.xxxx.nn"
version = "1.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_15
java.targetCompatibility = JavaVersion.VERSION_15
application{
    mainClass.set("io.xxxx.nn.Program")
    mainClassName = "io.xxxx.nn.Program"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.tomcat.embed:tomcat-embed-core:9.0.40")
    implementation("org.springframework:spring-webmvc:5.3.1")
    implementation("org.springframework.data:spring-data-jdbc:2.1.1")

    implementation("org.mybatis:mybatis:3.5.6")
    implementation("org.mybatis:mybatis-spring:2.0.6")

    implementation("ch.qos.logback:logback-classic:1.2.3")

    testImplementation("junit", "junit", "4.12")
}

```

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version
6.1.0

### Gradle Version
6.7-all

### Expected Behavior

Start a spring web program in the form of a jar package and access it normally

### Actual Behavior

Only tomcat is started, spring web is not loaded

### Gradle Build Script(s)

```gradle
plugins {
    java
    application
    id("com.github.johnrengelman.shadow") version "6.1.0"
}

group = "io.xxxx.nn"
version = "1.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_15
java.targetCompatibility = JavaVersion.VERSION_15
application{
    mainClass.set("io.xxxx.nn.Program")
    mainClassName = "io.xxxx.nn.Program"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.tomcat.embed:tomcat-embed-core:9.0.40")
    implementation("org.springframework:spring-webmvc:5.3.1")
    implementation("org.springframework.data:spring-data-jdbc:2.1.1")

    implementation("org.mybatis:mybatis:3.5.6")
    implementation("org.mybatis:mybatis-spring:2.0.6")

    implementation("ch.qos.logback:logback-classic:1.2.3")

    testImplementation("junit", "junit", "4.12")
}

```

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)

[jartf.TXT](https://github.com/johnrengelman/shadow/files/5596881/jartf.TXT)

**Comment by skkim-pixel-monster** [comment]
I'm having the same issue, how did you solve it?
