### ISSUE TITLE
How to use a forked version?

### ISSUE THREAD

**Issue by simPod** [johnrengelman/shadow#621]
_Hi, this might not be fully related to the shadow but was thinking that people here might have the most relevant experience._

I have a suspicion there's a bug in reproducible builds. I'd like to debug the plugin within my private project, so I forked this repo. But I don't know how to wire it into my gradle, how to use forked version instead of the one published to maven. Would anyone be willing to share a tip how to do it? 

Thanks!

**Comment by johnrengelman** [comment]
This is best asked on the Gradle user forums.
