### ISSUE TITLE
No .jar files appear published on plugins.gradle.org/m2 - bintray issue?

### ISSUE THREAD

**Issue by phassingeropi** [johnrengelman/shadow#623]
No .jar files appear published on plugins.gradle.org/m2 for johnrengelman - bintray issue?

### Shadow Version
All

### Gradle Version
All

### Expected Behavior
I would expect https://plugins.gradle.org/m2/com/github/johnrengelman/shadow/com.github.johnrengelman.shadow.gradle.plugin/5.2.0/com.github.johnrengelman.shadow.gradle.plugin-5.2.0.jar to be a downloadable file.

### Actual Behavior
Redirects to: https://jcenter.bintray.com/com/github/johnrengelman/shadow/com.github.johnrengelman.shadow.gradle.plugin/5.2.0/com.github.johnrengelman.shadow.gradle.plugin-5.2.0.jar
Response:
`{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}`

Now, is returning a 404 response altogether instead of a redirect to bintray

### Gradle Build Script(s)
N/A

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
None

**Comment by rozhok** [comment]
Looks like 5.2.0 version was unpublished.
6.1.0 works, however.

**Comment by johnrengelman** [comment]
Not sure, will definitely have to look into this with the Bintray/JCenter shut down.

**Comment by johnrengelman** [comment]
The Maven group name is different from the plugin id.
That JAR files are under this group: `com.github.jengelman.gradle.plugins` (https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/6.1.0/)

**Comment by johnrengelman** [comment]
I suspect this is because Shadow as one on the first plugins published to the Gradle Plugin portal and that process has undergone a number of revisions over the years.

With the jcenter shutdown, I'm going to re-look at how this is how configured with one option being to migrate the whole plugin into a new plugin ID and use all the standard configuration.
