### ISSUE TITLE
ConfigureShadowRelocation with Kotlin DSL

### ISSUE THREAD

**Issue by 2x2xplz** [johnrengelman/shadow#629]
I feel pretty dumb for converting my Gradle scripts to the Kotlin DSL because, despite writing my program in Kotlin, the Gradle DSL is entirely un-intuitive and has very little documentation, the whole thing has caused headaches with no benefit.

With that said, how would one use the ConfigureShadowRelocation task in a Kotlin DSL gradle script?

I currently have this working:
```
tasks {
    named<ShadowJar>("shadowJar") {
      ...definition here...
    }
}

tasks {
    build {
        dependsOn(shadowJar)
    }
}
```

I tried:
```
tasks {
    "relocateShadowJar"(ConfigureShadowRelocation::class) {
        target = shadowJar.get()
        prefix = "myprefix"
    }
}
```
and
```
tasks {
    named<ConfigureShadowRelocation>("configureShadowRelocation") {
        target = shadowJar.get()
        prefix = "myprefix"
    }
}
```

but cannot create a valid dependency relationship:
```
tasks {
    shadowJar {
        dependsOn(configureShadowRelocation)  <--- unresolved
        dependsOn(relocateShadowJar)  <--- unresolved
    }
}
```

I'm not sure this will even work, I am able to create a single working JAR from 3 individual package components (thank you!). I wanted to relocate the 3 packages to keep them together and distinct from all of the 3rd party dependencies, but this caused ClassNotFoundExceptions, I am hoping to fix these with the ConfigureShadowRelocation plugin. In other words I want to change:

```
com
javax
aaa
bbb
ccc
net
org
```
to

```
com
javax
myprogram
  |
  |\_aaa
  |\_bbb
   \_ccc
net
org
```

**Comment by big-andy-coates** [comment]
For the first part, try:

```Kotlin
plugins {
    id("com.github.johnrengelman.shadow") version "6.1.0"
}

// Shadow ALL dependencies:
tasks.create<ConfigureShadowRelocation>("relocateShadowJar") {
    target = tasks["shadowJar"] as ShadowJar
    prefix = "myprefix"
}

// Configure Shadow to output with normal jar file name:
tasks.named<ShadowJar>("shadowJar").configure {
    dependsOn(tasks["relocateShadowJar"])
    // Other config
}
```

For the second part, I've not done this myself, but have seen it done by creating a custom configuration. e.g. see use of `shadowImplementation` in this build script: https://github.com/JLLeitschuh/ktlint-gradle/blob/master/plugin/build.gradle.kts. You'd need to ensure only `aaa`, `bbb` and `ccc` where marked as `shadowImplementation`.

Hope this helps

**Comment by 2x2xplz** [comment]
@big-andy-coates  sorry for the delay in responding. thank you very much for providing an example and including that link. got caught up with some other issues so haven't tried it yet but wanted to acknowledge and say thanks, definitely appears to be a step ahead of what I was attempting.
