### ISSUE TITLE
Publish shadow plugin to maven central

### ISSUE THREAD

**Issue by hertzsprung** [johnrengelman/shadow#637]
With [bintray jcenter shutting down on 1 May 2021](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), it would be great if the shadow plugin can be published to Maven Central.  There's some more info on [this Sonatype blog](https://blog.sonatype.com/what-publishers-need-to-know-about-migrating-from-jcenter-/-bintray-to-the-central-repository).

**Comment by ArcticLampyrid** [comment]
`https://plugins.gradle.org/m2/` is not shutting down.

**Comment by hertzsprung** [comment]
> `https://plugins.gradle.org/m2/` is not shutting down.

Thanks, I wasn't aware of this repo!  Does gradle fetch from it by default?  Because my gradle project isn't finding it automatically. :thinking:

**Comment by ArcticLampyrid** [comment]
> Does gradle fetch from it by default?

It's the default repo for plugins DSL.
https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block

**Comment by hertzsprung** [comment]
> > Does gradle fetch from it by default?
> 
> It's the default repo for plugins DSL.
> https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block

Ah, thanks.  It seems that gradle doesn't fetch from `plugins.gradle.org` using the alternative approach in the [shadow user guide](https://imperceptiblethoughts.com/shadow/getting-started/).
