### ISSUE TITLE
shadowJar runs on assemble - how do disable this?

### ISSUE THREAD

**Issue by RichColours** [johnrengelman/shadow#644]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Expected Behavior
I have java plugin in my project, and shadowJar, but I want to run assemble normally without the shadowJar being built. I've made a minimal project with just one java application and your plugin, and running ./gradlew assemble yields the shadow jar output.
A problem I have is that shadowjar for my production app takes 30 seconds cus it is very large, and want to control when I actually make this jar.

### Actual Behavior
When i want it, like if I decide to assemble.dependsOn shadowJar for example.

Your docs say that shadowjar is reactive yet does not configuration. Am I doing something wrong for shadowJar to be being invoked on assemble of very basic java project?

Or pls point me to where in your (very nice) docs that it says that shadowJar runs as part of assemble.

**Comment by RichColours** [comment]
I've worked this out:

It seems that shadowJar (not sure if deliberately) adds its output to the `archives` configuration. It is known that the Java Plugin assembles all such archives in "archives".

```// Remove "<prj-shadow> from "archives", it goes in by default and we don't need it built by default:
project.getConfigurations().archives.artifacts.removeIf {
    v -> v.name.endsWith("-shadow")
}``` this takes two entries out of the `archives` configuration.

Maybe the same could be achieved by not having a `shadowJar{}` block and just using an extension task. I'll try.

**Comment by bfg** [comment]
hey @RichColours I'm also annoyed by this behaviour. I've worked around this with this gradle snippet:

```gradle
// run `shadowJar` task only if that was user's preference, i.e. if user explicitly
// asked for it by manually specifying it via CLI by specifying that shadowJar
// task should be ran
def shadowJarEnabled = gradle.startParameter.taskRequests
  .find {it.args.find {it.contains("shadowJar")} != null  } != null
if (!shadowJarEnabled) {
  gradle.startParameter.excludedTaskNames += "shadowJar"
}
```

@johnrengelman - it would be great if it would be possible to disable this behaviour via `shadowJar {}` configuration block.

**Comment by johnrengelman** [comment]
Why would this not be what you expect? A shadow jar is an artifact for the repo and `assemble` is intended to build all the artifacts?

If you want a different behavior, you can create your own task that has dependencies to only the build artifacts/tasks that you want.

**Comment by bfg** [comment]
> Why would this not be what you expect? A shadow jar is an artifact for the repo and `assemble` is intended to build all the artifacts?

Well, the use case I have is quite simple: I use `./gradlew clean build` to build the project and run the tests. Sometimes I have a failing test, which I'm trying to fix and it's annoying to wait for additional 20+ seconds for shadowJar task to complete, even though I'm usually not interested in building shadowJar at all; I'm interested in shadowJar only on CI builds which produce artifacts that are going to be deployed.

**Comment by johnrengelman** [comment]
Gradle provides many different ways for you to customize this work flow to your needs. For example, you could run “gradle clean check build” instead which will run all your tests and static checks before trying to create jars or you could do “gradle clean build -x shadowJar” to tell it to force skipping the shadow jar task
