### ISSUE TITLE
Gradle mainClassName is deprecated will be removed in v7.x

### ISSUE THREAD

**Issue by phreed** [johnrengelman/shadow#645]
### Shadow Version
v 6.1.0

### Gradle Version
v 6.8.3

### Expected Behavior
Accept the Gradle recommended main-class-name. 

```
val mainClassPath = "the main class package/name"
application {
    mainClass.set(mainClassPath)
}
```

### Actual Behavior

The deprecated `mainClassName` must be specified.
The warning can be suppressed but must be corrected for Gradle v7.x
```
application {
    mainClass.set(mainClassPath)
    @Suppress("DEPRECATION")
    mainClassName = mainClassPath
}
```

**Comment by efenderbosch** [comment]
dupe of #631 #609 #612
