### ISSUE TITLE
Plugin incompatible with Gradle 7.0 on property mainClass

### ISSUE THREAD

**Issue by TobseF** [johnrengelman/shadow#663]
### Shadow Version
**Shadow 5.2.0**

### Gradle Version
**Gradle 7.0**

### Expected Behavior
The shadow plugin should support the `mainClass` which is present since **Gradle 6.4**. The depreciated `mainClassName` which can be used before, was removed in **Gradle 7**.
```kotlin
/**
 * The fully qualified name of the application's main class.
 *
 * @since 6.4
 */
Property<String> getMainClass();
```

### Actual Behavior
Instead of using the provided property `mainClass`, the `shadowJar` command fails with:
> ` No value has been specified for property 'mainClassName'.`

Trying to add it with the `manifest` section also failed with the same error.
```kotlin
 manifest {
    attributes(mapOf("Main-Class" to "de.tfr.MainKt"))
 }
```
But even when it's possible to specify the manifest, this blows up the build file and is a pity, because the whole manifest  section can be skipped, if the new `mainClass` property would be supported like the old `mainClassName`.
This problem is also mentioned in https://github.com/johnrengelman/shadow/issues/572

### Gradle Build Script(s)
```kotlin
application() {
    mainClass.set("de.tfr.MainKt")
}
```

**Comment by ArcticLampyrid** [comment]
Actually fixed, just wait for a new version to be released
