### ISSUE TITLE
Java 8: java.lang.IllegalArgumentException: Unsupported class file major version 59

### ISSUE THREAD

**Issue by Computerdores** [johnrengelman/shadow#677]
Shadow Version: 5.2.0
Gradle Version: 6.8.1

### Expected Behavior
Building of the Jar

### Actual Behavior
Error Message + Stacktrace:
[Link To Gist](https://gist.github.com/Computerdores/1c705290932fb47e422184476900a15c)

### Gradle Build Script(s)
[Link To PasteBin](https://pastebin.com/gGFpXzyd)

**Comment by Computerdores** [comment]
I looked through a few issues with a similar title and it seems that their stacktrace also ended / began in the `shadow.org.objectweb.asm.ClassReader` Class, although they appear to have been fixed on shadow version 4.0.0 and 4.0.1 resp.

**Comment by johnrengelman** [comment]
Please use a version of Shadow that maches you’re Gradle release (6.x line). This project does not back port compatibility patches to older versions.
