### ISSUE TITLE
ShadowJar failing on records because records requires ASM8

### ISSUE THREAD

**Issue by josephjthomas** [johnrengelman/shadow#679]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version
7.0.0

### Gradle Version
7.0.2

### Expected Behavior
Bumping ASM to 8 or higher to allow the usage of records in a shadowjar.

### Actual Behavior
Build fails with `java.lang.UnsupportedOperationException: Records requires ASM8` when using records and compiling with Java 16 targeting Java 16.
Full stacktrace: https://paste.gg/p/anonymous/6a11517d3d4c4f45b0056b70d6bcab05

### Gradle Build Script(s)
/

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
We don't get here due failure on the build process.

**Comment by josephjthomas** [comment]
Could this be an issue with jdependency? They recently fixed it within version 2.7.0, shadow still uses 2.6.0

**Comment by jpenilla** [comment]
> Could this be an issue with jdependency? They recently fixed it within version 2.7.0, shadow still uses 2.6.0

Yes, this issue is due to shadow using outdated jdependency. I authored [this PR](https://github.com/tcurdt/jdependency/pull/67) to jdependency and have been using a custom build of shadow with the updated jdependency for my Java 16 projects since then without issue.

**Comment by Starmism** [comment]
Just to note for anyone waiting for the PR to be merged, in my case the issue was resolved by not minimizing in shadowJar.

**Comment by duplexsystem** [comment]
I'm having this same issue and confirmed #681 fixed it.
