### ISSUE TITLE
Replace  JavaExec:main with mainClass 

### ISSUE THREAD

**Issue by ben-manes** [johnrengelman/shadow#680]
> The JavaExec.main property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the mainClass property instead. See [JavaExec:main](https://docs.gradle.org/7.1-rc-1/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:main) for more details.
____ at org.gradle.api.tasks.JavaExec.setMain(JavaExec.java:418)
____ at com.github.jengelman.gradle.plugins.shadow.internal.JavaJarExec_Decorated.setMain(Unknown Source)
____ at org.gradle.api.tasks.JavaExec.setMain(JavaExec.java:112)
____ at org.gradle.process.JavaExecSpec$setMain.call(Unknown Source)
____ at com.github.jengelman.gradle.plugins.shadow.ShadowApplicationPlugin$_addRunTask_closure4.doCall(
_________ ShadowApplicationPlugin.groovy:83)

https://github.com/johnrengelman/shadow/blob/7eaffb78a020e024a3618b9c6f9c54730b8f23c0/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.groovy#L83

**Comment by alexp1917** [comment]
can we get a 7.1.0 release, as this is already fixed in the master branch? thanks!!!

**Comment by ben-manes** [comment]
Seems to have been released in 7.1, which also changed the GAV notation so that users won't find out from their dependency management tools (not in the github release notes)...
