### ISSUE TITLE
[FeatureRequest] Add ability to merge json file when create shadowJar

### ISSUE THREAD

**Issue by LogicFan** [johnrengelman/shadow#685]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version 

7.0.0

### Gradle Version 

7.0.2

### Expected Behavior

merge json files similar to xml.

### Actual Behavior

it does not merge.

**Comment by LogicFan** [comment]
Here is a working implementation, can someone add this into the repo?
https://github.com/LogicFan/shadow-json-transformer/blob/main/plugin/src/main/groovy/com/github/logicfan/gradle/shadow/transformers/JsonTransformer.groovy

**Comment by johnrengelman** [comment]
I doesn't need to be added to this repo. You can add that class above to your `buildSrc` directory in your project so that it's available to Gradle itself and then add it as a transformer using the `shadowJar.transform(Class)` method.
