### ISSUE TITLE
Bash executable

### ISSUE THREAD

**Issue by amirabiri** [johnrengelman/shadow#695]
I'd like to re-raise the issue that was raised in the past in https://github.com/johnrengelman/shadow/issues/320 (didn't want to comment on a closed issue). I wanted to challenge the assumption again and try to explain the use case better.

The core concept is simple - it's a simple technique that exists in *nix environments and is explained here: https://coderwall.com/p/ssuaxa/how-to-make-a-jar-file-linux-executable. This creates the illusion of a native executable on *nix systems.

This is very useful for many things - in particular it allows us to develop JVM-based cli tools and applications like git and docker. e.g we can then distribute to our users who instead of this:

```
# java -jar git.jar fetch
```

```
# git fetch
```

Combining Shadow Jar with [PicoCli](https://picocli.info/) this way creates a very powerful tool combination!

It also means that in a cloud environment we can distribute simple artifacts that are very easy to digest. e.g we just hand over a microservice to devops that looks like this:

```
# microservice
```

In order to support this very little needs to be done really - all that is left to do from where Shadow Jar is right now is to support an option of prepending a given shell script to the final artifact:

```
shadowJar {
    prependFile 'path/to/file.sh' // Or a better name for this...
}
```

**Comment by amirabiri** [comment]
BTW this technique is also used by Spring Boot for the same effect: https://docs.spring.io/spring-boot/docs/current/reference/html/deployment.html#deployment.installing.

However this ability is missing if building slim microservices using something other than Spring Boot and combining it with Shadow Jar (for example ktor + shadow jar).

**Comment by johnrengelman** [comment]
I'm not going to add this feature per the previous thread.
