### ISSUE TITLE
[Feature Suggest] Draft new release / Make it compatible with Java 17

### ISSUE THREAD

**Issue by josephjthomas** [johnrengelman/shadow#704]
Is a new release draft work in progress? I'd like to use the new features and fixes.

**Comment by josephjthomas** [comment]
Java 17 dropped and shadow 7.0.0 became unusable due "PermittedSubclasses requires ASM9". 
I would kindly like to ask again, can we please have a release? The required pull requests have already been pulled months ago.

**Comment by KroArtem** [comment]
@johnrengelman , WDYT about releasing new version?
