### ISSUE TITLE
Recent versions not available at https://plugins.gradle.org/m2/

### ISSUE THREAD

**Issue by glegoux** [johnrengelman/shadow#723]
Hello, 

The versions from 6.1.0+ (excluded) are not available at https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/ 

Could you add other recent versions like 7.0.0 and 7.1.0?

Thanks in advance!

**Comment by kdubb** [comment]
Correct path is https://plugins.gradle.org/m2/com/github/johnrengelman/shadow/com.github.johnrengelman.shadow.gradle.plugin.

The id is `com.github.johnrengelman.shadow`.

**Comment by KengoTODA** [comment]
I faced the same problem https://github.com/spotbugs/spotbugs-gradle-plugin/issues/589

It comes from the change in `com.gradle.plugin-publish` version 0.16.0. It's not a problem of the shadow plugin side, and users need to update the URL as described in the [plugin portal page](https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow).
