### ISSUE TITLE
Is shadow vulnerable to CVE- 2021-44228 ?

### ISSUE THREAD

**Issue by MortronMeymo** [johnrengelman/shadow#736]
Shadow definitely uses a vulnerable version of lg4j-core which should be updated as requested by #731, but is it actually vulnerable?

After searching through the code I saw that it does not use lg4j for logging, but uses 2 classes from log4j in `Log4j2PluginsCacheFileTransformer.groovy`. Those two classes are `PluginCache` and `PluginEntry` and after reviewing those it looks like is not vulnerable. Is this correct?

But of course due to the dependency shadow pulls a vulnerable version of lg4j into the classpath.

**Comment by williamwebb** [comment]
Not sure if shadow is vulnerable, but it is shading the vulnerable version of log4j. So it will always be marked as vulnerable by https://jfrog.com/xray/.

**Comment by johnrengelman** [comment]
This is pretty unlikely. If you aren’t logging untrusted user supplied values, there’s no issue. Also, why would shadow be in the classpath of a java app that’s doing work (http server, kafka processor, etc.) it’s a build plugin and its dependencies are contained in the build system. They aren’t propagated to the application.

**Comment by johnrengelman** [comment]
Closed in https://github.com/johnrengelman/shadow/commit/402c14fab1fb241c82898082e7ca58417c75c6f6
Will be released in 7.1.1 momentarily.

**Comment by MortronMeymo** [comment]
I meant on the classpath during build time, meaning a build server might be attackable, but not the application once deployed :D

**Comment by tkrah** [comment]
> This is pretty unlikely. If you aren’t logging untrusted user supplied values, there’s no issue. Also, why would shadow be in the classpath of a java app that’s doing work (http server, kafka processor, etc.) it’s a build plugin and its dependencies are contained in the build system. They aren’t propagated to the application.

You're right but different scan tools are false-flagging your plugin to be vulnerable just because they found the class in question in your plugin and IT stuff is going to delete / block your plugin because of that, so it is a good idea to update it - like done - to mitigate that problem and the discussion with IT ;-).

**Comment by ibzib** [comment]
Would it be possible to release a patch for shadow version 6 as well? Our project (apache/beam) is having difficulties upgrading to Gradle 7.
