### ISSUE TITLE
New releases missing from Gradle plugin repository

### ISSUE THREAD

**Issue by ahrens26** [johnrengelman/shadow#738]
The latest version of shadow at https://plugins.gradle.org/m2/gradle/plugin/com/github/jengelman/gradle/plugins/shadow/ is 7.0.0.  Releases 7.1.0 and 7.1.1 are missing, despite https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow showing version 7.1.1 as latest.

**Comment by johnrengelman** [comment]
See the release notes for 7.1 - https://github.com/johnrengelman/shadow/tree/master/src/docs/changes#v710-2021-10-04
