### ISSUE TITLE
Upgrade log4j dependency in version 4.x

### ISSUE THREAD

**Issue by gurusankar-subramanian** [johnrengelman/shadow#742]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version
shadow 4.0.4

### Gradle Version
Gradle 4.10.3

### Expected Behavior
log4j-core-2.11.0 is getting downloaded as part of shadow plugin

### Actual Behavior
upgrade log4j dependency in 4.x version

**Comment by johnrengelman** [comment]
Sorry, I'm not going to backport fixes. Please update to modern versions.
