### ISSUE TITLE
Dependency not found when using Shadow version 7.x

### ISSUE THREAD

**Issue by sfitts** [johnrengelman/shadow#745]
### Shadow Version

7.1.2

### Gradle Version

7.3.3

### Expected Behavior

Using the supplied `build.gradle` file we expect the `implementation` dependency on the plugin's JAR file to be resolved.

### Actual Behavior

The dependency cannot be found.

### Gradle Build Script(s)

```
apply plugin: 'groovy'

repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    implementation ("com.github.jengelman.gradle.plugins:shadow:7.1.2")
    implementation group: 'com.google.guava', name: 'guava', version: '31.0-jre'
}
```

We have a couple of custom transformers that are part of our build (located in `buildSrc`).  These classes reference classes from the shadow plug-in (such as `com.github.jengelman.gradle.plugins.shadow.transformers.Transformer`).  For all versions of the plug-in prior to 7.x, the build script above worked fine.  Starting with the 7.x version we get the following error:

```
Execution failed for task ':buildSrc:compileGroovy'.
> Could not resolve all files for configuration ':buildSrc:compileClasspath'.
   > Could not find com.github.jengelman.gradle.plugins:shadow:7.1.2.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/7.1.2/shadow-7.1.2.pom
       - https://repo.maven.apache.org/maven2/com/github/jengelman/gradle/plugins/shadow/7.1.2/shadow-7.1.2.pom
     Required by:
         project :buildSrc
```

Poking about in the directories for `https://plugins.gradle.org/m2/com/github/jengelman` we don't see any of the 7.x versions present.  Are these now located somewhere else?  I feel like we're missing something obvious, but I cannot figure out how to resolve this.

**Comment by johnrengelman** [comment]
See the breaking change note in v7.1.0 - https://imperceptiblethoughts.com/shadow/changes/#v7-1-0-2021-10-04
