### ISSUE TITLE
JCenter shutdown impact on Gradle builds

### ISSUE THREAD

**Issue by glazzari** [johnrengelman/shadow#746]
See https://blog.gradle.org/jcenter-shutdown

The Gradle Plugin Portal implicitly mirrors JCenter currently. If you’re using the Plugin Portal (via gradlePluginPortal() or the URL plugins.gradle.org/m2) to resolve your application’s dependencies, you may be relying on JCenter. You should avoid using the Plugin Portal as a repository, except for Gradle plugin projects.

### Shadow Version
7.3.2

### Actual Behavior
https://github.com/johnrengelman/shadow/blob/44bf43a0e338eef345d8a1b2fbbec768e67c051d/build.gradle#L5

**Comment by johnrengelman** [comment]
Are you suggesting a particular change here? Because this project also declares `mavenCentral` in it's repository configuration, so it's not only reliant on the plugin portals transitive fronting
https://github.com/johnrengelman/shadow/blob/master/build.gradle#L58-L59

**Comment by glazzari** [comment]
> Are you suggesting a particular change here? Because this project also declares `mavenCentral` in it's repository configuration, so it's not only reliant on the plugin portals transitive fronting https://github.com/johnrengelman/shadow/blob/master/build.gradle#L58-L59

So maybe you can just close this issue. I was just concerned about the _"You should avoid using the Plugin Portal as a repository, except for Gradle plugin projects."
