### ISSUE TITLE
Infinite loop with 7.1.2 and ConfigureShadowRelocation

### ISSUE THREAD

**Issue by michel-kraemer** [johnrengelman/shadow#747]
I'm the author of [gradle-download-task](https://github.com/michel-kraemer/gradle-download-task/). I'm using shadow to bundle the Apache HTTP client with my plugin. To avoid classpath collisions, I'm relocating Apache HTTP client to a different package: [build.gradle#L75-L80](https://github.com/michel-kraemer/gradle-download-task/blob/ccae9e1e0ce489828acb1693e9727b079517d9a7/build.gradle#L75-L80)

After upgrading from shadow 6.1.0 to 7.1.2, the `shadowJar` task runs into an infinite loop. I was able to figure out that relocation is the culprit. If I comment [L75-L80](https://github.com/michel-kraemer/gradle-download-task/blob/ccae9e1e0ce489828acb1693e9727b079517d9a7/build.gradle#L75-L80) out, the task runs successfully.

### Shadow Version

7.1.2

### Gradle Version

7.3.3

### Expected Behavior

Task runs successfully within seconds as it did in version 6.1.0

### Actual Behavior

Task does not finish after 15 minutes. It seems it's stuck in an infinite loop.

### Gradle Build Script(s)

https://github.com/michel-kraemer/gradle-download-task/blob/master/build.gradle

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)

—

### Steps to reproduce

1. `git clone https://github.com/michel-kraemer/gradle-download-task.git`
2. Edit [build.gradle#L3](https://github.com/michel-kraemer/gradle-download-task/blob/master/build.gradle#L3) and change shadow version from 6.1.0 to 7.1.2
3. Run `./gradlew shadowJar`

**Comment by michel-kraemer** [comment]
@johnrengelman Did you have time to have a look at this? Let me know if there's anything I can do to help. Thanks.

**Comment by johnrengelman** [comment]
I just pulled it and ran it on my machine (macbook m1 max) and it completed in 20 mins:

```
➜  gradle-download-task git:(master) ✗ ./gradlew shadowJar                                                                                                                               [22/02/4| 9:07AM]
Starting a Gradle Daemon (subsequent builds will be faster)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 19m 44s
5 actionable tasks: 5 executed
```

**Comment by johnrengelman** [comment]
I think you are pulling the entire Gradle dependency into your shadow jar:
```
  166 de/undercouch/gradle/tasks/download/org/gradle/initialization/BuildCancellationToken.class
  167 de/undercouch/gradle/tasks/download/org/gradle/initialization/GradleUserHomeDirProvider.class
  168 de/undercouch/gradle/tasks/download/org/gradle/internal/Actions$1.class
  169 de/undercouch/gradle/tasks/download/org/gradle/internal/Actions$CompositeAction.class
  170 de/undercouch/gradle/tasks/download/org/gradle/internal/Actions$FilteredAction.class
  171 de/undercouch/gradle/tasks/download/org/gradle/internal/Actions$NullAction.class
  172 de/undercouch/gradle/tasks/download/org/gradle/internal/Actions$RunnableActionAdapter.class
  173 de/undercouch/gradle/tasks/download/org/gradle/internal/Actions$TransformingActionAdapter.class
  174 de/undercouch/gradle/tasks/download/org/gradle/internal/Actions.class
  175 de/undercouch/gradle/tasks/download/org/gradle/internal/BiAction.class
  176 de/undercouch/gradle/tasks/download/org/gradle/internal/BiActions$1.class
  177 de/undercouch/gradle/tasks/download/org/gradle/internal/BiActions$2.class
  178 de/undercouch/gradle/tasks/download/org/gradle/internal/BiActions$3.class
  179 de/undercouch/gradle/tasks/download/org/gradle/internal/BiActions.class
  180 de/undercouch/gradle/tasks/download/org/gradle/internal/Cast.class
  181 de/undercouch/gradle/tasks/download/org/gradle/internal/Describables$1.class
  182 de/undercouch/gradle/tasks/download/org/gradle/internal/Describables$2.class
  183 de/undercouch/gradle/tasks/download/org/gradle/internal/Describables$AbstractDescribable.class
  184 de/undercouch/gradle/tasks/download/org/gradle/internal/Describables$FixedDescribable.class
  185 de/undercouch/gradle/tasks/download/org/gradle/internal/Describables$MemoizingDescribable.class
  186 de/undercouch/gradle/tasks/download/org/gradle/internal/Describables$ThreePartDescribable.class
  187 de/undercouch/gradle/tasks/download/org/gradle/internal/Describables$TwoPartDescribable.class
  188 de/undercouch/gradle/tasks/download/org/gradle/internal/Describables.class
  189 de/undercouch/gradle/tasks/download/org/gradle/internal/DisplayName.class
  190 de/undercouch/gradle/tasks/download/org/gradle/internal/ErroringAction.class
  191 de/undercouch/gradle/tasks/download/org/gradle/internal/Factories$1.class
  192 de/undercouch/gradle/tasks/download/org/gradle/internal/Factories$2.class
  193 de/undercouch/gradle/tasks/download/org/gradle/internal/Factories$CachingSoftReferenceFactory.class
  194 de/undercouch/gradle/tasks/download/org/gradle/internal/Factories.class
  195 de/undercouch/gradle/tasks/download/org/gradle/internal/Factory.class
  196 de/undercouch/gradle/tasks/download/org/gradle/internal/FileUtils$1.class
  197 de/undercouch/gradle/tasks/download/org/gradle/internal/FileUtils.class
  198 de/undercouch/gradle/tasks/download/org/gradle/internal/HasInternalProtocol.class
```

**Comment by johnrengelman** [comment]
Yeah, that's what's happening. You need this block in your build:
https://github.com/johnrengelman/shadow/blob/master/build.gradle#L23-L26
that we exclude it and the build runs fast.

**Comment by michel-kraemer** [comment]
Yes, that was it! Thank you so much! 👍

I noticed the section on "Special Handling of the Java Gradle Plugin Development Plugin" (https://imperceptiblethoughts.com/shadow/plugins/) saying that you need to remove the Gradle API dependency from `configurations.compile`, which did not work in my case. Your block removes it from `configurations.api`. I'm wondering if the documentation needs to be updated.

Also, it would be great if the plugin could show a warning so users know what is going on when relocating takes too long.

**Comment by johnrengelman** [comment]
Yeah, that’s probably just docs with the change from `compile`/`runtime` to `api`/`implementation`.

There’s not a good way to determine what is “too long” for a user. Maybe I can do something explicitly for detecting the gradle api and warning.
