### ISSUE TITLE
Feature request: Option to add minimized bundled JRE in the resulting shadow jar

### ISSUE THREAD

**Issue by chjan** [johnrengelman/shadow#748]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)

Would this at all be possible to do? Or if not included in this plugin, how to prepare that JRE using another approach. One could then use the Launch4j and then NSIS gradle plugins which are both easy to use. This compares to jpackage which I perceive as much more cryptic. For example, no tutorials explains how use jpackage to add DLL and other non-java files.

**Comment by johnrengelman** [comment]
Thanks for the request!
However, creating "executable jars" by bundling the JRE has been asked a number of times in issues and I am not interested in expanding Shadow to do this. I have pretty little time to maintain this plugin, so I'm keeping it narrow in scope. 
The shadow plugin has an API that allows other plugins/libraries to extend it. If someone wanted to build this capability as another plugin, I would consider PRs that add any needed APIs to make that happen (if they don't exist).
