### ISSUE TITLE
Plugin vanishing again Plugin [id: 'com.github.johnrengelman.shadow', version: '7.1.2'] was not found

### ISSUE THREAD

**Issue by cyberpwnn** [johnrengelman/shadow#750]
See https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/7.1.2/
See #221 

```
Build file '/Users/danielmills/Documents/development/workspace/Iris/build.gradle' line: 22

Plugin [id: 'com.github.johnrengelman.shadow', version: '7.1.2'] was not found in any of the following sources:

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

Note: Before it's mentioned, changing the jdk doesnt magically make the dependency available on a remote server. Doesnt work with java 11, 16, or 17, all working yesterday.

**Comment by johnrengelman** [comment]
I don’t manage the hosting infrastructure for the artifacts in Gradle’s plugin portal. You should raise an issue with them - https://discuss.gradle.org/

**Comment by cyberpwnn** [comment]
@johnrengelman do you intend to work around this issue so shadow can be used reliably or just ignore it?

**Comment by johnrengelman** [comment]
Not sure what your expecting here. Gradle plug-ins are resolved from their infrastructure. Any “workaround” would require users to apply shadow outside the normal/documented flow for Gradle plugins. 
As I said, raise an issue with Gradle. If it’s affecting this plugin, it’s affecting others.

**Comment by lnhrdt** [comment]
@johnrengelman I just stumbled into this as well. It appears to me that the Getting Started page in the User Guide is just incorrect. I opened #754 to fix it.

**Comment by sjmittal-plenty** [comment]
@johnrengelman The issue keeps surfacing up now also. We are using the DSL way of defining the plugin:

```
plugins {
  ....
  id 'com.github.johnrengelman.shadow' version '5.2.0'
  ....
}
```

Error we keep getting is:

```
Could not apply requested plugin [id: 'com.github.johnrengelman.shadow', version: '5.2.0'] as it does not provide a plugin with id 'com.github.johnrengelman.shadow'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> Plugin with id 'com.github.johnrengelman.shadow' not found.
```
