### ISSUE TITLE
Unable to use shadow to achieve the same result as jarjar tools for aTalk project

### ISSUE THREAD

**Issue by cmeng-git** [johnrengelman/shadow#761]
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Expected Behavior
Achieve the same result as the jarjar tool; "org.anarres.jarjar:jarjar-gradle:1.0.1"

### Actual Behavior
Unable to achieve the same result as the jarjar tool

### Gradle Build Script(s)
[build.gradle.zip](https://github.com/johnrengelman/shadow/files/8308304/build.gradle.zip)

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)

Please refer to the below link for aTalk project.
https://github.com/cmeng-git/atalk-android

aTalk is an open source that uses jarjar tools, as shown in the attached (also in the aTalk/build.gradle - refer to the above link).
However jarjar is unable to support gradle v7.0. aTalk has been trying to use shadow as a replacement tool for jarjar so as to upgrade to use gradle v7.0, but has not been successful to achieve the same result as the jarjar tools.

Appreciate your team's advice:
a. Does the shadow tool have all the same support functions as jarjar tool?
b. If so, appreciate if your team can provide the solution based on the attached build.gradle script.

**Comment by johnrengelman** [comment]
Sorry, I don't have the time to investigate your build or what jarjar does.
There's a lot of resources out there on shadow and some major projects (such as micronaut) use it to do native uber-jar building.

I think Stackoverflow might be a better location for this question.

Closing this.
