### ISSUE TITLE
Missing Shadow installs in Gradle Plugin repository

### ISSUE THREAD

**Issue by mindlessolipsist** [johnrengelman/shadow#762]
Shadow Version: 7.1
Gradle Version: 7.4.1
Java version: OpenJDK 17
Expected Behavior: Plugin is resolved
Actual Behavior: Exception

Just a heads up that the plug-in has worked fine for me in a JDK 17 (OpenJDK 17) Gradle 7.4.1 development environment, so I'm not sure the warning in the README about only working until Java 15 is necessary. Maybe better to re-word to "only tested up until Java 15", as some potential users might arbitrarily downgrade their projects for "compatibility."

I have, however, run into an issue with trying to refactor a single module Gradle project into a multi-module Gradle project and using a **buildSrc** directory:

_buildSrc/build.gradle_
```
plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal() // so that external plugins can be resolved in dependencies section
}

dependencies {
    implementation "com.github.jengelman.gradle.plugins:shadow:7.1.2"
}
```

Leads to:
```
> Could not resolve all files for configuration ':buildSrc:compileClasspath'.
   > Could not find com.github.jengelman.gradle.plugins:shadow:7.1.2.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/7.1.2/shadow-7.1.2.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :buildSrc

```

This is confusing, as the plugin works just fine when defined in the plugins section with the 7.x line. It makes sense, however, as when I look at:
https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/
https://repo.gradle.org/ui/native/jcenter/com/github/jengelman/gradle/plugins/shadow/

Neither repo has artifacts for the 7.x line. 

Why does artifact resolution work well in the `plugins` block but not in the `buildSrc`? One must infer that the repositories involved for resolution are different. If so, **where is the canonical home for the 7.x line?**

Have you considered publishing future versions under the namespace `org.imperceptiblethoughts`? Saves typing and would simplify manual searching repos...

**Comment by johnrengelman** [comment]
see the note here - https://imperceptiblethoughts.com/shadow/changes/#v7-1-0-2021-10-04

**Comment by johnrengelman** [comment]
The proper GAV coordinates are also shown in the Gradle plugin portal for each version.

**Comment by mindlessolipsist** [comment]
Thanks, that fixes it. For completeness to any searchers in the future, my successful `build.gradle` in `buildSrc` now looks like:

```
plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal() // so that external plugins can be resolved in dependencies section
}


dependencies {
    implementation "gradle.plugin.com.github.johnrengelman:shadow:7.1.2"
}
```
