### ISSUE TITLE
shadowJar gives warning or not getting applied

### ISSUE THREAD

**Issue by poqdavid** [johnrengelman/shadow#768]
### Shadow Version
7.1.2

### Gradle Version
7.4

### Expected Behavior
I can get rid of the warning by using `jar.dependsOn shadowJar` but when I do that task doesn't work not sure whats wrong but I want to get rid of the warnings and have a working shadowJar

### Actual Behavior
Either not relocating classes or it gives this warning https://gist.github.com/poqdavid/c16e6f3ff66ec496cc574f4ca9dcd9d2#file-log1-log

### Gradle Build Script(s)
https://gist.github.com/poqdavid/c16e6f3ff66ec496cc574f4ca9dcd9d2#file-build-gradle

**Comment by virustotalop** [comment]
What if you try doing `tasks.reobfJar.dependsOn 'shadowJar'`? If that doesn't work, if you could post your full build log that would help with debugging.

**Comment by poqdavid** [comment]
Yes, I managed to sort it out with `tasks.shadowJar.dependsOn('reobfJar')` and sorry forgot to close this
Also, apparently, it was reported here https://github.com/johnrengelman/shadow/issues/713
