### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by ipkpjersi** [johnrengelman/shadow#774]
Hey,

This isn't really a particular issue with the library itself, rather with the project.

The download link in the README of the repo appears to be broken, https://bintray.com/johnrengelman/gradle-plugins/gradle-shadow-plugin/_latestVersion seems to redirect to https://jfrog.com/distribution/?bintrayRD=1

I wanted to download the latest jar of this library, but it seems like I can't find the jar version of shadowjar anywhere (kind of ironic). 

Cheers.

**Comment by johnrengelman** [comment]
It's only published to the Gradle plugin portal now.
