### ISSUE TITLE
Specific classes are not being relocated in the @Metadata annotation

### ISSUE THREAD

**Issue by andriihorpenko** [johnrengelman/shadow#777]
### Shadow Version
7.1.2

### Gradle Version
7.3.3

### Expected Behavior
Relocate all classes in the `@Metadata` annotation

### Actual Behavior
Some classes in some cases are not being relocated inside the `@Metadata` annotation, causing `NoSuchMethodError`

On the screenshot below we can see that the first entry of `kotlin/reflect/KClass` is relocated to `shadow/kotlin/reflect/KClass`, but the next entry contains `kotlin/reflect/KClass`, which is for some reason not relocated.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/13716167/175789806-c9fdc6d9-ff0f-4717-8282-78e1d7936b8f.png">

The code which covers these Class uses is displayed below:
```kotlin
import io.suplab.vie.core.common.foundation.capability.providers.HostProvider
import kotlin.reflect.KClass

interface Host {
    fun <T : HostProvider> getProvider(provider: KClass<T>): T

    // ...
}
```

### Gradle Build Script(s)
```gradle
register<ConfigureShadowRelocation>("relocateClient") {
    target = getByName("shadeClient") as ShadowJar
}
register<ShadowJar>("shadeClient") {
    mergeServiceFiles()
    from(zipTree(artifactPath))
    exclude("**/module-info.class", "META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA")
    configurations = listOf(
        project.configurations.getByName("embedClient")
    )
    dependsOn("relocateClient")
}
```

### Content of Metadata annotation (stripped long d1)
```
@Metadata(mv = {1, 6, 0}, k = 1, xi = 48, d1 = {"..."}, d2 = {"Lio/suplab/vie/core/common/foundation/capability/types/Host;", "Lnet/minecraftforge/common/util/INBTSerializable;", "Lnet/minecraft/nbt/NBTTagCompound;", "addProvider", "", "provider", "Lio/suplab/vie/core/common/foundation/capability/providers/HostProvider;", "capabilities", "", "Lnet/minecraftforge/common/capabilities/Capability;", "(Lio/suplab/vie/core/common/foundation/capability/providers/HostProvider;[Lnet/minecraftforge/common/capabilities/Capability;)V", "getProvider", "T", "Lshadow/kotlin/reflect/KClass;", "(Lkotlin/reflect/KClass;)Lio/suplab/vie/core/common/foundation/capability/providers/HostProvider;", "capability", "(Lnet/minecraftforge/common/capabilities/Capability;)Lio/suplab/vie/core/common/foundation/capability/providers/HostProvider;", "hasProvider", "", "core"})
```

**Comment by Spliterash** [comment]
I'm not an expert on Gradle plugins, so I wrote not very high quality, but a working plugin that solves this problem
https://github.com/Spliterash/shadow-kotlin-relocate

**Comment by ninja-** [comment]
I noticed there is a case other than @Metadata which is not handled, it is reified types in delegated props:

```
arrayOfKProperty[0] = (KProperty)Reflection.property1((PropertyReference1)new PropertyReference1Impl(TheClass.class, "field", "someMethod()Lnot/relocated/type;", 0));
```
