### ISSUE TITLE
Integration for the osgi plug-in

### ISSUE THREAD

**Issue by romix** [johnrengelman/shadow#78]
Since both shadow and osgi plugins touch MANIFEST.MF, some kind of meaningful interaction between them should be definitely very useful and even required.

In particular, `Export-Package` and `Import-Package` should be generated properly, taking into account what was shaded and what was not shaded.

See http://www.gradle.org/docs/current/userguide/osgi_plugin.html for more information about the OSGI plug-in.

**Comment by mcoffin** [comment]
FYI going ahead and working on implementing this.

**Comment by ljacomet** [comment]
Hello, interested in this capability and willing to test or help with the dev ... but I admit not having much gradle experience.

**Comment by mcoffin** [comment]
@ljacomet I have a working version in [mcoffin/rogue/osgi-integration#78](https://github.com/mcoffin/shadow/tree/osgi-integration%2378). Now, I've been reluctant to open a PR & polish the code because I'm not sure that my implementation is too canonical. It adds a new task via a new plugin, `osgiShadowJar`, which effectively unzips the `shadowJar`, runs the OSGi plugin over it to generate a new manifest, then re-zips the jar. It works OK for my purposes, but isn't **too** flexible, so I definitely plan on changing it around before contributing it upstream.

**Comment by AdrienCab** [comment]
Any news on this integration as I would be very interested in such a feature.

**Comment by mcoffin** [comment]
I think I've found a more canonical way to do it, but it's going to take some time to code up once I find free time. In the meantime, you can do something like the following in your gradle files to emulate integration.

```groovy
import com.github.jengelman.gradle.plugins.shadow.tasks.DefaultInheritManifest
import org.gradle.api.internal.file.FileResolver

task osgiShadowJar(type: Jar, dependsOn: 'unzipShadowJar') {
    def mf = osgiManifest {
        classesDir = new File("$buildDir/tmp/osgiShadowJar-classes".toString())
        classpath = configurations.runtime
    }

    manifest = new DefaultInheritManifest(getServices().get(FileResolver.class))

    manifest.inheritFrom jar.manifest
    manifest.inheritFrom(mf) {
        eachEntry {
            if (OsgiOverride.OVERRIDE_KEYS.contains(it.getKey())) {
                it.setValue(it.getMergeValue())
            } else {
                it.setValue(it.getBaseValue())
            }
        }
    }

    classifier = "all-osgi"

    from(zipTree(project.shadowJar.archivePath.getPath())) {
        exclude("META-INF/MANIFEST.MF")
    }
}

class OsgiOverride {
    static final OVERRIDE_KEYS = ["Export-Package", "Import-Package"]
}
```

**Comment by johnrengelman** [comment]
Closing this as I feel its best implemented as a separate plugin.
