### ISSUE TITLE
No SoftwareComponent is created

### ISSUE THREAD

**Issue by natario1** [johnrengelman/shadow#789]
The project documentation says that the plugin automatically:

> Creates and registers the shadow component in the project (used for integrating with maven-publish).

As I read this, I would think that it creates a `SoftwareComponent` inside `project.components`. However, no component is created in my project. If this is expected, I think either the component should be added or documentation fixed.

### Shadow Version
7.1.2

### Gradle Version
7.4.2

**Comment by johnrengelman** [comment]
It provides a method to create a component to be registered in the maven-publish plugin. The components container is not extensible at the moment (at least the last time I checked).
