### ISSUE TITLE
Consider making `log4j-core` an optional / `runtimeOnly` dependency

### ISSUE THREAD

**Issue by sschuberth** [johnrengelman/shadow#790]
My understanding is that the `shadow` plugin depends on `log4j-core` not for its own logging (which should be / is done via the Gradle API anyway), but for the `Log4j2PluginsCacheFileTransformer`. This may [lead to confusions about dependency updates](https://github.com/ben-manes/gradle-versions-plugin/issues/686) for users of the `shadow` plugin that to not use Log4j in their own application (and consequently also not the `shadow` plugin's `Log4j2PluginsCacheFileTransformer`).

To avoid this, I'm wondering whether the dependency on `log4j-core` could be made optional in some way, e.g. by turning it into a `runtimeOnly` dependency?

**Comment by johnrengelman** [comment]
`runtimeOnly` would pull it in regardless. 

Not sure how this would work for users as trying to use the transformer would fail with class not found errors if the dependency isn't being resolved.

The _right_ answer is probably that all transformers should be in their own packages that can be added, but that's a lot of effort right now.


I'm going to close this in the meantime as I don't see a way to do this that doesn't create a bad experience for users.
