### ISSUE TITLE
Add a Transformer for stripping signature files

### ISSUE THREAD

**Issue by hbchai** [johnrengelman/shadow#801]
Merged JAR contents can contain signature files which cause JARs to fail to load or execute (https://stackoverflow.com/q/999489). Can we add a Transformer to src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers to strip out common signature files, and call this out in the documentation for merging JAR contents?

### Shadow Version

7.1.2

### Gradle Version

7.4

### Expected Behavior

It should be easier to resolve `Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes` errors for output JARs.

### Suggested code

```groovy
// Exclude signature files, to avoid "Invalid signature file digest" at runtime.
class ExcludeSignatureFilesTransformer implements Transformer {
  private static final logger = LoggerFactory.getLogger(ExcludeSignatureFilesTransformer.class)
  private final Spec<FileTreeElement> excludeSpec

  ExcludeSignatureFilesTransformer() {
    // See https://stackoverflow.com/q/999489
    excludeSpec = new PatternSet().exclude(
        'META-INF/*.DSA',
        'META-INF/*.RSA',
        'META-INF/*.SF').getAsExcludeSpec()
  }

  boolean canTransformResource(FileTreeElement element) {
    final boolean excluded = excludeSpec.isSatisfiedBy(element)
    if (excluded) {
      logger.info('Excluding signature file: ' + element.relativePath.pathString)
    }
    return excluded
  }

  void transform(TransformerContext context) {}

  boolean hasTransformedResource() {
    false  // Exclude the file resource.
  }

  void modifyOutputStream(ZipOutputStream jos, boolean preserveFileTimestamps) {}
}
```

**Comment by JD-CSTx** [comment]
The answers in the linked StackOverflow Question are more complicated, like here: https://stackoverflow.com/a/46014819/1534698. If you don't want to risk new errors, about the missing certificates, you should think about signing with new certificates or use a jar-in-jar solution.

**Comment by johnrengelman** [comment]
Thanks for the suggesting, but I'm not going to extend the capabilities of the plugin any further. The shadow API is robust enough for others to extend.

I'd be happy to include a spot in the docs for listing community transformers though.
