### ISSUE TITLE
Needs Java 19 support for minimize()

### ISSUE THREAD

**Issue by Jire** [johnrengelman/shadow#814]
Error `Unsupported class file major version 63`

When using Gradle toolchains via Kotlin extension:
```
kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(19))
    }
}
```

With latest Kotlin `1.8.0` (and `1.8.0-RC2`)

Only an issue when using `minimize()`

**Comment by kjetilv** [comment]
This seems to be on main already. I vote for a release :-)
