### ISSUE TITLE
Shadow 8.1.0 has not been published to `gradlePluginPortal`

### ISSUE THREAD

**Issue by Goooler** [johnrengelman/shadow#827]
Check https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow/8.1.0

**Comment by Goooler** [comment]
CC @johnrengelman

**Comment by johnrengelman** [comment]
Yeah with all the changes in the plugin publishing it went into a manual review state. Not sure exactly why. Will find out when one of their engineers looks tomorrow hopefully.

**Comment by Goooler** [comment]
Yeah, that might be the reason.

**Comment by Goooler** [comment]
Alright, it finally showing on `gradlePluginPortal`, good to see!

**Comment by Goooler** [comment]
> I think I'll just publish this as is with a note about the coordinate change

And a few things are worthy to note, see https://github.com/johnrengelman/shadow/pull/835#issuecomment-1447690576.
