### ISSUE TITLE
ConfigureShadowRelocation task is not resolvable in 8.1.0

### ISSUE THREAD

**Issue by iProdigy** [johnrengelman/shadow#834]
### Shadow Version
8.1.0

### Gradle Version
8.0.1

### Expected Behavior
`com.github.jengelman.gradle.plugins.shadow.tasks.ConfigureShadowRelocation` should be resolvable (or clearly documented that a change has occurred)

### Actual Behavior
`Unresolved reference: ConfigureShadowRelocation`

### Gradle Build Script(s)
https://github.com/twitch4j/twitch4j/blob/master/build.gradle.kts#L163 (we will be changing to the new `enableRelocation` syntax)

Caused by https://github.com/johnrengelman/shadow/pull/824/files#diff-6b2b213db0ba7e55e2818730dd5342e67e6c957c72b54acdba3a3b52885db9e2

Seems like this should've been clearly communicated in <https://github.com/johnrengelman/shadow/releases/tag/8.1.0> if intentional breaking change

**Comment by Goooler** [comment]
Use shadowJar instead, like:

```groovy
tasks.named("shadowJar", ShadowJar) {
    enableRelocation true
    relocationPrefix "shadow"
}
```
see 04b3c3c10bb1719e79fbddea636e258a53163cba.

**Comment by iProdigy** [comment]
Also it seems this documentation text needs to be updated:
```
To configure automatic dependency relocation, declare a task of type ConfigureShadowRelocation and configure the target parameter to be the ShadowJar task you wish to auto configure. You will also need to declare a task dependency so the tasks execute in the correct order.
```
https://github.com/johnrengelman/shadow/blob/master/src/docs/configuration/relocation/README.md#automatically-relocating-dependencies

**Comment by Proximyst** [comment]
@Goooler How are we expected to filter what dependencies are to be relocated now?

A common case might be including sub-projects which don't need relocation alongside dependencies that do. It's rather inconvenient if we need to have to include tests to ensure all packages have relocations specified before distribution.

**Comment by Goooler** [comment]
`enableRelocation` is disabled by default, see

https://github.com/johnrengelman/shadow/blob/49584a72811be917b2855ab365577517aa3a18e0/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.java#L34

**Comment by Proximyst** [comment]
I meant what option exists for this option now?

https://github.com/johnrengelman/shadow/blob/684bde3f64a44fdfae484b6b1dc6c184daf7af28/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ConfigureShadowRelocation.groovy#L23

There is no longer any way to e.g. create a configuration such as `relocatingImplementation` alongside the standard `implementation` such that Shadow includes `implementation` like normal, and `relocatingImplementation` specifically as relocating everything inside.

**Comment by Goooler** [comment]
`ConfigureShadowRelocation#getConfigurations` refed `ShadowJar#getConfigurations`, you just use the last one instead.

**Comment by Goooler** [comment]
`ConfigureShadowRelocation#getConfigurations` refed `ShadowJar#getConfigurations`, you just use the last one instead.

**Comment by Proximyst** [comment]
It did by _default_ yes, but we can't override `ShadowJar#getConfigurations` because then the classes that aren't in it won't be included in the final jar as `ShadowJar#getConfigurations` handles all included dependencies, not just 

Say for example you have a dependency on `project(":abc")` and `org.slf4j:slf4j-api`, you want to relocate `slf4j-api` but not the subproject. Previously, you could have them on separate configurations and have relocation include a subset of all shadowed dependencies. Now, you have to choose between relocating both, relocating neither, or only shadow and relocate 1 of the necessary dependencies.

The configuration task had an important feature in letting us choose which dependencies to relocate automatically, and which to do manually if at all.

**Comment by Proximyst** [comment]
For future readers, you can use the previous solution in a custom defined task if you want to preserve the desired behaviour (Kotlin DSL):

```kt
val relocatingApi: Configuration by configurations.creating
val relocatingImplementation: Configuration by configurations.creating
configurations.api { extendsFrom(relocatingApi) }
configurations.implementation { extendsFrom(relocatingImplementation) }

dependencies {
    relocatingApi(libs.caffeine)
    api(libs.jetbrains.annotations)
}

tasks {
    val configureRelocation by creating {
        val relocatingConfigurations = listOf(relocatingApi, relocatingImplementation)

        val packages = buildSet {
            relocatingConfigurations.forEach { config ->
                config.files.forEach { jar ->
                    JarFile(jar).use { jarFile ->
                        jarFile.entries().asSequence().forEach { entry ->
                            if (entry.name.endsWith(".class") && entry.name != "module-info.class") {
                                val lastSlash = entry.name.lastIndexOf('/')
                                val pkg = entry.name.substring(0..lastSlash).replace('/', '.')
                                add(pkg)
                            }
                        }
                    }
                }
            }
        }

        val prefix = "prefix-here"
        shadowJar {
            packages.forEach {
                relocate(it, "$prefix.$it")
            }
        }
    }

    shadowJar {
        dependsOn(configureRelocation)
    }
}
```

This will then relocate the packages of `libs.caffeine` but not `libs.jetbrains.annotations`; any packages that are present in both a `relocatingX` and non-relocating `x` configuration will be relocated as well, just like before. There's probably some neat way to make it cache, but it's fast enough for me not to care.

You may also want to create the configurations in some kind of `buildSrc` plugin if you use multiple projects.

**Comment by johnrengelman** [comment]
Added a note to the release notes and docs about this change.
