### ISSUE TITLE
Release 8.1.0 not published

### ISSUE THREAD

**Issue by snazy** [johnrengelman/shadow#836]
There's no 8.1.0 downloadable from Gradle Plugins repo.

https://plugins.gradle.org/m2/gradle/plugin/com/github/johnrengelman/shadow/8.1.0/shadow-8.1.0.pom returns HTTP/404

8.0.0 works.

https://plugins.gradle.org/m2/gradle/plugin/com/github/johnrengelman/shadow/ lists 7.1.0/, 7.1.1/, 7.1.2/ and 8.0.0/

**Comment by Goooler** [comment]
Duplicate of #827

**Comment by Goooler** [comment]
Check https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow/8.1.0

**Comment by snazy** [comment]
Ah, damn. I was looking for plugin-declarations, but there was a project dependency buried somewhere. NVM. Should work now.
