### ISSUE TITLE
Wrong coordinate on the project website?

### ISSUE THREAD

**Issue by oldergod** [johnrengelman/shadow#841]
The getting started page https://imperceptiblethoughts.com/shadow/getting-started/#default-java-groovy-tasks

gives those coordinates. I believe the prefix `gradle.plugin.` is wrong and should be removed?

```
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath 'gradle.plugin.com.github.johnrengelman:shadow:8.1.0'
    }
}
```

**Comment by Goooler** [comment]
Duplicate of #827
