### ISSUE TITLE
Resource file is moved

### ISSUE THREAD

**Issue by nicofari** [johnrengelman/shadow#846]
I have a configuration file in src/main/resources. My code reads and expects the file to be there.
After "shadowJarring"  the jar contains the file, but in the "root" so my code fails to find it

### Shadow Version
7.1.2

### Gradle Version
7.6

### Expected Behavior
the file should stay in src/main/resources

### Actual Behavior
the file is moved in the root of the jar

### Gradle Build Script(s)
buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "org.jetbrains.kotlin.jvm" version "${kotlinVersion}"
    id "com.github.johnrengelman.shadow" version "7.1.2"
}

apply plugin: "com.github.johnrengelman.shadow"
apply plugin: "java"

repositories {
    mavenCentral()
}

compileKotlin.kotlinOptions.jvmTarget = "11"
compileTestKotlin.kotlinOptions.jvmTarget = "11"

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

test {
    useJUnitPlatform()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}"
    implementation platform("org.http4k:http4k-bom:${http4kVersion}")
    implementation "org.http4k:http4k-core"
    implementation "org.http4k:http4k-format-jackson-yaml:${http4kVersion}"
    implementation "org.http4k:http4k-format-jackson:4.40.1.0"
    implementation "org.http4k:http4k-opentelemetry:${http4kVersion}"
    implementation "org.apache.pdfbox:pdfbox:2.0.27"
    implementation "de.redsix:pdfcompare:1.1.61"

    testImplementation platform("org.junit:junit-bom:${junitVersion}")
    testImplementation "org.http4k:http4k-testing-hamkrest"
    testImplementation "org.junit.jupiter:junit-jupiter-api"
    testImplementation "org.junit.jupiter:junit-jupiter-engine"
}

shadowJar {
    manifest.attributes['Main-Class'] = 'it.multidialogo.multiprinter.MultiprinterKt'
    archiveBaseName.set("multiprinter")
    archiveClassifier.set(null)
    archiveVersion.set(null)
    mergeServiceFiles()
}

**Comment by johnrengelman** [comment]
Hey @nicofari there really isn't enough here to debug the issue. Based on your build file, Shadow won't do any file renaming (you aren't activating any package renaming).
What's the full path inside `src/resources` for your file? What is the code that is loading that file look like?

**Comment by nicofari** [comment]
Hi John
the full path is

`/src/main/resource/modules.yaml`

the code which reads it is:

```
        val m = ObjectMapper(YAMLFactory()).registerKotlinModule()
        val moduleRegistry: ModuleRegistry =
            m.readValue(File("src/main/resources/modules.yaml"), ModuleRegistry::class.java)

```
thanks for your help

**Comment by johnrengelman** [comment]
Yeah, that path won’t be correct when reading the file from inside a Jar. The contents of “src/resources” end up in the root of the Jar. 
you will need to check the documentation for the ObjectMapper whether it supports reading from a Jar resource. 

Closing as this is not a shadow issue.
