### ISSUE TITLE
Bundling Shadow with my own Plugins

### ISSUE THREAD

**Issue by stackmagic** [johnrengelman/shadow#99]
I'm writing a bunch of my own plugins and I want the user of my plugins to add just 1 repo and dependency to his/her buildscript closure - because my plugins depend on the shadow plugin, I would like to bundle the shadow plugin with my own plugins... using the shadow plugin to build this single all-encompassing jar.

I tried a dozen things but can't seem to get this to work. I always end up with a 42MB jar which includes (I suspect) all of

```
dependencies {
    localGroovy()
    gradleApi()
}
```

because my plugins need these to compile but obviously I don't want to bundle all gradle/groovy with my own plugins...just shadowJar and its immediate 'non-provided' dependencies.

Is there a way to accomplish this? There has to be. I tried adding new configurations and referencing them, I tried an excplicit include of shadowJar (which by your docs would add an implicit global exclude for everything else) etc - nothing works...

Here's my (broken) build script: https://gist.github.com/stackmagic/01e6d7822a4070138db2

**Comment by dnault** [comment]
+1 Would be nice to have a convenient way to exclude localGroovy() and gradleApi() when building a shadow jar. Use case: building a shadow jar that contains both a Gradle plugin and some custom Ant tasks. I want to be kind to the Ant users and not make them specify a nasty class path when loading the tasks.

**Comment by kashike** [comment]
+1 For being able to exclude gradleApi(), especially.

**Comment by johnrengelman** [comment]
This will happen. Just not for a couple weeks. Heading on vacation for a week tomorrow and won't have access to computer. I'll look at implementing this afterwards.

**Comment by badlogic** [comment]
Any chance of this getting resolved, or pointers on how to resolve it and submit a PR?

**Comment by johnrengelman** [comment]
@badlogic - I'll be looking at doing this with Shadow itself for the next release (when Gradle 2.14 is released), then I'll have an example.
Off the cuff, tI think it will involve creating a new `configuration` and then adding your dependencies to that and reconfiguring the `shadowJar` task to use it:

```
configurations {
  plugin
}

dependencies {
  plugin 'somedep:someartifict:version'
}

shadowJar {
  configurations = [project.configurations.plugin]
}
```

**Comment by johnrengelman** [comment]
you'd still need to add the dependency to compile scope or configure the `compile` tasks to also use `configurations.plugin` in their classpath.

**Comment by johnrengelman** [comment]
This will be supported in Shadow v2.0.0 by doing the following:

```
dependencies {
  shadow gradleApi()
  shadow localGroovy()

  compile "some:other-plugin:1.2.3"
}
```

In fact Shadow v2.0.0 will be built this way itself.

**Comment by badlogic** [comment]
Thanks!
